### ISSUE TITLE
Segmentation fault when using libimobiledevice 1.1.5

### ISSUE THREAD

**Issue by peol** [google/ios-webkit-debug-proxy#10]
Hi,

as discussed in #2, I'm reporting this issue as a separate one. The build was successful but when attaching my iPhone 5, ios-webkit-debug-proxy crashes with a segfault.

This is using OSX 10.8.3 and building manually from master (not the brew formula - that also fails though).

Downgrading to libimobiledevice to 1.1.4 "fixes" it.

**Comment by artygus** [comment]
now 1.2.0 is a minimal required version of libimobiledevice, since https://github.com/google/ios-webkit-debug-proxy/commit/8a90693a4fbd86f0c320c83954d6790b63381334#diff-67e997bcfdac55191033d57a16d1408aR18
