### ISSUE TITLE
I want to support Windows version

### ISSUE THREAD

**Issue by Anselz** [google/ios-webkit-debug-proxy#102]
We are hoping to run under Windows.THX

**Comment by artygus** [comment]
@Anselz in the meantime you can check out https://github.com/artygus/ios-webkit-debug-proxy-win32

**Comment by Anselz** [comment]
@artygus Awesome!

**Comment by paulirish** [comment]
Pointed to artygus's port in the readme. Closing this for now. We'll keep open the other tracking ticket to merge these eventually.
