### ISSUE TITLE
Creating a new release for the project

### ISSUE THREAD

**Issue by bigfei** [google/ios-webkit-debug-proxy#108]
This latest release of this project is on the 2014.07. It is a quite long time for a project release. Can you guy make a new one cause many  package management software (eg, [homebrew](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ios-webkit-debug-proxy.rb)) are still using the old buggy version? Thanks.

**Comment by paulirish** [comment]
@jchuong can you turn out a rls?

**Comment by jchuong** [comment]
Okay, I created release 1.5.  I'm not sure as to how to set it up for homebrew.

**Comment by artygus** [comment]
@jchuong I think you this file https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ios-webkit-debug-proxy.rb should be updated

**Comment by jchuong** [comment]
@artygus Thanks, I was just looking up the steps now but I'll let you handle it.

**Comment by artygus** [comment]
@jchuong https://github.com/Homebrew/homebrew/pull/41347 has been merged
