### ISSUE TITLE
No available formula for zlib

### ISSUE THREAD

**Issue by hueyy** [google/ios-webkit-debug-proxy#109]
Upon running `brew install ios-webkit-debug-proxy`, I receive the following output:

    Error: No available formula for zlib (dependency of ios-webkit-debug-proxy)
    Searching formulae...
    lzlib
    Searching taps...

`zlib` appears to have been replaced by `lzlib` in brew. I've installed `lzlib` instead, but I'm still facing this issue. Any way around this?

**Comment by artygus** [comment]
@leejinhuey AFAIK zlib is not required to compile iwdp directly, it might be needed by one of it's dependencies, e.g. openssl or libxml

**Comment by leejinhuey** [comment]
You're right, it's `openssl` that requires `zlib`

    Error: No available formula for zlib (dependency of openssl)
    Searching formulae...
    lzlib
    Searching taps...

Does this mean I should file this issue with `openssl`?

**Comment by paulirish** [comment]
Upstream issue. Might have been resolved already, even.
