### ISSUE TITLE
Remote.evaluate request with large expression (e.g. 7500 characters or more) is causing a web socket disconnect

### ISSUE THREAD

**Issue by snevesbarros** [google/ios-webkit-debug-proxy#11]
When attempting to send a large javascript expression I noticed that I keep getting disconnected. 

This works fine:
{"id": 1, "method": "Runtime.evaluate", "params": {"expression": " document.title", "objectGroup": "console", "returnByValue": true }}

This works fine:
{"id": 1, "method": "Runtime.evaluate", "params": {"expression": "(function(name){console.info('printed: ' + name)})('small number of characters')", "objectGroup": "console", "returnByValue": true }}

This fails:
{"id": 1, "method": "Runtime.evaluate", "params": {"expression": "(function(name){console.info('printed: ' + name)})('Add more than 7500 characters here.....etc.(didn't want to flood this ticket :))')", "objectGroup": "console", "returnByValue": true }}

Running this on the console gives the same result:
http://localhost:27753/devtools/devtools.html?host=localhost:27753&page=1

We are attempting to send a compressed javascript library (e.g. the webdriver find_element library as part of the request)  which contains more than 7500 characters.

Any suggestions on how this could be resolved?

Thanks,

Sergio

**Comment by rosesandhello** [comment]
This issue does not appear to be completely resolved. The upper limit now seems to be around 16K and seems to apply to both incoming and outgoing messages.
