### ISSUE TITLE
Not able to inspect UIWebview

### ISSUE THREAD

**Issue by shmdhussain** [google/ios-webkit-debug-proxy#110]
I am not able to debug/inspect in iPhone 5s (iOS 8.1.1) the native UIwebview app using the ios-webkit-debug-proxy, i am able to debug the mobile safari pages using the urls 'http://localhost:9221/" and "http://localhost:9222/ "and "chrome-devtools://devtools/bundled/devtools.html?ws=localhost:9222/devtools/page/1" used to list devices and its opened tabs.

But not able to inspect native webview applications, today only i installed ios-webkit-debug-proxy in my mac (OSX 10.10) and chrome 43.

Please help me in this. Thanks in advance.

**Comment by shmdhussain** [comment]
When i searched in net I found that this is not possible for the app installed from app store, possible only for the app insatlled from xcode to my device "Not only can you remotely debug web pages in mobile Safari, you can remotely debug any web page in any plain old UIWebView, which just happens to include that UIWebView hosting your PhoneGap application. Note that you can only inspect UIWebView content in apps that were transferred to a device from XCode. Sorry, no inspecting apps downloaded from the App Store!" 

see this link:http://phonegap-tips.com/articles/debugging-ios-phonegap-apps-with-safaris-web-inspector.html

**Comment by artygus** [comment]
Unfortunately it's not possible
