### ISSUE TITLE
Could it work with Cocoa WebView on Mac OS?

### ISSUE THREAD

**Issue by hy9be** [google/ios-webkit-debug-proxy#114]
Since it could work against UIWebViews on iOS, could it work with Cocoa WebView on Mac OS? If not, any idea on supporting it with modest code changes?

Thanks!

**Comment by paulirish** [comment]
Perhaps! but that is out of scope for the project.  Would be happy to see someone try to make this work, but it'd likely not share much of iwdp's implementation.
