### ISSUE TITLE
Mixed content - websocket error

### ISSUE THREAD

**Issue by andreinitescu** [google/ios-webkit-debug-proxy#115]
Im using the WIndows port and here's what I got:

`Mixed Content: The page at 'https://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html?host=localhost:9222&page=2' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 
'ws://localhost:9222/devtools/page/2'. This request has been blocked; this endpoint must be available over WSS.WebInspector.loaded @ DevTools.js:3104
DevTools.js:3104 Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
`

it looks like the request is to ws:// and not to wss:// and since it's coming on a https:// page, it fails

**Comment by artygus** [comment]
@andreinitescu do you see a shield icon in the address bar?

**Comment by andreinitescu** [comment]
wooooow... it works! 
thank you! :)

**Comment by artygus** [comment]
@andreinitescu welcome

**Comment by MrOutput** [comment]
@artygus  thank you

**Comment by ruanhao** [comment]
there is a shield on the address bar in Chrome, what to do when it is Safari ? How to setup?

**Comment by nauman-qc** [comment]
@artygus

**Comment by NegrilloC** [comment]
@nauman-qc Once you select the shield there should be an option to "Load unsafe scripts" after selecting that option it should be woking.

**Comment by jonexyq** [comment]
I need to remind user click the shield icon? could you tell me how to remind my user?
