### ISSUE TITLE
Disconnecting right after connected

### ISSUE THREAD

**Issue by xing-zhi** [google/ios-webkit-debug-proxy#116]
On Debian 8, after connecting, it showed information below and then disconnected.

 ```
Invalid message _rpc_reportConnectedApplicationList: <dict>
	<key>WIRApplicationDictionaryKey</key>
	<dict>
		<key>PID:71</key>
		<dict>
			<key>WIRApplicationIdentifierKey</key>
			<key>PID:71</key>
			<key>WIRIsApplicationProxyKey</key>
			<false/>
			<key>WIRApplicationNameKey</key>
			<string></string>
			<key>WIRApplicationBundleIdentifierKey</key>
			<string>lockdownd</string>
			<key>WIRIsApplicationActiveKey</key>
			<integer>1</integer>
		</dict>
	</dict>
</dict>
```

Could anyone tell me what's wrong with this? 

Thanks!

**Comment by pondahai** [comment]
<key>WIRApplicationIdentifierKey</key>
            <key>PID:71</key>   <==================== ???may be iOS's bug

**Comment by artygus** [comment]
@pondahai yeap looks like a bug, do you experience troubles with iOS 9?

**Comment by pondahai** [comment]
Yes, after upgrade to iOS 9.0.2

**Comment by artygus** [comment]
@pondahai try to update libplist to 1.12

**Comment by artygus** [comment]
closing this one up, no reply from OP
