### ISSUE TITLE
Unable to retrieve device list!

### ISSUE THREAD

**Issue by octoxan** [google/ios-webkit-debug-proxy#118]
Ran the install, it failed because it needed newer versions. Manually built and installed latest libimobiledevice. Now ios-webkit-debug-proxy works except 

    idevice_id -l 

throws:

    "ERROR: Unable to retrieve device list!"

**Comment by artygus** [comment]
idevice_id is not a part of ios-webkit-deub-proxy utility, please report the issue to libimobiliedevice
