### ISSUE TITLE
Can't expand the view for source folders

### ISSUE THREAD

**Issue by programmin1** [google/ios-webkit-debug-proxy#123]
When I go to sources and try to expand one of the folders in the left panel, it doesn't work. When I go to the devtools console of the devtools page I see it's having problems:

``
Uncaught TypeError: window.getComputedStyle(...).getPropertyCSSValue is not a function:
TreeElement.isEventWithinDisclosureTriangle @ DevTools.js:2771
TreeElement.treeElementToggled @ DevTools.js:2489
``

**Comment by artygus** [comment]
@programmin1 you can try to run iwdp with `-f http://frontend.chrome-dev.tools/serve_rev/@198714/inspector.html`

**Comment by artygus** [comment]
this is because safari and chrome dev tools protocols diverged too much and what you see is a result of keeping old devtools alive, you can try bundled devtools in this case, e.q. `chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1`
