### ISSUE TITLE
iOS Web Kit debug Proxy connects and disconnects immediately

### ISSUE THREAD

**Issue by priyatech** [google/ios-webkit-debug-proxy#129]
iOS Web Kit debug Proxy connects with the iOS device and disconnects immediately. Once in 10 times plugging and unplugging and changing the port it connects. Is there any  iOS Web Kit debug Proxy cache on device or mac to clean up? 

Xcode7.2 
OSx10.11
iOS Device 7.1
iPhone 5S

**Comment by artygus** [comment]
Sounds like libimobiledevice problem, please report to http://github.com/libimobiledevice/libimobiledevice if problem persists.

The only cache I could think of is lockdown dir `/var/db/lockdown` on OS X, `/var/lib/lockdown` on Linux
