### ISSUE TITLE
LiveEdit JS

### ISSUE THREAD

**Issue by RaphaelDDL** [google/ios-webkit-debug-proxy#130]
Hi everyone,

In first place, thanks for this awesome tool! Was tired of Safari lame inspector :)

I tried to Live edit JS just like Chrome but every breakpoint goes into a VM#### tab, which then editing and saving ain't being recompiled/re-run.

Not sure if I'm doing something wrong or simply isn't available. 

But from what I was thinking, Web Inspector doesn't have that kind of feature shipped, so I guess proxy wouldn't be able to translate that. Am I right?

Thanks!

Regards,
Raphael

**Comment by artygus** [comment]
Yeap, you're right
