### ISSUE TITLE
Run 2 proxies in 2 different ports

### ISSUE THREAD

**Issue by warapitiya** [google/ios-webkit-debug-proxy#132]
Trying to run 2 different ios-webkit-debug-proxies in different port parallel. but 1st one get running and the 2nd gives me an error. 

``` js
ss.remove_fd(9)
ss.accept server=4 new_client=9
ss.add_fd(9)
ss.recv fd=9 len=63
ws.recv[63]:
 47 45 54 20 2F 6A 73 6F 6E 20 48 54 54 50 2F 31 2E 31 0D  GET /json HTTP/1.1.
 0A                                                        .
 48 6F 73 74 3A 20 6C 6F 63 61 6C 68 6F 73 74 3A 39 32 32  Host: localhost:922
 32 0D 0A                                                  2..
 43 6F 6E 6E 65 63 74 69 6F 6E 3A 20 63 6C 6F 73 65 0D 0A  Connection: close..
 0D 0A
```

**Comment by artygus** [comment]
@warapitiya can you confirm you tried custom devices ports? e.g.
- first instance `ios_webkit_debug_proxy`
- second instance `os_webkit_debug_proxy -c null:9321,:9322-9332`

**Comment by artygus** [comment]
Closing now since no reply from OP. Locally small demo works as expected
