### ISSUE TITLE
installing ios-webkit-debug-proxy on mac OS X 10.11.13

### ISSUE THREAD

**Issue by pkvelu007** [google/ios-webkit-debug-proxy#133]
Hi, 

When I am trying to install ios-webkit-debug-proxy  on OSX 10.11.13 using the command brew install os-webkit-debug-proxy --- I am facing following issue ---

""""""
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing dependencies for ios-webkit-debug-proxy: openssl, libimobi
==> Installing ios-webkit-debug-proxy dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2d.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://raw.githubusercontent.com/DomT4/LibreMirror/master/OpenS

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://www.mirrorservice.org/sites/ftp.openssl.org/source/opens

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "openssl"
Download failed: https://www.mirrorservice.org/sites/ftp.openssl.org/source/openssl-1.0.2d.tar.gz

"""""

Please let me know how to fix this issue..

**Comment by artygus** [comment]
@pkvelu007 did you try `brew update`?

**Comment by brandonros** [comment]
Slightly similar issue. Same OS version, can't compile/install.

I ran `brew update`, then `brew install ios-webkit-debug-proxy` and got this

```
➜  ~  brew install ios-webkit-debug-proxy
==> Installing dependencies for ios-webkit-debug-proxy: libusb, usbmuxd, libtasn1, openssl, libimobiledevice
==> Installing ios-webkit-debug-proxy dependency: libusb
==> Downloading https://downloads.sourceforge.net/project/libusb/libusb-1.0/libusb-1.0.20/libusb-1.0.20.tar.bz2
Already downloaded: /Library/Caches/Homebrew/libusb-1.0.20.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/libusb/1.0.20
Last 15 lines from /Users/Marketing/Library/Logs/Homebrew/libusb/01.configure:
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/tmp/libusb20160328-33281-1s65z36/libusb-1.0.20':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
```

**Comment by brandonros** [comment]
A quick Google search shows that my Xcode is outdated. My apologies!
