### ISSUE TITLE
Ship prebuilt binaries on NPM?

### ISSUE THREAD

**Issue by auchenberg** [google/ios-webkit-debug-proxy#136]
In order to simplify the installation of this wonderful component I've been thinking if a similar model to https://github.com/electron-userland/electron-prebuilt to be adapted?

Provide prebuild binaries via NPM instead relying on OSX-specific homebrew?

This could be interesting, specially if @artygus plans to merge in his https://github.com/artygus/ios-webkit-debug-proxy-win32 fork.

**Comment by artygus** [comment]
@auchenberg looks good, but I don't think win32 port will ever be merged into main branch, because it relies on libimobiledevice libraries and it doesn't look like those guys are really interested in win32 platform (though parts of the libraries code is win32-compatible). I decided to go with mingw builds, and it's almost there, just need a minor tweaks https://github.com/google/ios-webkit-debug-proxy/pull/124

**Comment by auchenberg** [comment]
Doesn't this non-win32 already rely on `libimobiledevice`, per https://github.com/google/ios-webkit-debug-proxy/blob/master/configure.ac#L18?

**Comment by artygus** [comment]
It is for sure and libimobiledevice successfully builds with mingw. Ah yes, just thought electron-prebuilt is used for different purpose. It's too late here, need some sleep.

**Comment by auchenberg** [comment]
Alrighty. Sleep tight @artygus :zzz: :sleeping:

**Comment by artygus** [comment]
Thanks @auchenberg  :sleepy:

**Comment by SrinivasanTarget** [comment]
@artygus @auchenberg Any update on this? Any ETA?

**Comment by auchenberg** [comment]
At Microsoft we are shipping our "protocol adapter" for Edge via NPM. https://github.com/Microsoft/edge-diagnostics-adapter.

Makes it super easy to be consumed from node projects.

**Comment by SrinivasanTarget** [comment]
@auchenberg Ok when are we going to do the same for ios-webkit-debug-proxy? It would be easy for node projects like appium depending on this repo.

**Comment by SrinivasanTarget** [comment]
@auchenberg Any update on this?

**Comment by artygus** [comment]
win32 is finally here, gonna craft npm in the next few days

**Comment by IAMtheIAM** [comment]
Did this ever happen?

**Comment by artygus** [comment]
never managed to do so, scoop does the job on windows
