### ISSUE TITLE
Add screencasting support

### ISSUE THREAD

**Issue by auchenberg** [google/ios-webkit-debug-proxy#137]
Chrome DevTools supports [screencasting](http://blog.chromium.org/2013/12/chrome-devtools-for-mobile-emulate-and.html) of the screen of the attached device.

[![ScreenShot](http://img.youtube.com/vi/Q7rEFEMpwe4/maxresdefault.jpg)](http://youtu.be/Q7rEFEMpwe4)
#### How

It should be possible to get a screen stream from connected iOS devices via https://github.com/WPO-Foundation/xrecord, where the frames could be extracted and send over the wire as Base64 encoded PNG frames.
#### Steps to implement:
- Reply `{ result: true }` to the `Page.canScreencast` method request made from DevTools.
- Implement logic to capture screenshot of running Android app as JPEG, base64 encode the image and emit a `Page.screencastFrame` event, with the following data-structure:

``` javascript
{
    method: 'Page.screencastFrame',
    params: {
        data: <base64 image>,
        metadata: {
            pageScaleFactor: 1,
            offsetTop: 0,
            deviceWidth: <width>,
            deviceHeight: <height>,
            scrollOffsetX: 0,
            scrollOffsetY: 0
        }
    }
}
```
#### Similar efforts

https://github.com/facebook/stetho/issues/190

https://github.com/Microsoft/IEDiagnosticsAdapter/issues/25

**Comment by tregusti** [comment]
I would really like to have this functionality added too!

**Comment by auchenberg** [comment]
Implemented in https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter
