### ISSUE TITLE
Package requirements unmet on Ubuntu 14.04

### ISSUE THREAD

**Issue by jdomeara** [google/ios-webkit-debug-proxy#138]
After I run ./autogen.sh, I get the following error message:

```
configure: error: Package requirements (libimobiledevice-1.0 >= 1.2.0) were not met:

Requested 'libimobiledevice-1.0 >= 1.2.0' but version of libimobiledevice is 1.1.6

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libimobiledevice_CFLAGS
and libimobiledevice_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

I tried installing the updaed packages from http://www.libimobiledevice.org/ but that does not seem to solve anything. Has anyone been able to solve this issue?

**Comment by jrbeaudoin** [comment]
Hi @jdomeara!

I followed this tutorial and it worked perfectily:
http://askubuntu.com/a/672018/531745

Hope it helps.

**Comment by artygus** [comment]
looks like missing package version, thus the issue is not related to the utility
