### ISSUE TITLE
Unable to run make previous declaration of 'idevice_connection_get_fd'

### ISSUE THREAD

**Issue by kiwiot** [google/ios-webkit-debug-proxy#139]
Not sure where to start to fix this issue. 

`webinspector.c  -fPIC -DPIC -o .libs/webinspector.o
webinspector.c:57:11: error: conflicting types for 'idevice_connection_get_fd'
 wi_status idevice_connection_get_fd(idevice_connection_t connection,
           ^
In file included from /usr/local/include/libimobiledevice/installation_proxy.h:33:0,
                 from webinspector.c:18:
/usr/local/include/libimobiledevice/libimobiledevice.h:250:17: note: previous declaration of 'idevice_connection_get_fd' was here
 idevice_error_t idevice_connection_get_fd(idevice_connection_t connection, int *fd);
                 ^
make[2]: *** [webinspector.lo] Error 1
make[2]: Leaving directory `/home/jared/src/ios-webkit-debug-proxy/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/jared/src/ios-webkit-debug-proxy'
make: *** [all] Error 2
`

**Comment by BrandKNY** [comment]
Also experiencing this same issue: Ubuntu 14.04 (following mainly from [this guide](http://askubuntu.com/questions/598940/libimobiledevice-1-2-ios-8-support-for-ubuntu-14-04-trusty/712154#712154) ). Anyone have some feedback or recommendations? Will explore the issue myself and post back if I figure something out.

**Comment by HOYS** [comment]
Also experiencing this issue on Ubuntu 14.04 VM.

**Comment by tommyJS** [comment]
+1 Ubuntu 16.04 LTS

**Comment by artygus** [comment]
should be fixed with #141
