### ISSUE TITLE
IOS 9.3.2 could not connect to lockdown 

### ISSUE THREAD

**Issue by GeneGenie** [google/ios-webkit-debug-proxy#142]
Ubuntu 14.04
1. IOS safari inspector enabled 
2. Trust confirmation accepted 
   BUT 

```
$ ios_webkit_debug_proxy --debug
ss.add_server_fd(3)
Listing devices on :9221
ss.add_fd(4)
ss.add_server_fd(5)
ss.remove_server_fd(5)
ss.recv fd=4 len=932
ss.add_server_fd(5)
Could not connect to lockdownd. Exiting.: Operation now in progress
ss.remove_server_fd(5)
Unable to attach 9c5dd... inspector
```

```
$ idevicepair pair
SUCCESS: Paired with device 9c5dd...
```

```
idevice_id -l
9c5dd...
```

**Comment by peresbruno** [comment]
Hi!

Same problem here.

**Comment by artygus** [comment]
hi @GeneGenie is it still happening? did you try to plug/unplug a few times?

**Comment by GeneGenie** [comment]
Yes. Many times.

пятница, 24 июня 2016 г. пользователь Arty Gus написал:

**Comment by artygus** [comment]
what os version do you use?

**Comment by GeneGenie** [comment]
> Ubuntu 14.04

**Comment by BrunoSalerno** [comment]
Exact same problem here. Also, iOS 9.3.2 and Ubuntu 14.04.

**Comment by srsamarthyam** [comment]
Set the permissions for /var/db/lockdown folder.

**Comment by nethi216** [comment]
This solution worked for me

Access this folder '/var/db/lockdown' through terminal

and then ls - l (will give you the list of plist files)

remove all plist files except 'SystemConfiguration.plist'

run this command 'sudo chmod 777 /var/db/lockdown' to set the permissions

**Comment by artygus** [comment]
did proposed solution work for you @GeneGenie?

**Comment by LeFredd** [comment]
Please where is /var/db/lockdow on Ubuntu 16.04?
