### ISSUE TITLE
It doesn't work with ios10.

### ISSUE THREAD

**Issue by dania-ru** [google/ios-webkit-debug-proxy#144]

**Comment by artygus** [comment]
any errors?

**Comment by dania-ru** [comment]
I'm running ios-webkit-debug-proxy on Windows.
When I try to send a command to device from my machine's browser (for example: {"id":1,"method":"Page.navigate","params": {"url":"http://www.google.com/"}}), the webpage reloads on the device, showing the error message "A problem occurred with this webpage so it was reloaded". Looking at the traffic I see that webkit debug proxy receives the following messages sequence:   _rpc_applicationUpdated
 _rpc_applicationDisconnected
_rpc_applicationConnected (with another PID of com.apple.WebKit.WebContent )
And that page number on device changes...

When doing the same thing when connected to an iOS9 device, we get:
_rpc_applicationSentListing
_rpc_applicationSentData
And whatever operation I try to perform works...

BTW, when sending the same command from Safari on a Mac connected to the iOS10, it always succeeds.

Has anyone played with iOS10 beta and seen this issue?

**Comment by EliyahuStern** [comment]
I have similar issues with iOS 10 Beta 1 too

**Comment by EliyahuStern** [comment]
I am getting this error message:
Invalid message _rpc_reportConnectedDriverList: <dict>
	<key>WIRDriverDictionaryKey</key>
	<dict>
	</dict>
</dict>

**Comment by cheatnsutar008** [comment]
Invalid message _rpc_reportConnectedDriverList: <dict>
    <key>WIRDriverDictionaryKey</key>
    <dict>
    </dict>
</dict>
Same for me. Maybe issue with libimobiledevice?

**Comment by artygus** [comment]
I'll look into it

**Comment by artygus** [comment]
@cheatnsutar008 it may be, but in this case `_rpc_reportConnectedDriverList` is simply not handled by the utility and it's not the only problem, need to do some reasearch

**Comment by artygus** [comment]
iOS 10 should be handled now, but you need to build from HEAD

**Comment by yaphatak** [comment]
@artygus : When we can install this via brew install...?

**Comment by artygus** [comment]
@yaphatak it's possible right now with `brew install --HEAD`

**Comment by yaphatak** [comment]
Thanks I will give a try.

**Comment by aroramayank2002** [comment]
We have our device iPhone 6s updated to IOS 10 but since then proxy is failing to connect:

Command used:  
    ios_webkit_debug_proxy -c f79e0cb99fb720592ab3b956b4173b049ca69243:9226
Error:
  Could not connect to lockdownd. Exiting.: Broken pipe
  Unable to attach f79e0cb99fb720592ab3b956b4173b049ca69243 inspector 

It's able to connect to devices still on IOS 9.3

**Comment by artygus** [comment]
@aroramayank2002 `brew upgrade libimobiledevice --HEAD` #161

**Comment by aroramayank2002** [comment]
Thanks artygus, that is the quickest reply I have got on github. 
Tried it yesterday, now it says:
Invalid message _rpc_reportConnectedDriverList: <dict>
	<key>WIRDriverDictionaryKey</key>
	<dict>
	</dict>
</dict> 

Looking into it.

**Comment by artygus** [comment]
hi @aroramayank2002 😄, looks like you have outdated version of utility, please try `brew update && brew upgrade ios-webkit-debug-proxy`

**Comment by aroramayank2002** [comment]
@artygus, you just broke last record for fast response. 

Tried the above command here is the output:
mayank.arora$ brew update && brew upgrade ios-webkit-debug-proxy

/usr/local/Library/Homebrew/cmd/update.sh: line 12: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 12: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 12: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 12: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 12: /usr/local/Library/ENV/scm/git: No such file or directory
==> Homebrew has enabled anonymous aggregate user behaviour analytics
Read the analytics documentation (and how to opt-out) here:
  https://git.io/brew-analytics
Error: update-report should not be called directly!

Tried the same commands on two lines and it worked... Thanks a lot artygus. You deserver a treat, let me know if you come to Stockholm in future ;)
