### ISSUE TITLE
Could not connect to lockdownd. Exiting.: Undefined error: 0

### ISSUE THREAD

**Issue by KrazySush** [google/ios-webkit-debug-proxy#145]
Hi,
I am getting error while starting ios-webkit-debug-proxy as:
**Could not connect to lockdownd. Exiting.: Undefined error: 0**
.
.
**Unable to attach \<Device UDID\> inspector**

I have following configuration:
MAC OS X El Capitan v10.11.5
Xcode 8 beta
iTunes 12.4.1
iPhone 6+  iOS 10.0 beta

It is working fine for other iOS versions below 10.0 beta.

Need help.

**Comment by artygus** [comment]
ios 10.0 beta is not supported yet https://github.com/google/ios-webkit-debug-proxy/issues/145

**Comment by KrazySush** [comment]
@artygus Hi,
Any idea, by when the support will be available for iOS 10 beta?
