### ISSUE TITLE
Timeline and Profiling Not Working on iOS Simulator

### ISSUE THREAD

**Issue by AndrewHenderson** [google/ios-webkit-debug-proxy#146]
Breakpoints work, however profiles never load in both the Profiles tab and the Timeline.

![chrome_dev_tools](https://cloud.githubusercontent.com/assets/1031565/16161066/6d2ab048-3480-11e6-9c79-9410a2dcb7d8.gif)

**Comment by artygus** [comment]
it won't load b/c safari and chrome inspector protocols diverged
