### ISSUE TITLE
Console input ~>16KB causes websocket disconnect

### ISSUE THREAD

**Issue by rosesandhello** [google/ios-webkit-debug-proxy#147]
On entering ~>16KB into the console, IWDP invariably disconnects.

Attached is a (very large -- apologies) debug log of exactly the time of such an occurrence.

(and if someone could direct me on how to provide more useful logs, I'd appreciate it)

[console_crash_debug.txt](https://github.com/google/ios-webkit-debug-proxy/files/330536/console_crash_debug.txt)

This also appears to be the case in its sending messages, as I get websocket disconnects on attempting to load the Resources tab on resource heavy sites (disney.com being a good example).

**Comment by artygus** [comment]
hi @rosesandhello, what OS do you use and I'm wondering if you built utility from source?

**Comment by rosesandhello** [comment]
OSX 10.11 and Homebrew. I'll give a go to building it.

**Comment by artygus** [comment]
if it's homebrew try to reinstall it
    
    brew update
    brew upgrade ios-webkit-debug-proxy

**Comment by rosesandhello** [comment]
Already the latest version, I'm afraid.

**Comment by artygus** [comment]
That's really strange, sounds like very old issue, but I'll take a look. If I find the reason, I'll let you know. Are you using chrome bundled front-end? And just curious why do you use the utility instead of safari inspector? Chrome dev tools are way better but blink/webkit dev protocols diverged so much that chrome dev tools are barely working with ios

**Comment by rosesandhello** [comment]
I am using a relatively new front end, and I do see the communication failings (I am still considering contributing to the compat layer), but this really does more seem to be IWDP. I might give serious consideration to using the Safari utility.

**Comment by artygus** [comment]
should be fixed with https://github.com/google/ios-webkit-debug-proxy/pull/148
