### ISSUE TITLE
Proxy unable to handle multiple consecutive requests

### ISSUE THREAD

**Issue by snevesbarros** [google/ios-webkit-debug-proxy#15]
We are are making multiple requests and finding that the proxy isn't always able to handle them accordingly. We dont received a response and the web socket connection is closed. 

When running the proxy in debug mode we do see the response coming back from the device (webInspector protocol) however this is never returned by the proxy to us.

If you would like to see this in action please find a test example <a href="https://docs.google.com/file/d/0ByIdcWPvw1I3WlJvLXExQWlQT1E/edit?usp=sharing">here</a>:
1. Unpack the zip file
2. Run <b>sudo npm install ws</b> and <b>sudo npm install optimist</b> in the unpacked folder.
3. Attach an iOS device and open mobile safari
4. Start the proxt "ios_webkit_debug_proxy -c :27752-27758 -d"
5. Run the wdp_client.js test (multiple times).

The test contains 5 requests, which when run repeatedly sometimes get executed and sometimes the web socket is disconnected.

Any ideas why this is happening?

Regards,

Sergio

**Comment by mare1012** [comment]
Hallo @snevesbarros @zwri, i have a similiar issue. I'm using appium and ios-webkit-debug-proxy to test iOS 10.3.1 real device. i wrote a simple script with python. But sometimes it works sometimes it doesnt, if a run the same script for a couple times. If the script doesnt work. the error says webkit remote debugger socket disconnected. 

I also already tried to install IWDP via Terminal, but it doesnt change anything
> git clone https://github.com/google/ios-webkit-debug-proxy.git
> cd ios-webkit-debug-proxy
> ./autogen.sh
> ./configure
> make
> sudo make install

here is the log file:
https://gist.github.com/mare1012/5ac509d11442583fb7d1fc8e4264bcee
here is my script:
https://gist.github.com/mare1012/1f67e5c10507932d9823651405a56aa8
