### ISSUE TITLE
webinspector.c:50:25: error: implicit declaration of function ‘idevice_connection_get_fd’

### ISSUE THREAD

**Issue by bobjohnbob** [google/ios-webkit-debug-proxy#151]
I tried to follow the linux install instructions in your readme.  When I ran `make` I got the following error:

```
/libxml2 -I/usr/include/libxml2 -g -O2 -Wall -Werror -MT webinspector.lo -MD -MP -MF .deps/webinspector.Tpo -c webinspector.c  -fPIC -DPIC -o .libs/webinspector.o
webinspector.c: In function ‘idevice_connection_get_fd_wrapper’:
webinspector.c:50:25: error: implicit declaration of function ‘idevice_connection_get_fd’ [-Werror=implicit-function-declaration]
   idevice_error_t err = idevice_connection_get_fd(connection, &fd);
                         ^
cc1: all warnings being treated as errors
Makefile:565: recipe for target 'webinspector.lo' failed
make[2]: *** [webinspector.lo] Error 1
make[2]: Leaving directory '/home/jshaver/Projects/newVistas/ios-webkit-debug-proxy/src'
Makefile:401: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/jshaver/Projects/newVistas/ios-webkit-debug-proxy'
Makefile:333: recipe for target 'all' failed
make: *** [all] Error 2

```
I am running ubuntu 16.04.

Checking out commit f10c708f0a16ce4ede62516fd715f519a97f348a seems to have worked around the problem.  I figured this out by looking at the commit log:

```
commit 5a178c599caa3a7577bb18b9a3848d17ed17e3bf
Author: Alex Lau <al@saucelabs.com>
Date:   Fri May 13 11:39:16 2016 -0700

    Use libimobiledevice idevice_connection_get_fd

commit f10c708f0a16ce4ede62516fd715f519a97f348a
Author: Arty Gus <artygus@users.noreply.github.com>
Date:   Sat Mar 12 12:31:00 2016 +0300

    readme: troubleshooting for simulator #135

```
I'm not sure how to actually fix the issue, but I thought you might want to know there is one.  If you have any questions or I can provide any more information to help, please let me know.

**Comment by artygus** [comment]
version from master branch should be built with libimobildevice from HEAD https://github.com/google/ios-webkit-debug-proxy/issues/149

**Comment by itrmit** [comment]
Hi  artygus,
/usr/local/Cellar/libimobiledevice/1.2.0 is my current version
but still got error: implicit declaration of function 'idevice_connection_get_fd' is invalid in C99

can you help me?

**Comment by artygus** [comment]
@itrmit something definitely wrong, you should have `/usr/local/Cellar/libimobiledevice/HEAD/` folder, not `/usr/local/Cellar/libimobiledevice/1.2.0`

**Comment by artygus** [comment]
I think I'll rollback #141 until libimobiledevice 1.2.1 is out to workaround the issue
