### ISSUE TITLE
Unable to specify which simulator to connect to

### ISSUE THREAD

**Issue by MSLaguana** [google/ios-webkit-debug-proxy#152]
When running in a multi-user environment, two users may have different instances of the iOS simulator open at the same time. As far as I can tell there isn't a way to select the iOS simulator to connect to, `ios-webkit-debug-proxy` just picks one and not necessarily one owned by the current user.

Is there a way to work around this?

**Comment by artygus** [comment]
No, there's only one instance os simulator connected through localhost:27753. You would experience with Safari devtools, only one simulator would be listed in device list
