### ISSUE TITLE
CSS is read only and DOM APIs are not working from console

### ISSUE THREAD

**Issue by mohsen1** [google/ios-webkit-debug-proxy#153]
My setup:

```
brew install ios-webkit-debug-proxy                                            Tue Aug 16 10:32:31 2016
Warning: ios-webkit-debug-proxy-1.6 already installed
```

Physical iPhone with iOS 9.3.4

Chrome version  52.0.2743.

Devtools frontend: 

```
chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1
```

Issue: 

the CSS is read only 
![screen shot 2016-08-16 at 10 40 39 am](https://cloud.githubusercontent.com/assets/543633/17709435/e79045b8-639d-11e6-9b17-61324a9fe13c.png)

DOM APIs are not working:

```
document.body.innerHTML = '!'
// nothing happens!
```

**Comment by artygus** [comment]
The issue is related to diverged Chrome and Safari protocols, not going to be fixed. The purpose of the tools is to proxy requests to safari devtools through websocket protocol
