### ISSUE TITLE
UIWebViews no show

### ISSUE THREAD

**Issue by RhinoLu** [google/ios-webkit-debug-proxy#154]
Hi,

iOS Safari shows on localhost:9222 correctly,
but iOS Chrome or other UIWebView missing.

This tool still support UIWebView debug ?

Mac 10.11.6, iOS 9.3.4

Regards

**Comment by artygus** [comment]
Hi @RhinoLu there already was a similar question here #110, unfortunately it's not possible other UIWebViews because iOS doesn't expose them to WebInspector
