### ISSUE TITLE
Getting error when trying to compile code using ./autogen.sh

### ISSUE THREAD

**Issue by c0gupr2** [google/ios-webkit-debug-proxy#156]
Hi,

I am getting an error when trying to compile code using command ./autogen.sh.
Can somebody please provide a solution for this?

./configure: line 15991: syntax error near unexpected token `libusbmuxd,'
./configure: line 15991: `PKG_CHECK_MODULES(libusbmuxd, libusbmuxd >= $LIBUSBMUXD_VERSION)'

Thanks,
Rohit Gupta

**Comment by c0gupr2** [comment]
I am able to resolve above issue and now stuck with below problem

/Users/bachupa/Downloads/Xcode-beta.app/Contents/Developer/usr/bin/make  all-recursive
Making all in common
  CC       debug.lo
In file included from debug.c:36:
../src/idevice.h:30:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make[2]: *** [debug.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by artygus** [comment]
look's like OpenSSL headers were removed in the 10.11 SDK, you can try

    brew install openssl

**Comment by ivasylchenko** [comment]
@c0gupr2 
what was the fix for initial issue (libusbmuxd,)?
