### ISSUE TITLE
Chrome iOS remote debugging?

### ISSUE THREAD

**Issue by snevesbarros** [google/ios-webkit-debug-proxy#16]
It seems that the web views for the Chrome browser do not show up on the proxy.

Does the chrome browser on iOS support remote debugging and if so does it require the web inspector protocol or the webkit protocol? 

Would it be possible to make these web view(s) available to the proxy as well?

Thanks,

Sergio

**Comment by Josh-a-e** [comment]
Is anyone aware if anything has changed here?

**Comment by programmin1** [comment]
What's the point in inspecting Chrome if it uses the same rendering engine as Safari? In fact I don't think there is any other browser, like Firefox for iOS, because of Apple's absurd policies on that.

**Comment by Josh-a-e** [comment]
Right now I have an issue where stripe checkout appears just fine on iOS Safari, but doesn't show up at all in iOS Chrome, so I really just want to have a look at the console to see what's going on.

In this instance I think chrome has different policies around the creation of new tabs.
