### ISSUE TITLE
Could not connect to lockdownd. Exiting Permission denied

### ISSUE THREAD

**Issue by Can-too** [google/ios-webkit-debug-proxy#160]
I have installed the XCode upgrade to my iOS 7.3.1, to run my existing IPhone Appium Tests using iOS 10. The some of my real mobile devices have also been upgraded but Since the upgrade to XCode my browser app tests all devices are failing. The ios-webkit-debug proxy has been having the same issue: 

Could not connect to lockdownd. Exiting Permission denied.
Unable to attach <udid> inspector.

I have continually booted/rebooted the mobile devices and the iMac Mini (El Captain). I have even tried uninstalling/reinstalling the ios_webkit_debug_proxy, but nothing has helped...

It seems like the upgrade of the XCode 7.3.1 to include iOS 10 appears to be the issue because using the ios_webkit_debug_proxy with the iOS 9.3.5 devices, have also stopped working, failing with the same reason.   

I have since run SafariLauncher using XCode on both iOS 9.3.5 and 10.0.1. using idevice -l all my devices are listed, using idevicepair pair was a SUCCESS, BUT using idevicepair validate produces:

ERROR: Device <udid> is not paired with this host

Which seems to be a contradiction.... I have also tried using Instruments on the MAC but when I choose a device having 10.0.1 installed the recording button is not enabled and has the comment: "This instrument's supported recording mode are none". This may be of no interest - just something I noticed...

Help....

**Comment by artygus** [comment]
@Can-too I have Beta version of XCode installed but it works quite fine, you could try installing libimobildevice from master

    brew uninstall --force libimobiledevice ios-webkit-debug-proxy
    brew install --HEAD libimobiledevice ios-webkit-debug-proxy

**Comment by Can-too** [comment]
Many thanks for the response, unfortunately the install didn't work with the --HEAD parameter. It did work without it.... (Message: No head for the ios-webkit-debug-proxy.) Unfortunately this this has not helped and I'm getting the same message....

**Comment by rjmadhu** [comment]
@artygus  
No head is defined for  ios-webkit-debug-proxy
brew install --HEAD libimobiledevice 
brew install  ios-webkit-debug-proxy

**Comment by Can-too** [comment]
okay that worked, with using the disk utility (sudo diskutil repairPermissions /). seems to have rectified the previous problems but now I cannot connect to the device and have the following message:

Invalid message _rpc_reportConnectedDriverList: <dict>
      <key>WIRDriverDictionaryKey</key>
      <dict>
      </dict>

Any suggestions?

**Comment by artygus** [comment]
@rjmadhu thanks, it's probably because I rolled out a new version of  ios-webkit-debug-proxy  to brew recently
@Can-too `brew update && brew upgrade ios-webkit-debug-proxy`

**Comment by Can-too** [comment]
Okay... So should I download again? Or when should I download?

**Comment by artygus** [comment]
@Can-too I pushed a new versions of utility a few days ago to brew

**Comment by Can-too** [comment]
artygus, is the command "brew update && brew upgrade ios-webkit-debug-proxy" to be used just as you have entered it? because when using it I get the message Error: /usr/local must be writeable!

Using just "brew update" I get the same message...

**Comment by Can-too** [comment]
Okay got it, many thanks all ! 
Needed to run the following command:
`sudo chown -R $(whoami):admin /usr/local`
**then:**
- `brew update`
- `brew upgrade ios-webkit-debug-proxy`

**Comment by terminal-illness** [comment]
Hi there,

I had the same issue:

Could not connect to lockdownd. Exiting Permission denied.
Unable to attach inspector

So I ran the following:

chmod +x /var/db/lockdown

Worked for me :)

**Comment by mashek347** [comment]
GNWRICA2080432:~ 502000533$ ios_webkit_debug_proxy -c a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e927753 
Could not connect to lockdownd. Exiting.: Permission denied
Unable to attach a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9 inspector

is not working for 
Please help?

**Comment by skumar1122** [comment]
@mashek347 
Try like this -
ios_webkit_debug_proxy -c a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e:27753 -d

**Comment by terminal-illness** [comment]
if you run sudo ios_webkit_debug_proxy -c a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e:27753 -d

does that start the debug proxy? If so then changing the permission on lockdown should solve your problem

**Comment by mashek347** [comment]
Still, I am facing issue. 
please refer below the error code:

Launching Appium with command: '/Applications/Appium 3.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --address "127.0.0.1" --debug-log-spacing --platform-version "10.0.2" --platform-name "iOS" --safari --browser-name "Safari" --show-ios-log --default-device --native-instruments-lib

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:

[Appium]   address: '127.0.0.1'
[Appium]   safari: true
[Appium]   defaultDevice: true

[Appium]   debugLogSpacing: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.0.2'
[Appium]   browserName: 'Safari'
[Appium]   nativeInstrumentsLib: true
[Appium]   showIOSLog: true
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"10.0.2"}'
[Appium]   --browser-name => --default-capabilities '{"browserName":"Safari"}'

[Appium]   --native-instruments-lib => --default-capabilities '{"nativeInstrumentsLib":true}'
[Appium]   --show-ios-log => --default-capabilities '{"showIOSLog":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:

[Appium]   platformName: 'iOS'

[Appium]   platformVersion: '10.0.2'
[Appium]   browserName: 'Safari'
[Appium]   nativeInstrumentsLib: true
[Appium]   showIOSLog: true

[Appium] Appium REST http interface listener started on 127.0.0.1:4723

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"io.appium.SafariLauncher","safariIgnoreFraudWarning":true,"platformVersion":"10.0.2","safariAllowPopups":false,"browserName":"safari","platformName":"iOS","udid":"a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9","deviceName":"iPhone 6"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"io.appium.SafariLa...

[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   app: 'io.appium.SafariLauncher'
[Appium]   safariIgnoreFraudWarning: true
[Appium]   platformVersion: '10.0.2'
[Appium]   safariAllowPopups: false
[Appium]   browserName: 'safari'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9'
[Appium]   deviceName: 'iPhone 6'
[Appium]   nativeInstrumentsLib: true
[Appium]   showIOSLog: true

[BaseDriver] Session created with session id: 3d3b367e-945a-46b8-9cf2-3f950d600d25

[debug] [iOS] Not auto-detecting udid.

[debug] [iOS] Creating iDevice object with udid a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9

[debug] [iOS] Checking for presence of SafariLauncher at '/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app'

[debug] [iOS] SafariLauncher exists

[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /var/folders/z3/tkbh3cns4fd4fyd6xsdgk1bh68_4ff/T/instruments_sock

[debug] [iOS] No language specified. Using default strings

[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory

[iOS] Could not file localizable strings file 'Localizable.strings'!

[debug] [iOS] Creating instruments

[debug] [UIAuto] Preparing bootstrap code

[debug] [UIAuto] Dynamic bootstrap dir: /Users/502000533/Library/Application Support/appium/bootstrap

[debug] [UIAuto] Dynamic env: {"nodePath":"/Applications/Appium 3.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/z3/tkbh3cns4fd4fyd6xsdgk1bh68_4ff/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

[debug] [UIAuto] Dynamic bootstrap path: /Users/502000533/Library/Application Support/appium/bootstrap/bootstrap-7bf8a16bd619352a.js

[debug] [UIAuto] Reusing dynamic bootstrap: /Users/502000533/Library/Application Support/appium/bootstrap/bootstrap-7bf8a16bd619352a.js

[debug] [iOS] Running ios real device reset flow

[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog

[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'

[debug] [iOS] App is not installed. Will try to install.

[MJSONWP] Encountered internal error running command: Error: Installing /Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app failed
    at /Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)

[HTTP] <-- POST /wd/hub/session 500 2674 ms - 291 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 35 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 33 ms - 83 
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 3 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"10.0.2","newCommandTimeout":"10000","automationName":"Appium"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","pla...

[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.0.2'
[Appium]   newCommandTimeout: '10000'

[Appium]   automationName: 'Appium'
[Appium]   browserName: 'Safari'
[Appium]   nativeInstrumentsLib: true
[Appium]   showIOSLog: true
[BaseDriver] Capability 'newCommandTimeout' changed from string ('10000') to integer (10000). This may cause unexpected behavior

[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): deviceName can't be blank.
    at IosDriver.validateDesiredCaps (lib/basedriver/driver.js:120:25)
    at IosDriver.validateDesiredCaps (lib/driver.js:40:16)
    at IosDriver.callee$0$0$ (lib/basedriver/commands/session.js:14:8)
    at tryCatch (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at IosDriver.callee$0$0 [as createSession] (lib/basedriver/commands/session.js:8:46)
    at IosDriver.createSession$ (lib/driver.js:40:16)
    at tryCatch (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at IosDriver.createSession (lib/driver.js:110:19)
    at AppiumDriver.createSession$ (lib/appium.js:121:43)
    at tryCatch (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21
[HTTP] <-- POST /wd/hub/session 500 91 ms - 198 

)
    at invoke (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at AsyncIterator.enqueue (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
 { [SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): deviceName can't be blank.] jsonwpCode: 33 }

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 17 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 14 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 17 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 31 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 18 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 15 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 16 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 17 ms - 83 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"io.appium.SafariLauncher","safariIgnoreFraudWarning":true,"platformVersion":"10.0.2","safariAllowPopups":false,"browserName":"safari","platformName":"iOS","udid":"a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9","deviceName":"iPhone 6"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"io.appium.SafariLa...
[Appium] Creating new IosDriver session

[Appium] Capabilities:
[Appium]   app: 'io.appium.SafariLauncher'
[Appium]   safariIgnoreFraudWarning: true
[Appium]   platformVersion: '10.0.2'
[Appium]   safariAllowPopups: false
[Appium]   browserName: 'safari'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9'
[Appium]   deviceName: 'iPhone 6'
[Appium]   nativeInstrumentsLib: true
[Appium]   showIOSLog: true
[BaseDriver] Session created with session id: 1ebe0fbf-3b22-4bd1-bcc8-c9d2afc53324
[debug] [iOS] Not auto-detecting udid.

[debug] [iOS] Creating iDevice object with udid a132919a4b4c2c393ea15f7860fe8ae1e3d6f1e9

[debug] [iOS] Checking for presence of SafariLauncher at '/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app'

[debug] [iOS] SafariLauncher exists
[debug] [iOS] Removing any remaining instruments sockets

[debug] [iOS] Cleaned up instruments socket /var/folders/z3/tkbh3cns4fd4fyd6xsdgk1bh68_4ff/T/instruments_sock
[debug] [iOS] No language specified. Using default strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Could not file localizable strings file 'Localizable.strings'!
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/502000533/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/Applications/Appium 3.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/z3/tkbh3cns4fd4fyd6xsdgk1bh68_4ff/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

[debug] [UIAuto] Dynamic bootstrap path: /Users/502000533/Library/Application Support/appium/bootstrap/bootstrap-7bf8a16bd619352a.js

[debug] [UIAuto] Reusing dynamic bootstrap: /Users/502000533/Library/Application Support/appium/bootstrap/bootstrap-7bf8a16bd619352a.js

[debug] [iOS] Running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'

[debug] [iOS] App is not installed. Will try to install.

[MJSONWP] Encountered internal error running command: Error: Installing /Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app failed
    at /Applications/Appium 3.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)

[HTTP] <-- POST /wd/hub/session 500 2061 ms - 291 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 16 ms - 83

**Comment by chethanshetty09** [comment]
Below steps worked for me :)

Make sure the below Capabilities are setup properly
capabilities.setCapability("autoWebView", true);
capabilities.setCapability("startIWDP", true);
If the ios-webkit-debug-proxy is not installed, install it with below command:
brew install --HEAD libimobiledevice ios-webkit-debug-proxy

Try to run this command from terminal and see if the connected device has the Web kit proxy running
sudo ios_webkit_debug_proxy -c <Device UDID>:9221 -d(replace the above device UDID)

If you see some errors, like
Could not connect to lockdownd. Exiting Permission denied
Then you need to give permission:
sudo chmod +x /var/db/lockdown

Now try to run the command:

sudo ios_webkit_debug_proxy -c <Device UDID>:9221 -d
(replace the above device UDID)
If still you face the problem then follow below steps: try to uninstall the ios-webkit-debug-proxy and install again

brew uninstall --force libimobiledevice ios-webkit-debug-proxy
brew install --HEAD libimobiledevice ios-webkit-debug-proxy
Now try to run the command:

sudo ios_webkit_debug_proxy -c <Device UDID>:9221 -d
(replace the above device UDID)

**Comment by skwid138** [comment]
After using brew to install on OSX 10.13.5 and then 
ios_webkit_debug_proxy -f chrome-devtools://devtools/bundled/inspector.html
I received the following errors
Could not connect to lockdownd. Exiting.: Permission denied
Unable to attach 8efdc365951be7e7bc39b0e1e9dd78844fc1a7ac inspector

Following the advice of terminal-illness above I ran sudo chmod 755 /var/db/lockdown and then reconnected the iPad and it worked great.

**Comment by artygus** [comment]
hi @skwid138, did you install libimobiledevice with --HEAD flag? what does `ios_webkit_debug_proxy -V` show?
