### ISSUE TITLE
Could not connect to lockdownd. Exiting.: Broken pipe

### ISSUE THREAD

**Issue by yaphatak** [google/ios-webkit-debug-proxy#161]
I am on 10.11.6 and ios 10.0.1, iTune 12.5.1.21

this is how `brew info ios-webkit-debug-proxy` looks like 

`ios-webkit-debug-proxy: stable 1.7 (bottled)
DevTools proxy for iOS devices
https://github.com/google/ios-webkit-debug-proxy
/usr/local/Cellar/ios-webkit-debug-proxy/1.7 (19 files, 357.9K) *
  Poured from bottle on 2016-09-20 at 14:08:52
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ios-webkit-debug-proxy.rb
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✔, pkg-config ✘
Required: libplist ✔, usbmuxd ✔, libimobiledevice ✔`

**Comment by artygus** [comment]
@yaphatak I think it's related to libimobiledevice issues, please try `brew upgrade libimobiledevice --HEAD`

**Comment by yaphatak** [comment]
that did a trick. Thanks

**Comment by frami** [comment]
The command 'brew upgrade libimobiledevice --HEAD' solved the problem for me. I use ios10.

**Comment by ayrka39** [comment]
thanks, it is THE solution for me.

**Comment by pavanbachu0604** [comment]
@ayrka39 : Even I am facing the same issue ..whats the solution ? iOS 10 DEVICE

**Comment by artygus** [comment]
@pavanbachu0604 solution is to rebuild the tools with libimobiledevice from master

**Comment by jglifonea** [comment]
thanks for this! this works!

**Comment by SteveArias** [comment]
Thank you!!! You saved me from hours of frustration.
