### ISSUE TITLE
iOS10 - can't connect to WKWebView anymore

### ISSUE THREAD

**Issue by fpn** [google/ios-webkit-debug-proxy#163]
Was debugging WKWebView fine on my iphone before upgrading today to iOS10.
Ran into the TLS issue, and had to upgrade to:
- libimobiledevice (master/HEAD)
- libssl.so.1.1 (master/HEAD)
- (libimobiledevice_idevice_connection/HEAD)

ios-webkit-debug-proxy can connect to safari works, but not to the WKWebView.
Using an mac laptop and safari works also with iOS 10 and WKWebView.

```
fpn@alpha:~$ ios_webkit_debug_proxy 
Listing devices on :9221
Connected :9222 to Theo’s iPhone (***)
Unknown app_id PID:286
Invalid message _rpc_applicationSentListing: <dict>
    <key>WIRApplicationIdentifierKey</key>
    <string>PID:286</string>
    <key>WIRListingKey</key>
    <dict>
    </dict>
</dict>
Disconnected :9222 from Theo’s iPhone (***)
```

**Comment by artygus** [comment]
hi @fpn, I didn't get it were you able to resolve the issue? The upgrades you listed are necessary indeed, because libimobiledevice is stuck on 1.2.0, not sure when the new version is going to be released

**Comment by fpn** [comment]
I wasn't able to debug WKWebView even with the upgrades listed above.

**Comment by artygus** [comment]
hi @fpn, do you still see the issue after #169 was merged in?
