### ISSUE TITLE
IOS 10 Can't hit a breakpoint

### ISSUE THREAD

**Issue by crich1979** [google/ios-webkit-debug-proxy#164]
As per the title we have several developers that are unable to hit breakpoints while using ios-webkit-debug-proxy connected to an IOS 10 device.  

Following has been done:
brew update 
brew uninstall libimobiledevice
brew install libimobiledevice --HEAD
brew uninstall ios_webkit_debug-proxy
brew install ios_webkit_debug-proxy

The connection to the device is established fine and source files are visible.  We are able to set a breakpoint but it is never hit.  Adding a "debugger;" line to the code also never causes it to break.  Debugging directly in safari works fine the same breakpoint is hit.  We have tested with our application (ionic) and with a simple hosted webpage.  We can continue to debug fine on ios 9.x devices.

Any help or advice would be great.  

Many thanks

Chris

**Comment by artygus** [comment]
Hi @crich1979 unfortunately it's because diverged Chrome and Safari protocols, an the issue is not going to be fixed. One way around is to use older devtools. The purpose of the tools is to proxy requests to safari devtools through websocket protocol.

**Comment by crich1979** [comment]
OK thanks.  That really sucks but I understand.  I used it for VS code debugging of our app but we have to support ios 10 so i'm back to the the annoying safari debugger I guess.  I'll ask if the vscode-cordova guys have any plans to support it another way.

**Comment by auchenberg** [comment]
I spent a little time sniffing the traffic between Chrome DevTools and Safari Web Inspector. 

Let me clarify: The debugging API between Webkit and Chrome for core debugging scenarios hasn't diverged, but remains stable. This is documented in the compatibility tables: http://compatibility.remotedebug.org/Debugger


**The debugging:**

I started the `ios_webkit_debug_proxy` and connected my iPhone 7 Plus running iOS 10, where I connected the Chrome DevTools and Safari Web Inspector front-ends to inspect the WebSocket frames

The example code: http://output.jsbin.com/guyabaloye

**Chrome DevTools:**
![image](https://cloud.githubusercontent.com/assets/173559/19008400/f78f80fa-871f-11e6-91a6-01f13f52b5a4.png)

![image](https://cloud.githubusercontent.com/assets/173559/19008408/fb5f6db2-871f-11e6-90ea-9f1e92699cb5.png)

**Safari Web Inspector:**
![image](https://cloud.githubusercontent.com/assets/173559/19008414/0417bc3e-8720-11e6-8e7f-98186e23a418.png)

![image](https://cloud.githubusercontent.com/assets/173559/19008422/08c0142a-8720-11e6-9254-20f106c07ba8.png)

Looking at the traffic, it's clear that Safari Web Inspector makes the Debugger.setBreakpointsActive API request, and Chrome DevTools doesn't. Looking at the documentation for the API, http://compatibility.remotedebug.org/Debugger/Safari%20iOS%2010.0/commands/setBreakpointsActive, it seems pretty reasonable that this API should be called to enable the "debugger;" breakpoint in the debugger back-end.

So to validate my assumption I wrote a little script to send API commands to the IOS device:
https://gist.github.com/auchenberg/b3a07edc242c4c91a31ddaa2e76d832d#file-gistfile1-js-L35

And bam, with the `Debugger.setBreakpointsActive API` request to the WebKit back-end, the breakpoint is hit

🎉👏🍻

![image](https://cloud.githubusercontent.com/assets/173559/19008431/10b3906c-8720-11e6-9376-857d395ee9e3.png)

**Conclusion**

Make the `Debugger.setBreakpointsActive` API request from your debugger, and debugger-statements should break again on iOS/Webkit.

The WebKit API hasn't changed, but the front-ends (Chrome DevTools and Safari Web Inspector) has different assumptions on which API calls to make.
