### ISSUE TITLE
(Linux) GnuTLS error: Error in the pull function. Could not connect to lockdownd. Exiting.: Broken pipe

### ISSUE THREAD

**Issue by benwiley4000** [google/ios-webkit-debug-proxy#166]
Running Ubuntu 16.04. `idevice_id -l` returns `ca77ad6...` shown below, I've got a page open in a browser tab on the iPhone, and I've made sure to "trust" the computer via the phone.
```
$ ios_webkit_debug_proxy 
Listing devices on :9221
GnuTLS error: Error in the pull function.
Could not connect to lockdownd. Exiting.: Broken pipe
Unable to attach ca77ad6e59a6433a51995f0284c00786d24c2971 inspector
```

`localhost:9221` does open a web page that read "iOS Devices:," but nothing else.

**Comment by artygus** [comment]
@benwiley4000 I believe it's something related to libimobiledevice, please try with version from master

**Comment by artygus** [comment]
maybe https://github.com/libimobiledevice/libimobiledevice/issues/382 https://github.com/libimobiledevice/libimobiledevice/issues/365

**Comment by benwiley4000** [comment]
@artygus thanks for the tip. I've run the following:

`sudo apt-get remove libimobiledevice-dev && sudo apt-get autoremove`
`git clone https://github.com/libimobiledevice/libimobiledevice.git && cd libimobiledevice`
```
./autogen.sh
make
sudo make install
```
```
cd ../ios-webkit-debug-proxy
./autogen.sh
make
```
And I ended with the following error during `make`:
```
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include   -I/usr/local/include -I/usr/include/libxml2 -I/usr/include/libxml2 -g -O2 -Wall -Werror -MT webinspector.lo -MD -MP -MF .deps/webinspector.Tpo -c -o webinspector.lo webinspector.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -I/usr/local/include -I/usr/include/libxml2 -I/usr/include/libxml2 -g -O2 -Wall -Werror -MT webinspector.lo -MD -MP -MF .deps/webinspector.Tpo -c webinspector.c  -fPIC -DPIC -o .libs/webinspector.o
webinspector.c:57:11: error: conflicting types for ‘idevice_connection_get_fd’
 wi_status idevice_connection_get_fd(idevice_connection_t connection,
           ^
In file included from /usr/local/include/libimobiledevice/installation_proxy.h:33:0,
                 from webinspector.c:18:
/usr/local/include/libimobiledevice/libimobiledevice.h:250:17: note: previous declaration of ‘idevice_connection_get_fd’ was here
 idevice_error_t idevice_connection_get_fd(idevice_connection_t connection, int 
                 ^
```
I'm having trouble debugging this and would appreciate help. Thanks!

**Comment by artygus** [comment]
@benwiley4000 please try https://github.com/google/ios-webkit-debug-proxy/tree/libimobiledevice_idevice_connection branch

**Comment by benwiley4000** [comment]
@artygus thanks. I've now been able to build (hooray) but I'm getting this error when I run `ios_webkit_debug_proxy`:
```
symbol lookup error: ios_webkit_debug_proxy: undefined symbol: idevice_connection_get_fd
```

**Comment by artygus** [comment]
did you run `make install`?

**Comment by benwiley4000** [comment]
Yes - just ran a second time to be sure, and same error.

**Comment by artygus** [comment]
looks like you have wrong shared lib,
did you install ios-webkit-debug-proxy from package the first time?

**Comment by benwiley4000** [comment]
I've installed from the GitHub master branch, and now the branch you
recommended (I did nothing to purge ios-webkit-debug-proxy before re-
autogen/make/install).

**Comment by artygus** [comment]
you could try to run it from build dir, e.g. `./src/ios_webkit_debug_proxy`

**Comment by benwiley4000** [comment]
Ok - that returns the same error.

**Comment by artygus** [comment]
this is weird, try to run

    make uninstall
    make clean
    ./authogen.sh
    make
    ./src/ios_webkit_debug_proxy

**Comment by benwiley4000** [comment]
Unfortunately it's the same! Perhaps this is irrelevant, but of all the packages I installed with apt-get prior to installing ios-webkit-debug-proxy, libimobiledevice is the only one I have changed/modified. Not sure if any others need to be re-built for whatever reason.

**Comment by artygus** [comment]
ah, I see now, it could be `sudo make install`, to work properly you need to run `sudo make uninstall`

**Comment by artygus** [comment]
ah shit, I guess you need to run `sudo ldconfig`

**Comment by benwiley4000** [comment]
@artygus I used sudo! However I just did what you asked (`ldconfig`) and magic - works! Thank you!

**Comment by juliogc** [comment]
Hi, guys

Sorry to reopen this topic, but I'm with the same problem and all those workarounds are failing to me.

```
$ ios_webkit_debug_proxy
Listing devices on :9221
GnuTLS error: Error in the pull function.
Could not connect to lockdownd. Exiting.: Broken pipe
Unable to attach e0a75957378fceb4a4275f996168ac68179b8862 inspector
```

Here some extra infos

**OS Version**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Device recognized (hash)**
```
$ idevice_id -l
e0a75957378fceb4a4275f996168ac68179b8862
```

**Device recognized (debug)**
```
$ idevice_id -d $(idevice_id -l | head -1)
Julio's iPhone
```

**usbmuxd daemon running**
```
$ ps aux | grep -i usbmuxd
usbmux    6458  0.2  0.0 322832  7820 ?        Ssl  19:19   0:00 /usr/sbin/usbmuxd --user usbmux --systemd
```

Here are all the ways that I tried to install:
1) The default install instructions on [ios-webkit-debug-proxy](https://github.com/google/ios-webkit-debug-proxy#installation)
2) The [initial test](#issuecomment-251467811) sugested by @benwiley4000 
3) This [second step](#issuecomment-251469064) sugested by @artygus 
4) And [another one step](#issuecomment-251476599) sugested by @artygus 
5) Plus [this one](#issuecomment-251477916) also by @artygus 
6) Also tried `sudo ldconfig`
7) Extra: Also followed [this tutorial](http://www.davidemontersino.com/development-en/web-development/2014/09/how-to-use-ipads-web-inspector-on-ubuntu/) to install as non-global bin

All this methods fail and the result is always the same as showed on the top.
I really can not understand why this is failing.

Could you please help me with this issue?

**Comment by artygus** [comment]
hi @juliogc can you confirm you're using libimobiledevice from master branch?

**Comment by juliogc** [comment]
Hi @artygus!

Yes, first I tried by cloning from the [github repository](https://github.com/libimobiledevice/libimobiledevice) and I have downloaded it via [libimobiledevice website](http://www.libimobiledevice.org/downloads/libimobiledevice-1.2.0.tar.bz2) as tar.bz2 too.

**Comment by ianmorti** [comment]
@artygus @juliogc I'm also seeing the `GnuTLS error` on 16.04.  tried both branch and master

**Comment by artygus** [comment]
@juliogc I can't see why author of the [tutotrial](http://www.davidemontersino.com/development-en/web-development/2014/09/how-to-use-ipads-web-inspector-on-ubuntu/) suggests installing libimobiledevice-dev and then make a build from sources (to skip building usbmuxd?).

The safest way is to build libimobiledevice (usbmuxd, libplist and libimobiledevice) from sources, the software quite advanced since previous release versions, but maintainers are not marking a new version for release just yet, and then rebuild ios-webkit-debug-proxy.

I don't think the issue is somehow related to ios-webkit-debug-proxy as it makes all the calls through libimobiledevice. There were a few looking alike issues related to messed up environments.

**Comment by juliogc** [comment]
@artygus I have to be honest that I'm almost a dummy user at this point and really don't understand the reason that the author recommend this "custom" installation.

But now I fixed the problem installing some extra dependencies that I found in [this post](http://askubuntu.com/questions/598940/libimobiledevice-1-2-ios-8-support-for-ubuntu-14-04-trusty/605198) from askubuntu. I'll leave bellow all the dependencies installed and all steps that took me at this point:

First I separated the packages in a directory to avoid extra problems
```
$ mkdir -p ~/projects/ios-debug
$ cd ~/projects/ios-debug
```

Then installed a bunch of dependencies as listed in askubuntu post mentioned above.
Obs: Please tell me if there are some useless/unnecessary deps installed
Obs2: I know there are some deps listed bellow that are already installed in OS, but I was desperate :joy:
Obs3: I know that I could install all in one command, just put in this way to make easier to read
```
$ sudo apt install -y libusbmuxd-dev
$ sudo apt install -y libplist-dev
$ sudo apt install -y libplist++-dev
$ sudo apt install -y libgnutls-dev
$ sudo apt install -y libssl-dev
$ sudo apt install -y usbmuxd
$ sudo apt install -y make
$ sudo apt install -y automake
$ sudo apt install -y autoconf
$ sudo apt install -y libtool
$ sudo apt install -y pkg-config
$ sudo apt install -y gcc
$ sudo apt install -y libusb-dev
$ sudo apt install -y libusb-1.0-0-dev
$ sudo apt install -y libimobiledevice-dev
```

After this, I installed the [libimobiledevice](https://github.com/libimobiledevice/libimobiledevice) via github:
```
$ git clone https://github.com/libimobiledevice/libimobiledevice.git
$ cd libimobiledevice
$ ./autogen.sh
$ make
$ sudo make install
$ cd ../ # Back to the ~/projects/ios-debug dir
```

After I tried to install [ios-webkit-debug-proxy](https://github.com/google/ios-webkit-debug-proxy) from master branch and get the same error from [here](#issuecomment-251467811):
```
$ git clone https://github.com/google/ios-webkit-debug-proxy.git
$ cd ios-webkit-debug-proxy
$ ./autogen.sh
$ make 
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include   -I/usr/local/include -I/usr/include/libxml2 -I/usr/include/libxml2 -g -O2 -Wall -Werror -MT webinspector.lo -MD -MP -MF .deps/webinspector.Tpo -c -o webinspector.lo webinspector.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -I/usr/local/include -I/usr/include/libxml2 -I/usr/include/libxml2 -g -O2 -Wall -Werror -MT webinspector.lo -MD -MP -MF .deps/webinspector.Tpo -c webinspector.c  -fPIC -DPIC -o .libs/webinspector.o
webinspector.c:57:11: error: conflicting types for ‘idevice_connection_get_fd’
 wi_status idevice_connection_get_fd(idevice_connection_t connection,
           ^
In file included from /usr/local/include/libimobiledevice/installation_proxy.h:33:0,
                 from webinspector.c:18:
/usr/local/include/libimobiledevice/libimobiledevice.h:250:17: note: previous declaration of ‘idevice_connection_get_fd’ was here
 idevice_error_t idevice_connection_get_fd(idevice_connection_t connection, int 
                 ^
```

So I moved to branch `libimobiledevice_idevice_connection` and now get success on running de debug proxy!
```
$ git checkout libimobiledevice_idevice_connection
$ ./autogen.sh
$ make
$ sudo make install

$ ios-webkit-debug-proxy
Listening devices on :9221
Connected :9222 to Julio's iPhone.......
```

I hope this could help and thank you so much for your help @artygus !

**Comment by ianmorty** [comment]
@artygus @juliogc yep - got mine working too.  rebuilding `libimobiledevice` locally and using `libimobiledevice_idevice_connection` branch seemed to do the trick 👍

**Comment by ios122** [comment]
update libimobiledevice and rebuild ios-webkit-debug-proxy,and Then:

```
sudo chmod -R 777 /var/lib/lockdown/ 
```

**Comment by evenfrost** [comment]
Can confirm changing permissions as @ios122 suggested helped me along with re-plugging the device.

**Comment by adnan-wahab** [comment]
I am getting this error, and the branch libimobiledevice_idevice_connection doesn't seem to exist anymore

**Comment by artygus** [comment]
hi @adnan-wahab changes from this branch were merged into master, please check that you're using latest libimobilidevice (1.2.1), if it doesn't help you could try building libimobiledevice with gnutls instead of openssl

    sudo apt install libgnutls-dev libgcrypt-dev
    cd <libimobiledevice>
    ./configure --without-cython --disable-openssl
