### ISSUE TITLE
(update: CSS3 animation issue) Inspector unbearably slow/sluggish, freezes

### ISSUE THREAD

**Issue by benwiley4000** [google/ios-webkit-debug-proxy#167]
UPDATE: Turns out this is an issue with inspecting elements that have CSS3 animations.

Running on Ubuntu 16.04.

I'm happy to have this working, but it's not very useful to me currently. I'm trying to open up the DOM tree to inspect nested elements. I'm able to get the first couple descendants which have no siblings (after several-second delays), but once I open my main content div the inspector freezes and the browser tab stops responding to changes in the currently-hovered element.

The last element I selected is displaying the down triangle but no child content.

Nothing displays in the JavaScript console or in the shell running `ios_webkit_debug_proxy`, so I'm not sure what I could do to improve performance.

ETA:
iPhone running iOS 9.3.1
libimobiledevice_idevice_connection branch of ios-webkit-debug-proxy
libimobiledevice from github, updated Tue Oct 4

**Comment by benwiley4000** [comment]
I should update and note that other web pages I've visited don't have this same problem and it appears to be at least somewhat unique to the page I'm working on. However I'm not sure what would cause this behavior.

**Comment by benwiley4000** [comment]
Ok after some further testing I've realized the freezing problem is unique to elements with CCS3 animations. Commenting out the `animation-name` property in my CSS fixes the issue. Have any similar issues been reported?

Further I think the slowness I was experiencing earlier has gone away for whatever reason; it may have been a problem with my local network.

**Comment by artygus** [comment]
a note about devtools has been added to [readme](https://github.com/google/ios-webkit-debug-proxy/blob/master/README.md#devtools-note)
