### ISSUE TITLE
could not connect to lockdownd. Exiting.: Permission denied

### ISSUE THREAD

**Issue by nethi216** [google/ios-webkit-debug-proxy#168]
Hi All,

i was able to execute my appium tests on IOS mobile successfully a few weeks ago, but i didn't run any tests for about few weeks and resumed the execution today, but i'm seeing the following issue, Can you please help?

IOS Mobile - 6 Plus
Version - 9.3
Xcode version - 7.3
MAC OS - EI Captain 10.11

**Issue**
could not connect to lockdownd. Exiting.: Permission denied
ss.remove_server_fd(4)
Unable to attach UDID inspector
******

**Comment by imurchie** [comment]
Try running `sudo chmod 777 /var/db/lockdown` to set the permissions.

**Comment by pmeenan** [comment]
I've seen recently that the lockdown permissions keep getting reset even after changing them (not sure the interval - probably on the order of close to a day last time it happened).  You might need to make the permissions change part of the prep that gets run before running a test.

**Comment by imurchie** [comment]
Making sure you have the latest `libimobiledevice` helps as well.

```
brew install libimobiledevice@HEAD
```

**Comment by artygus** [comment]
duplicate #160

**Comment by nethi216** [comment]
i did above stated things, but no luck, Can you please help me on how to changed lockdown permissions?

**Comment by artygus** [comment]
hi @nethi216 sorry, read it too late. I see you made it work 👍

**Comment by chethanshetty09** [comment]
Below steps worked for me :)

1. Make sure the below Capabilities are setup properly 
```
capabilities.setCapability("autoWebView", true);
capabilities.setCapability("startIWDP", true);
```

2. If the ios-webkit-debug-proxy is not installed, install it with below command: 
`brew install --HEAD libimobiledevice ios-webkit-debug-proxy`

3. Try to run this command from terminal and see if the connected device has the Web kit proxy running
`sudo ios_webkit_debug_proxy -c <Device UDID>:9221 -d
`(replace the above device UDID)

If you see some errors, like
Could not connect to lockdownd. Exiting Permission denied
 Then you need to give permission:
`sudo chmod +x /var/db/lockdown`

Now try to run the command:
```
sudo ios_webkit_debug_proxy -c <Device UDID>:9221 -d
(replace the above device UDID)
```

If still you face the problem then follow below steps: try to uninstall the ios-webkit-debug-proxy and install again
```
brew uninstall --force libimobiledevice ios-webkit-debug-proxy
brew install --HEAD libimobiledevice ios-webkit-debug-proxy
```

Now try to run the command:
```
sudo ios_webkit_debug_proxy -c <Device UDID>:9221 -d
(replace the above device UDID)
```

**Comment by gipsykeys** [comment]
> If still you face the problem then follow below steps: try to uninstall the ios-webkit-debug-proxy and install again
>
```
 brew uninstall --force libimobiledevice ios-webkit-debug-proxy
 brew install --HEAD libimobiledevice ios-webkit-debug-proxy
```
>
> Now try to run the command:

>
```
sudo ios_webkit_debug_proxy -c <Device UDID>:9221 -d
```
>(replace the above device UDID)


It took me 5 hours of googling solutions to that didn't work for me, until I reached this one. Thank you @chethanshetty09 !!

By the way, the easiest way to get your phone's UDID is from iTunes. You can copy it from there

**Comment by manju43akil** [comment]
Hi,
I'm still getting below error even after running these commands, Could you please help me ?
MacBook-Pro-2:lockdown $ sudo ios_webkit_debug_proxy -c <UDID>:9221 -d
Password:
ss.add_fd(3)
ss.recv fd=3 len=294
ss.recv fd=3 len=686
ss.add_server_fd(4)
Could not connect to lockdownd, error code -3. Exiting.
ss.remove_server_fd(4)
Unable to attach 838da6039XXXXXXXXXXXXXXXXXXb3dd91 inspector

**Comment by jackeymason** [comment]
> > If still you face the problem then follow below steps: try to uninstall the ios-webkit-debug-proxy and install again
> 
> ```
>  brew uninstall --force libimobiledevice ios-webkit-debug-proxy
>  brew install --HEAD libimobiledevice ios-webkit-debug-proxy
> ```
> 
> > Now try to run the command:
> 
> > 
> 
> ```
> sudo ios_webkit_debug_proxy -c <Device UDID>:9221 -d
> ```
> 
> > (replace the above device UDID)
> 
> It took me 5 hours of googling solutions to that didn't work for me, until I reached this one. Thank you @chethanshetty09 !!
> 
> By the way, the easiest way to get your phone's UDID is from iTunes. You can copy it from there

This did it for me. Your 5 hours reduced my search to around 30 minutes. Thank you!

**Comment by LazaroFilm** [comment]
> sudo chmod +x /var/db/lockdown

Somehow Terminal tells me I do not have permission. Looking at the lockdown folder info, it says permissions are only for _usbmuxd. even sudo won't change permissions. Am I missing something? I'm on Catalina 10.15.6

**Comment by cow614** [comment]
@LazaroFilm did you find a solution? I am also stuck on this now
