### ISSUE TITLE
Problem running on Debian 8

### ISSUE THREAD

**Issue by Eccenux** [google/ios-webkit-debug-proxy#170]
## Preparations

First I'll share some things I already figured out:
1. Kind of obvious part was that - on a clean machine - you might also need:
   
   ``` bash
   apt-get install git
   apt-get install make
   ```
2. What was not obvious is that you need to set up testing repos for Debian (e.g. as described [here](http://www.binarytides.com/enable-testing-repo-debian/)).
3. And... After you install standard packages:
   
   ``` bash
   apt-get install autoconf automake libusb-dev libusb-1.0-0-dev libplist-dev libplist++-dev usbmuxd libtool libimobiledevice-dev
   ```
4. ...It was also required to re-install some packages from testing repos:
   
   ``` bash
   apt-get -t testing install libimobiledevice-dev
   apt-get -t testing install libplist-dev
   ```
5. And then do standard stuff which is:
   
   ``` bash
   git clone https://github.com/google/ios-webkit-debug-proxy.git
   cd ios-webkit-debug-proxy
   ./autogen.sh
   make
   make install
   ```
### Steps

So after I finally was able to run `./autogen.sh` what I did was:
1. Attach iPhone (I can see it on my desktop, I can browse files).
2. Enable the inspector.
3. Run `ios_webkit_debug_proxy`.
4. Open `http://localhost:9221/` in Chrome.
### Result

> root@debian8:~# ios_webkit_debug_proxy
> Listing devices on :9221
> Could not start com.apple.webinspector!: Success
> Unable to attach f30d9...53dff32a...31 inspector

And list on `http://localhost:9221/` is empty.
### Expected

I expected something like `Starting com.apple.webinspector: Success` or something.

And my device visible after visiting `http://localhost:9221/`.
### Notes

And BTW I cannot run `idevice_id -l` (no such command). But I'm guessing it's MacOS specific (installed with XCode).

The iPhone is 4S with iOS 9.3.5.

**Comment by artygus** [comment]
hi @Eccenux there was a similar issue here https://github.com/google/ios-webkit-debug-proxy/issues/82#issuecomment-74205898

**Comment by artygus** [comment]
Closing since no reply from author.

**Comment by Eccenux** [comment]
Just for the record - comment from issue #82 doesn't seem related or I failed to see how that helps.

I was not able to really start the webinspector (seems like the message misleading says "success" while it is not fully started). And I'm assuming this is why I cannot see my device on the list.

**Comment by artygus** [comment]
@Eccenux `idevice_id` comes with libimobiledevice, could you try installing it and try `idevice_id -l` once again? Issue doesnt look related to iwdp to me, more like troubles with libimobiledevice

**Comment by Eccenux** [comment]
Hm... So this makes `idevice_id -l` work:
```bash
git clone https://github.com/libimobiledevice/libimobiledevice.git
cd libimobiledevice
#./autogen.sh #-> fail: /usr/bin/python-config: not found
apt-get install python2.7-dev
#./autogen.sh #->...OpenSSL could not be found
apt-get install libssl-dev
./autogen.sh
make
make install
```

BUT there is still a problem with connecting to device.

> root@debian8:~# ios_webkit_debug_proxy
> Listing devices on :9221
> **Could not start com.apple.webinspector!**: Success
> Unable to attach f30d938193...0253dff32a04831 inspector

Are there some logs I could check?

**Comment by artygus** [comment]
but does `idevice_id -l` shows your device? I think the express solution is to remove existing apt-packages and rebuild usbmuxd, libusbmuxd, libimobildevice and ios-webkit-device-proxy from sources and see if it works
