### ISSUE TITLE
Older version of the Chrome inspector doesn't work in Chrome 54

### ISSUE THREAD

**Issue by lexs** [google/ios-webkit-debug-proxy#172]
`KeyboardEvent.keyIdentifier` was removed in Chrome 54 but is used in old version of the inspector that iwdp uses. This means that the console no longer works as the `enter` key isn't recognized.

We'll need an modified version that replaces all uses of `KeyboardEvent.keyIdentifier` with `KeyboardEvent.key`.

**Comment by MarisaLovesUsAll** [comment]
Confirm.
Staying with google-chrome 53 for now.

**Comment by code-tree** [comment]
Any chance of this being fixed?

**Comment by artygus** [comment]
The purpose of the tool is to proxy requests to safari devtools through websocket protocol. If you're using linux or windows you could use devtools extracted from webkit  https://github.com/artygus/webkit-webinspector. If you don't like webkit devtools you could stick to valence from mozilla or similar projects.

**Comment by auchenberg** [comment]
You can use https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter to enable newer versions of the Chrome DevTools front-end.

**Comment by lexs** [comment]
@artygus The readme only mentions the Chrome inspector (which, while based on Webkit) is currently broken. The version specified here doesn't work anymore: https://github.com/google/ios-webkit-debug-proxy/blob/dcaa13922c460700a3b1212f6f6daa0bff7a17b0/src/ios_webkit_debug_proxy_main.c#L210

Please reopen this until that is fixed (or you recommend to use @auchenberg's adapter for example).

**Comment by artygus** [comment]
@lexs good catch

**Comment by code-tree** [comment]
@auchenberg that appears to require iTunes which isn't available on Linux. Any other options to resolve this? Even on Chrome 53 I can't select elements (can only expand them).

**Comment by artygus** [comment]
@code-tree it doesn't require iTunes, [usbmuxd](https://github.com/libimobiledevice/usbmuxd) should be sufficient. You could also use devtools frontend from webkit sources

**Comment by auchenberg** [comment]
@code-tree The adapter hasn't been tested in Unix, but feel free to open a PR with the changes needed. Sounds like it's pretty straightforward.

**Comment by artygus** [comment]
the alternatives were added to readme https://github.com/google/ios-webkit-debug-proxy/commit/4b940e6dd9629b1662d8fd8dc710f26731af9c6e
