### ISSUE TITLE
Sourcemap Support

### ISSUE THREAD

**Issue by netpoetica** [google/ios-webkit-debug-proxy#173]
Is there any recommended way to wire up source maps when manually navigating to a URL like `chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1` or a plan to support source maps with this tool in the future?

**Comment by artygus** [comment]
The purpose of the tool is to proxy requests to safari devtools through websocket protocol. If you're using linux or windows you could use devtools extracted from webkit, e.g. https://github.com/artygus/webkit-webinspector. If you don't like webkit devtools you could stick to https://github.com/mozilla/valence or similar projects.

**Comment by auchenberg** [comment]
You can use https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter to enable newer versions of the Chrome DevTools front-end.

**Comment by Xquick** [comment]
What is current status on using source maps? Is it possible to do? I am not able to see mapped files even though maps are being detected by Chrome.
