### ISSUE TITLE
Empty list shows in localhost:9221

### ISSUE THREAD

**Issue by PinkyJie** [google/ios-webkit-debug-proxy#174]
I try to use this proxy with iOS simulator, I open the simulator manually and open mobile safari to access a web page, and I'm sure the Web Inspect switch is ON on simulator. Then I run `ios_webkit_debug_proxy -d`, logs are showed in the following screenshot, no errors but no devices found in `localhost:9221`.

![image](https://cloud.githubusercontent.com/assets/551329/20695839/fcb6f534-b629-11e6-93f7-f18a8be54eec.png)

I use `homebrew` to install this proxy, is there anyone knows why?

**Comment by PinkyJie** [comment]
macOS version: 10.11.6
Xcode version: Version 8.1

**Comment by artygus** [comment]
hi @PinkyJie, can you confirm that you start simulator before the proxy?

**Comment by PinkyJie** [comment]
@artygus Yes, I started simulator before the proxy.

**Comment by artygus** [comment]
@PinkyJie could you please post the output of `lsof -n -i:27753 | grep LISTEN`?

**Comment by artygus** [comment]
and can you confirm that `::1 localhost` line is present in `/etc/hosts`?

**Comment by PinkyJie** [comment]
@artygus After I added `::1 localhost` in my hosts file, everything works fine. Thank you very much! I think this tip should be added in documentation.

**Comment by artygus** [comment]
@PinkyJie actually it's in the Troubleshooting section, hehe
