### ISSUE TITLE
Not able to install ios-webkit-debug-proxy1.7 release version  in Mac machine

### ISSUE THREAD

**Issue by Siddh010** [google/ios-webkit-debug-proxy#175]
Hi I am not able to install ios-webkit-debug-proxy 1.7 release version in mac machine.

Execute below command 

brew uninstall ios-webkit-debug-proxy  ( Which unstall 1.6 version )
brew install ios-webkit-debug-proxy     (will install 1.6 version instead of 1.7)
Also Tried with brew install ios-webkit-debug-proxy-1.7  but failed ..

==> Downloading https://homebrew.bintray.com/bottles/ios-webkit-debug-proxy-1.6.
Already downloaded: /Users/######/Library/Caches/Homebrew/ios-webkit-debug-proxy-1.6.el_capitan.bottle.tar.gz
==> Pouring ios-webkit-debug-proxy-1.6.el_capitan.bottle.tar.gz

Thanks
Siddartha

**Comment by artygus** [comment]
Hi @Siddh010 please try

    brew update
    brew upgrade ios-webkit-debug-proxy

**Comment by Siddh010** [comment]
Thank you .. I am able to update 1.7 version now.
