### ISSUE TITLE
Device is connected but debugging isn't working

### ISSUE THREAD

**Issue by kdziurdz** [google/ios-webkit-debug-proxy#176]
Hello, I wanted to use iwdp to debug my webap which isn't displayed properly on iPad. I'm using windows 10 and ios-webkit-debug-proxy-win32

When i go to `http://localhost:9221/`,
> 1. localhost:9222 - iPad
my device is displayed but it does not connect. nothing happens when i go :9222

All I did till now:
-turned on web inspection in iPad
-downloaded and ran iTunes
-connected iPad to my PC and choose "Trusted" when asked

i got following message in ios-webkit-debug-proxy-win32.exe (ran as administrator)

```
Invalid message _rpc_reportConnectedApplicationList: <dict>
        <key>WIRApplicationDictionaryKey</key>
        <dict>
                <key>PID:68</key>
                <dict>
                        <key>WIRApplicationIdentifierKey</key>
                        <key>PID:68</key>
                        <key>WIRIsApplicationProxyKey</key>
                        <false/>
                        <key>WIRApplicationNameKey</key>
                        <string></string>
                        <key>WIRApplicationBundleIdentifierKey</key>
                        <string>lockdownd</string>
                        <key>WIRIsApplicationActiveKey</key>
                        <integer>1</integer>
                </dict>
                <key>PID:223</key>
                <dict>
                        <key>WIRApplicationIdentifierKey</key>
                        <key>PID:223</key>
                        <key>WIRIsApplicationProxyKey</key>
                        <false/>
                        <key>WIRApplicationNameKey</key>
                        <string>Safari</string>
                        <key>WIRApplicationBundleIdentifierKey</key>
                        <string>com.apple.mobilesafari</string>
                        <key>WIRIsApplicationActiveKey</key>
                        <integer>1</integer>
                </dict>
                <key>PID:591</key>
                <dict>
                        <key>WIRApplicationIdentifierKey</key>
                        <key>PID:591</key>
                        <key>WIRIsApplicationProxyKey</key>
                        <true/>
                        <key>WIRApplicationNameKey</key>
                        <string></string>
                        <key>WIRApplicationBundleIdentifierKey</key>
                        <string>com.apple.WebKit.WebContent</string>
                        <key>WIRIsApplicationActiveKey</key>
                        <integer>1</integer>
                        <key>WIRHostApplicationIdentifierKey</key>
                        <key>PID:223</key>
                </dict>
        </dict>
</dict>
```

Any help?

**Comment by artygus** [comment]
hi @kdziurdz could you please checkout [x64 build](https://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/ios-webkit-debug-proxy-win64.zip/download), it has the latest changes from original repository

**Comment by programmin1** [comment]
Have you tested an iOS9 device or older? Because they broke connecting it to a PC with libimobiledevice in iOS10, you may need to recompile libimobiledevice :(

**Comment by artygus** [comment]
@programmin1 the x64 build includes changes from libimobiledevice

**Comment by kdziurdz** [comment]
x64 build still doesn't work but it is much better :D  
iOS ver 9.3.5. it still asks me for update

now, in localhost:9222

```
Inspectable pages for iPad (Konrad):
http://<<generatedurl>>.ngrok.io/?folderName=test12
```
but after clicking the url

`Unable to connect to chrome-devtools-frontend.appspot.com:80`

btw. I use ngrok to tunnel my local webapp outside. I found it more stable than localtunnel

**Comment by artygus** [comment]
@kdziurdz proxying devtools through localhost is kind of broken on windows, you could try to navigate to `chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1` directly. But latest chrome devtools hardly work with recent iOS versions, you could try using [RemoteDebug/remotedebug-ios-webkit-adapter](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter) or webkit devtools, you could find exracted version with mini webserver [here](https://github.com/artygus/webkit-webinspector)
