### ISSUE TITLE
Doesn't work with iOS10+

### ISSUE THREAD

**Issue by dcaric** [google/ios-webkit-debug-proxy#177]
I have devices on iOS10.1 and iOS10.2 and also on some older like 7.x
I have also precompile libimobilledevice library using
- clone from git https://github.com/libimobiledevice/libimobiledevice
- CFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib ./configure
which forces to ouse openssl instead favoured Apple's TLS
- than make and make install

and I got these commands working

ETK-MacBook-Pro:git dariocaric$ ls -l /usr/local/bin/idevice*
-rwxr-xr-x  1 dariocaric  admin   9316 Dec 18 19:50 /usr/local/bin/idevice_id
-rwxr-xr-x  1 dariocaric  admin  49444 Dec 18 19:50 /usr/local/bin/idevicebackup
-rwxr-xr-x  1 dariocaric  admin  67692 Dec 18 19:50 /usr/local/bin/idevicebackup2
-rwxr-xr-x  1 dariocaric  admin  30176 Dec 18 19:50 /usr/local/bin/idevicecrashreport
-rwxr-xr-x  1 dariocaric  admin  14104 Dec 18 19:50 /usr/local/bin/idevicedate
-rwxr-xr-x  1 dariocaric  admin  19796 Dec 18 19:50 /usr/local/bin/idevicedebug
-rwxr-xr-x  1 dariocaric  admin  22324 Dec 18 19:50 /usr/local/bin/idevicedebugserverproxy
-rwxr-xr-x  1 dariocaric  admin  14624 Dec 18 19:50 /usr/local/bin/idevicediagnostics
-rwxr-xr-x  1 dariocaric  admin   9008 Dec 18 19:50 /usr/local/bin/ideviceenterrecovery
-rwxr-xr-x  1 dariocaric  admin  30604 Dec 18 19:50 /usr/local/bin/ideviceimagemounter
-rwxr-xr-x  1 dariocaric  admin  24660 Dec 18 19:50 /usr/local/bin/ideviceinfo
-rwxr-xr-x  1 dariocaric  admin   9404 Dec 18 19:50 /usr/local/bin/idevicename
-rwxr-xr-x  1 dariocaric  admin  14108 Dec 18 19:50 /usr/local/bin/idevicenotificationproxy
-rwxr-xr-x  1 dariocaric  admin  37020 Dec 18 19:50 /usr/local/bin/idevicepair
-rwxr-xr-x  1 dariocaric  admin  33892 Dec 18 19:50 /usr/local/bin/ideviceprovision
-rwxr-xr-x  1 dariocaric  admin  14000 Dec 18 19:50 /usr/local/bin/idevicescreenshot
-rwxr-xr-x  1 dariocaric  admin  14160 Dec 18 19:50 /usr/local/bin/idevicesyslog

One example:
ETK-MacBook-Pro:git dariocaric$ idevicename 
Dario’s iPad Air2
ETK-MacBook-Pro:git dariocaric$ 

But when I want to start ios_webkit_debug_proxy I'm getting lockdown problem (with the latest iOS_webkit_debug_proxy, running on macOS Sierra but like I said it is working on <iOS10 so it is not related to macOS Sierra)

ETK-MacBook-Pro:~ dariocaric$ ios_webkit_debug_proxy 
Listing devices on :9221
Could not connect to lockdownd. Exiting.: Broken pipe
Unable to attach a79e..... inspector

Do you know for this problem is there a plan to fix it for iOS10+?

Thanks!
Dario

**Comment by artygus** [comment]
Hi @dcaric looks like permissions problems, please check the thread https://github.com/google/ios-webkit-debug-proxy/issues/160, hope it helps

**Comment by dcaric** [comment]
You mean chmod +x /var/db/lockdown ?
No, I gave that before and several times. This is (I think) something new

**Comment by artygus** [comment]
k, does `idevicename -d` shows the error code?

**Comment by artygus** [comment]
I see now you posted that it works, then it looks like iwdp utility might be using old libraries, because it makes the same `lockdownd_client_new_with_handshake` call as `idevicename` does, could you confirm that you rebuilt iwdp after buidling libimobiledevice from master?

**Comment by dcaric** [comment]
Yes that's what I thought. I was trying to rebuild from source but for now I have to figure how to solve this
make....
libtool: link: gcc -I/usr/local/include -I/usr/local/Cellar/usbmuxd/1.0.10_1/include -I/usr/local/include -I/usr/local/include -g -O2 -Wall -Werror -o ios_webkit_debug_proxy ios_webkit_debug_proxy-ios_webkit_debug_proxy_main.o ios_webkit_debug_proxy-base64.o ios_webkit_debug_proxy-char_buffer.o ios_webkit_debug_proxy-device_listener.o ios_webkit_debug_proxy-hash_table.o ios_webkit_debug_proxy-ios_webkit_debug_proxy.o ios_webkit_debug_proxy-port_config.o ios_webkit_debug_proxy-rpc.o ios_webkit_debug_proxy-sha1.o ios_webkit_debug_proxy-socket_manager.o ios_webkit_debug_proxy-webinspector.o ios_webkit_debug_proxy-websocket.o  -L/usr/local/lib /usr/local/lib/libimobiledevice.dylib -L/usr/local/Cellar/libplist/1.12/lib -L/usr/local/Cellar/usbmuxd/1.0.10_1/lib -L/usr/local/opt/openssl/lib -lssl -lcrypto -lz -lusbmuxd -lpthread /usr/local/lib/libplist.dylib -lm -pthread
clang: error: argument unused during compilation: '-pthread'

**Comment by artygus** [comment]
Yeah, strange. It's indeed useless during compilation, but required on linking. I think you could try to uninstall hand-built libimobiledevice and go for:

    brew install libimobiledevice --HEAD
    brew install ios-webkit-debug-proxy  --HEAD

**Comment by dcaric** [comment]
But If I do brew install libimobiledevice --HEAD it will not work. Like I said I have to compile libimobiledevice with 
CFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib
to use openssl, otherwise it will not work. Now idevice... commands work, at least that works.

**Comment by artygus** [comment]
brew formula depends on openssl, it should install the proper version. at least it works fro me as expected

**Comment by dcaric** [comment]
OK I will try, thx

**Comment by artygus** [comment]
On the second thought to skip the error you could simple remove `-Werror` from `configure.ac`

**Comment by dcaric** [comment]
I tried before -Werror and it didn't work. Now I have some problems to fix for 
 brew install --HEAD libimobiledevice
I'm getting
glibtoolize:   error: $pkgauxdir is not a directory: '/usr/local/Cellar/libtool/2.4.6_1/share/libtool/build-aux'
autom4te: need GNU m4 1.4 or later: /usr/bin/m4
aclocal: error: echo failed with exit status: 1
autom4te: need GNU m4 1.4 or later: /usr/bin/m4
autoheader: '/usr/local/Cellar/autoconf/2.69/bin/autom4te' failed with exit status: 1
autom4te: need GNU m4 1.4 or later: /usr/bin/m4
automake: error: autoconf failed with exit status: 1
autom4te: need GNU m4 1.4 or later: /usr/bin/m4
./autogen.sh: line 14: ./configure: No such file or directory
xcodebuild: error: SDK "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk" cannot be located.
clang: error: unable to find utility "clang", not a developer tool or in PATH

I have to fix this, but I will post here once when i do that

**Comment by dcaric** [comment]
i don't know what I didn't do :) and I ended up with this (like before)
during make 

/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in common
  CC       socket.lo
  CC       thread.lo
  CC       debug.lo
In file included from debug.c:36:
../src/idevice.h:30:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make[2]: *** [debug.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2


so I did ..
ETK-MacBook-Pro:libimobiledevice--git dariocaric$ brew install openssl --force
Warning: openssl-1.0.2j already installed, it's just not linked.
ETK-MacBook-Pro:libimobiledevice--git dariocaric$ 
ETK-MacBook-Pro:libimobiledevice--git dariocaric$ 
ETK-MacBook-Pro:libimobiledevice--git dariocaric$ brew link openssl --force
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
ETK-MacBook-Pro:libimobiledevice--git dariocaric$ 

which means I need 
CFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib ./configure
what I wrote at the begging

I'm using latex macOS Sierra so maybe this is a root cause of my problem ?



Than I did this:
ETK-MacBook-Pro:~ dariocaric$ brew install ios-webkit-debug-proxy --HEAD <=== doesn't exists ?
Error: No head is defined for ios-webkit-debug-proxy
ETK-MacBook-Pro:~ dariocaric$ brew install ios-webkit-debug-proxy <== this was ok
==> Installing dependencies for ios-webkit-debug-proxy: libimobiledevice
==> Installing ios-webkit-debug-proxy dependency: libimobiledevice
.......


but after all this I still have problem which I had at the beginning

I can do this and other commands are ok

ETK-MacBook-Pro:~ dariocaric$ idevicename 
Dario’s iPad Air2
ETK-MacBook-Pro:~ dariocaric$ 

but I cannot do this
ETK-MacBook-Pro:~ dariocaric$ ios_webkit_debug_proxy
Listing devices on :9221
Could not connect to lockdownd. Exiting.: Broken pipe
Unable to attach a79e...... inspector


and yes I did this also
ETK-MacBook-Pro:~ dariocaric$ sudo chmod -R 777 /var/db/lockdown/

So at the end I think this is problem with ios_webkit_dev_proxy, but I don't get it what - jet

**Comment by artygus** [comment]
It doesn't look like problem with iwdp because it fails on the libimobiledevice call, which is most likely related to old libimobiledevice. Did you try to pass CFLAGS to brew while installing libimobiledevice?

**Comment by artygus** [comment]
just in case, do you have xcode command line tools installed? I mean maybe it's stale version or something?

**Comment by dcaric** [comment]
I cam cmd tools, how can I checks is iwdp calls correct libimobiledevice ?
I have
/usr/local/Cellar/libimobiledevice
/usr/local/Cellar/libimobiledevice/1.2.0/include/libimobiledevice
/usr/local/include/libimobiledevice
/usr/local/opt/libimobiledevice

and...
ETK-MacBook-Pro:~ dariocaric$ ls -l /usr/local/include/libimobiledevice
total 472
-rw-r--r--  1 dariocaric  admin  13555 Dec 19 20:54 afc.h
-rw-r--r--  1 dariocaric  admin   9249 Dec 19 20:54 debugserver.h
-rw-r--r--  1 dariocaric  admin   7754 Dec 19 20:54 diagnostics_relay.h
-rw-r--r--  1 dariocaric  admin   6584 Dec 19 20:54 file_relay.h
-rw-r--r--  1 dariocaric  admin   4670 Dec 19 20:54 heartbeat.h
-rw-r--r--  1 dariocaric  admin   7399 Dec 19 20:54 house_arrest.h
-rw-r--r--  1 dariocaric  admin  24189 Dec 19 20:54 installation_proxy.h
-rw-r--r--  1 dariocaric  admin   8904 Dec 19 20:54 libimobiledevice.h
-rw-r--r--  1 dariocaric  admin  19900 Dec 19 20:54 lockdown.h
-rw-r--r--  1 dariocaric  admin   5995 Dec 19 20:54 misagent.h
-rw-r--r--  1 dariocaric  admin   7135 Dec 19 20:54 mobile_image_mounter.h
-rw-r--r--  1 dariocaric  admin   9976 Dec 19 20:54 mobilebackup.h
-rw-r--r--  1 dariocaric  admin   8920 Dec 19 20:54 mobilebackup2.h
-rw-r--r--  1 dariocaric  admin  13560 Dec 19 20:54 mobilesync.h
-rw-r--r--  1 dariocaric  admin   8034 Dec 19 20:54 notification_proxy.h
-rw-r--r--  1 dariocaric  admin   6972 Dec 19 20:54 property_list_service.h
-rw-r--r--  1 dariocaric  admin   6118 Dec 19 20:54 restore.h
-rw-r--r--  1 dariocaric  admin   6997 Dec 19 20:54 sbservices.h
-rw-r--r--  1 dariocaric  admin   4218 Dec 19 20:54 screenshotr.h
-rw-r--r--  1 dariocaric  admin   6158 Dec 19 20:54 service.h
-rw-r--r--  1 dariocaric  admin   6107 Dec 19 20:54 syslog_relay.h
-rw-r--r--  1 dariocaric  admin   4889 Dec 19 20:54 webinspector.h
ETK-MacBook-Pro:~ dariocaric$ ls -l /usr/local/opt/libimobiledevice
lrwxr-xr-x  1 dariocaric  admin  32 Dec 19 20:55 /usr/local/opt/libimobiledevice -> ../Cellar/libimobiledevice/1.2.0
ETK-MacBook-Pro:~ dariocaric$ ls -l /usr/local/Cellar/libimobiledevice
total 0
drwxr-xr-x  11 dariocaric  admin  374 Dec 19 20:55 1.2.0
ETK-MacBook-Pro:~ dariocaric$ 



and like I said all these commands are working perfectly ok

ETK-MacBook-Pro:~ dariocaric$ ls -l /usr/local/bin/idev*
-rwxr-xr-x  1 dariocaric  admin   9316 Dec 19 20:54 /usr/local/bin/idevice_id
-rwxr-xr-x  1 dariocaric  admin  49444 Dec 19 20:54 /usr/local/bin/idevicebackup
-rwxr-xr-x  1 dariocaric  admin  67692 Dec 19 20:54 /usr/local/bin/idevicebackup2
-rwxr-xr-x  1 dariocaric  admin  30176 Dec 19 20:54 /usr/local/bin/idevicecrashreport
-rwxr-xr-x  1 dariocaric  admin  14104 Dec 19 20:54 /usr/local/bin/idevicedate
-rwxr-xr-x  1 dariocaric  admin  19796 Dec 19 20:54 /usr/local/bin/idevicedebug
-rwxr-xr-x  1 dariocaric  admin  24324 Dec 19 20:54 /usr/local/bin/idevicedebugserverproxy
-rwxr-xr-x  1 dariocaric  admin  14624 Dec 19 20:54 /usr/local/bin/idevicediagnostics
-rwxr-xr-x  1 dariocaric  admin   9008 Dec 19 20:54 /usr/local/bin/ideviceenterrecovery
-rwxr-xr-x  1 dariocaric  admin  30604 Dec 19 20:54 /usr/local/bin/ideviceimagemounter
-rwxr-xr-x  1 dariocaric  admin  24660 Dec 19 20:54 /usr/local/bin/ideviceinfo
-rwxr-xr-x  1 dariocaric  admin   9404 Dec 19 20:54 /usr/local/bin/idevicename
-rwxr-xr-x  1 dariocaric  admin  14108 Dec 19 20:54 /usr/local/bin/idevicenotificationproxy
-rwxr-xr-x  1 dariocaric  admin  37020 Dec 19 20:54 /usr/local/bin/idevicepair
-rwxr-xr-x  1 dariocaric  admin  33892 Dec 19 20:54 /usr/local/bin/ideviceprovision
-rwxr-xr-x  1 dariocaric  admin  14000 Dec 19 20:54 /usr/local/bin/idevicescreenshot
-rwxr-xr-x  1 dariocaric  admin  14160 Dec 19 20:54 /usr/local/bin/idevicesyslog
ETK-MacBook-Pro:~ dariocaric$ 

And no I didn't try to pass CFLAGS to brew while installing libimobiledevice, i suppose I can try that in a while. But on the other hand no matter how I get those commands working they are now working fine. So if iwdp is using some of them it should work?

**Comment by artygus** [comment]
versions from brew come prebuilt, it relies on dynamic libs found somewhere in `@@HOMEBREW_PREFIX@@/opt/libimobiledevice..`

**Comment by artygus** [comment]
I'm concerned why do use `/Applications/Xcode.app/Contents/Developer/usr/bin/make` to run  make? and the error you posted

> glibtoolize: error: $pkgauxdir is not a directory: '/usr/local/Cellar/libtool/2.4.6_1/share/libtool/build-aux'
> autom4te: need GNU m4 1.4 or later: /usr/bin/m4
> aclocal: error: echo failed with exit status: 1
> autom4te: need GNU m4 1.4 or later: /usr/bin/m4
> ...
> xcodebuild: error: SDK > "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk" cannot be located.

looks like you don't have xcode command line tools installed properly

**Comment by artygus** [comment]
PS. Was able to test current version with iOS 10.2 and it works for me

**Comment by dcaric** [comment]
lucky you :)
but with what iOS device ?
I had some problem with paths but I fixed that


I didi this

ETK-MacBook-Pro:Cellar dariocaric$ rm /usr/local/bin/idev*
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ ls -l /usr/local/bin/idev*
ls: /usr/local/bin/idev*: No such file or directory
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ brew uninstall ios-webkit-debug-proxy 
Uninstalling /usr/local/Cellar/ios-webkit-debug-proxy/1.7... (19 files, 358.3K)
ETK-MacBook-Pro:Cellar dariocaric$ brew uninstall ios-webkit-debug-proxy 
Error: No such keg: /usr/local/Cellar/ios-webkit-debug-proxy
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ brew uninstall libimobiledevice
Error: No such keg: /usr/local/Cellar/libimobiledevice
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ CFLAGS='-I/usr/local/opt/openssl/include' LDFLAGS='-L/usr/local/opt/openssl/lib' brew install libimobiledevice --HEAD
==> Using the sandbox
==> Cloning https://git.libimobiledevice.org/libimobiledevice.git
Updating /Users/dariocaric/Library/Caches/Homebrew/libimobiledevice--git
==> Checking out branch master
==> ./autogen.sh
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libimobiledevice/HEAD-c7f24a9 --without-cython
==> make install
Warning: This keg was marked linked already, continuing anyway
🍺  /usr/local/Cellar/libimobiledevice/HEAD-c7f24a9: 66 files, 1M, built in 41 seconds
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ ls -l /usr/local/bin/idev*
lrwxr-xr-x  1 dariocaric  admin  54 Dec 19 22:14 /usr/local/bin/idevice_id -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/idevice_id
lrwxr-xr-x  1 dariocaric  admin  57 Dec 19 22:14 /usr/local/bin/idevicebackup -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/idevicebackup
lrwxr-xr-x  1 dariocaric  admin  58 Dec 19 22:14 /usr/local/bin/idevicebackup2 -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/idevicebackup2
lrwxr-xr-x  1 dariocaric  admin  62 Dec 19 22:14 /usr/local/bin/idevicecrashreport -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/idevicecrashreport
lrwxr-xr-x  1 dariocaric  admin  55 Dec 19 22:14 /usr/local/bin/idevicedate -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/idevicedate
lrwxr-xr-x  1 dariocaric  admin  56 Dec 19 22:14 /usr/local/bin/idevicedebug -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/idevicedebug
lrwxr-xr-x  1 dariocaric  admin  67 Dec 19 22:14 /usr/local/bin/idevicedebugserverproxy -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/idevicedebugserverproxy
lrwxr-xr-x  1 dariocaric  admin  62 Dec 19 22:14 /usr/local/bin/idevicediagnostics -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/idevicediagnostics
lrwxr-xr-x  1 dariocaric  admin  64 Dec 19 22:14 /usr/local/bin/ideviceenterrecovery -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/ideviceenterrecovery
lrwxr-xr-x  1 dariocaric  admin  63 Dec 19 22:14 /usr/local/bin/ideviceimagemounter -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/ideviceimagemounter
lrwxr-xr-x  1 dariocaric  admin  55 Dec 19 22:14 /usr/local/bin/ideviceinfo -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/ideviceinfo
lrwxr-xr-x  1 dariocaric  admin  55 Dec 19 22:14 /usr/local/bin/idevicename -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/idevicename
lrwxr-xr-x  1 dariocaric  admin  68 Dec 19 22:14 /usr/local/bin/idevicenotificationproxy -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/idevicenotificationproxy
lrwxr-xr-x  1 dariocaric  admin  55 Dec 19 22:14 /usr/local/bin/idevicepair -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/idevicepair
lrwxr-xr-x  1 dariocaric  admin  60 Dec 19 22:14 /usr/local/bin/ideviceprovision -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/ideviceprovision
lrwxr-xr-x  1 dariocaric  admin  61 Dec 19 22:14 /usr/local/bin/idevicescreenshot -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/idevicescreenshot
lrwxr-xr-x  1 dariocaric  admin  57 Dec 19 22:14 /usr/local/bin/idevicesyslog -> ../Cellar/libimobiledevice/HEAD-c7f24a9/bin/idevicesyslog


ETK-MacBook-Pro:Cellar dariocaric$ idevicename <===== WORKS FINE !!
Dario’s iPad Air2
ETK-MacBook-Pro:Cellar dariocaric$ 





ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ brew install ios-webkit-debug-proxy --HEAD  <== not working
Error: No head is defined for ios-webkit-debug-proxy
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ brew install ios-webkit-debug-proxy <== installing
==> Downloading https://homebrew.bintray.com/bottles/ios-webkit-debug-proxy-1.7.sierra.bottle.tar.gz
Already downloaded: /Users/dariocaric/Library/Caches/Homebrew/ios-webkit-debug-proxy-1.7.sierra.bottle.tar.gz
==> Pouring ios-webkit-debug-proxy-1.7.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/ios-webkit-debug-proxy/1.7: 19 files, 358.3K
ETK-MacBook-Pro:Cellar dariocaric$ 
ETK-MacBook-Pro:Cellar dariocaric$ 


TRY iwdp but now I have seg fault

ETK-MacBook-Pro:Cellar dariocaric$ ios_webkit_debug_proxy
Listing devices on :9221
Segmentation fault: 11
ETK-MacBook-Pro:Cellar dariocaric$

**Comment by dcaric** [comment]
OK I did it working on the other (same type) mac so I agree this is some config issue with my first mac

**Comment by chethanshetty09** [comment]
Below steps worked for me :)

Make sure the below Capabilities are setup properly
```
capabilities.setCapability("autoWebView", true);
capabilities.setCapability("startIWDP", true);
```
If the ios-webkit-debug-proxy is not installed, install it with below command:
`brew install --HEAD libimobiledevice ios-webkit-debug-proxy
`
Try to run this command from terminal and see if the connected device has the Web kit proxy running
`sudo ios_webkit_debug_proxy -c <Device UDID>:9221 -d`(replace the above device UDID)

If you see some errors, like
Could not connect to lockdownd. Exiting Permission denied
Then you need to give permission:
`sudo chmod +x /var/db/lockdown`

Now try to run the command:

`sudo ios_webkit_debug_proxy -c <Device UDID>:9221 -d`
(replace the above device UDID)
If still you face the problem then follow below steps: try to uninstall the ios-webkit-debug-proxy and install again

```
brew uninstall --force libimobiledevice ios-webkit-debug-proxy
brew install --HEAD libimobiledevice ios-webkit-debug-proxy
```
Now try to run the command:

`sudo ios_webkit_debug_proxy -c <Device UDID>:9221 -d`
(replace the above device UDID)

**Comment by z2014** [comment]
> xcode command

when i run
`brew install opencv@2` in docker build from centos, i got this error too.
and i run `xcode-select --install` in docker , i got `xcode-select : command not found`,
so how to fix this problem
