### ISSUE TITLE
child process exited with code 2

### ISSUE THREAD

**Issue by HemantTrivedi** [google/ios-webkit-debug-proxy#179]
While exciting the following command , it gives error as 'child process exited with code '

/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/ios-webkit- debug- proxy-launcher.js -c 8ee9e0f670b763192b38fbdcb10dce856033351b:27753 –d 

I have tried following commands as well   

ios_webkit_debug_proxy -c 0e4b2f612b65e98c1d07d22ee08678130d345429:27753 -d
/usr/local/lib/node_modules/appium/bin/ios-webkit-debug-proxy-launcher.js -c 8ee9e0f670b763192b38fbdcb10dce856033351b:27753 –d 

but i am not getting connected to device .

**Comment by artygus** [comment]
is it still happening after you resolved #181?
