### ISSUE TITLE
Can't connect get select_port() failed  Could not connect to lockdownd errors

### ISSUE THREAD

**Issue by mkarlovich** [google/ios-webkit-debug-proxy#18]
I can't connect, I get this error running the following command.  iPhone 5 connected with web inspector turned on.

> ios_webkit_debug_proxy -c d5e07800839a0bdddc8d07ef931e9f878c3fc9:ios_webkit_debug_proxy -d

select_port() failed
Unable to create registry
ss.add_fd(3)
ss.recv fd=3 len=294
ss.recv fd=3 len=684
ss.add_server_fd(4)
Could not connect to lockdownd. Exiting.: Undefined error: 0
ss.remove_server_fd(4)
Unable to attach d5e07800839a0bc3dddc8d07ef931e9f878c3fc9 inspector

**Comment by artygus** [comment]
I guess the problem was resolved in later versions of the utility
