### ISSUE TITLE
Can't see any info print in Chrome's console while use console.log()

### ISSUE THREAD

**Issue by cgyrock** [google/ios-webkit-debug-proxy#180]
I run my Cordova App in my iPhone device.
There are codes in index.js 

    var app = {
        // Application Constructor
        initialize: function() {
            document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
        },

        // deviceready Event Handler
        //
        // Bind any cordova events here. Common events are:
        // 'pause', 'resume', etc.
        onDeviceReady: function() {
            this.receivedEvent('deviceready');
        },

        // Update DOM on a Received Event
        receivedEvent: function(id) {
            var parentElement = document.getElementById(id);
            var listeningElement = parentElement.querySelector('.listening');
            var receivedElement = parentElement.querySelector('.received');

            listeningElement.setAttribute('style', 'display:none;');
            receivedElement.setAttribute('style', 'display:block;');

            console.log('Received Event: ' + id);
        }
    };

    app.initialize();

This is a standard Cordova genered javascript file,
there is 'console.log('Received Event: ' + id);' in receivedEvent function
,but I can't see any info print in Chrome's console

**Comment by artygus** [comment]
hi @cgyrock the sole purpose of the tool is to proxy ios safari webinspector packets to some endpoint through websockets, unfortunately webkit and chrome protocols diverged quite a bit, please see [readme](https://github.com/google/ios-webkit-debug-proxy#devtools-note) for possible alternatives
