### ISSUE TITLE
Could not connect to lockdownd. Exiting.: Broken pipe

### ISSUE THREAD

**Issue by HemantTrivedi** [google/ios-webkit-debug-proxy#181]
I tried to run the web-kit-debug-proxy on Appium 1.6 and ios 10. But it displays the lock down error. I tried to update the lib device-Head but still the issue persists. Please help me on this

**Comment by artygus** [comment]
hi @HemantTrivedi did you rebuild the tool after updating libimobiledevice?

**Comment by HemantTrivedi** [comment]
Hi @artygus  ,thanks for the replay . I tried following command  and it's now connecting . 
 brew link --overwrite ios-webkit-debug-proxy
brew link --overwrite --dry-run ios-webkit-debug-proxy


But I have another doubt . While launching the Appium session , in appium logs I am getting appium version as 1.5 while I updated to 1.6. Also is's not getting connected to machine . may I know what could be the possible cause for it ?

**Comment by artygus** [comment]
I'm not familiar with appium, does it use bundled version of `ios-webkit-debug-proxy` or requires to be present in system?

Anyway, you could try this:

    brew update
    brew install --HEAD libimobiledevice
    brew install --HEAD ios-webkit-debug-proxy

**Comment by HemantTrivedi** [comment]
Thanks @artygus . I will try that .
