### ISSUE TITLE
page Id

### ISSUE THREAD

**Issue by VasilijSviridov** [google/ios-webkit-debug-proxy#184]
Hi,

Could you tell me how do I get pageId before connecting to ws ?
As example pageId was changed from 1 to 7 , how do I get that pageId ? 

Cheers

**Comment by artygus** [comment]
hi @VasilijSviridov not sure I got that, but you could try using "http://localhost:9222/json/list" endpoint

**Comment by VasilijSviridov** [comment]
well, made it dirty way :) just parsing the whole localhost:port and matching the page number :/
I will double check /json/list

Cheers @artygus
