### ISSUE TITLE
localhost:9221 showing only iOS simulator (no way to inspect)

### ISSUE THREAD

**Issue by ekulabuhov** [google/ios-webkit-debug-proxy#185]
![image](https://cloud.githubusercontent.com/assets/4452263/22984116/4d8ed3e6-f39c-11e6-9a77-fb3b34faebe1.png)

I can see Simulator in the list but I can't open dev-tools. What could be causing this? Running iOS v10, Safari, Debugging enabled.

**Comment by ekulabuhov** [comment]
This is the error I get:

```
Listing devices on :9221
Connected :9222 to SIMULATOR (SIMULATOR)
Invalid message _rpc_reportConnectedDriverList: <dict>
	<key>WIRDriverDictionaryKey</key>
	<dict>
	</dict>
</dict>
Disconnected :9222 from SIMULATOR (SIMULATOR)
```

**Comment by artygus** [comment]
@ekulabuhov do you use latest version (which is 1.7.1)?

**Comment by ekulabuhov** [comment]
@artygus using 1.6. That's the latest according to brew. Do I need to build from source?

**Comment by artygus** [comment]
@ekulabuhov I think you need to update brew, https://github.com/Homebrew/homebrew-core/pull/9043 was merged not so long ago

**Comment by ekulabuhov** [comment]
Tried updating multiple times. Still points to an older version. Installed successfully pointing directly at the Pull Request: `brew install https://raw.githubusercontent.com/artygus/homebrew-core/50d1ca15c028cbef32f176f6cd13b4e9e0147ab4/Formula/ios-webkit-debug-proxy.rb`

**Comment by ekulabuhov** [comment]
@artygus and yes, everything works now as expected! Thanks!

EDIT: except console, doesn't evaluate, you can type in it but nothing happens.
