### ISSUE TITLE
Unable to select a DOM node and view or change its styles

### ISSUE THREAD

**Issue by dmusicant** [google/ios-webkit-debug-proxy#186]
While I can view the DOM tree, it does not let me select one to view the styles, or change the styles.

It starts with the top node selected but even that one, changing the styles on the right pane does not update anything.

USING:
openSUSE 42.1 LEAP 64 bit
Linux Kernel 4.9.0-2 default
KDE 5.5.5
Intel Core i7-6600U
16 GB RAM

**Comment by artygus** [comment]
please check out readme, devtools section https://github.com/google/ios-webkit-debug-proxy#devtools-note
