### ISSUE TITLE
Element Selector Does not Work

### ISSUE THREAD

**Issue by FerrazzzZ** [google/ios-webkit-debug-proxy#188]
This tools is fantastic specially for people who love to develop web apps with google chrome but it would be awesome if the element selector worked.

For example in the safari browser you can select the element selector and than tap anywhere on the page and it will inspect to that element. It would be so awesome if this feature worked in google chrome inspector.

**Comment by auchenberg** [comment]
Please see https://github.com/google/ios-webkit-debug-proxy#devtools-note
