### ISSUE TITLE
Several errors on start-up (in chrome-devtools://devtools/bundled/inspector.html)

### ISSUE THREAD

**Issue by aleclarson** [google/ios-webkit-debug-proxy#189]
1. Installed with: `brew install ios-webkit-debug-proxy`

2. Opened the Safari app in "iOS 10.2 Simulator" (with the "Web Inspector" setting enabled)

3. Goto `www.google.com`

4. Run `ios_webkit_debug_proxy -f chrome-devtools://devtools/bundled/inspector.html` 

5. See [this](http://i.imgur.com/yQeRkoz.png) in the `chrome-devtools` tab

Chrome v57.0.2987.110 (64-bit)
macOS v10.12.3

**Comment by artygus** [comment]
hi @aleclarson, please check out readme https://github.com/google/ios-webkit-debug-proxy#devtools-note
