### ISSUE TITLE
send failed: Socket is not connected

### ISSUE THREAD

**Issue by unbug** [google/ios-webkit-debug-proxy#19]
Dont know whether this proxy will go to google's server or not,the debug of Chrome for android is blocked by GWF in China,and now this proxy give me "send failed: Socket is not connected" when I click a page to debug,I can view the device list and see the pages,but can not debug it,if the proxy go to google's server,then it's blocked by GWF too ;(

**Comment by devmidai** [comment]
我的好像还是不行，提示send failed: Socket is not connected
