### ISSUE TITLE
Not able do see webview in browser

### ISSUE THREAD

**Issue by chOOnz** [google/ios-webkit-debug-proxy#190]
I have trouble beeing able to see my webview in my browser when visiting `localhost:9222` after running `ios_webkit_debug_proxy` in command line. Also when I visit `localhost:9221` I am able to see my device which is connected. I already tried different apps which contain a webview, like browsers, but I was not able to see any webcontent when visiting `localhost:9222`.

Some info:
iOS version: 10.2.1
OSX version: 10.11.6
iwdp version: 1.7.1 (updated everything 40mins ago)

Everything was working fine a few weeks ago.

**Comment by artygus** [comment]
@chOOnz what does `ios_webkit_debug_proxy -V` show?

**Comment by artygus** [comment]
Oh now I see, I don't think it is possible to see webviews from apps other than browser if they don't expose it. To make sure iwdp is broken, please check if you can see those webviews in Safari on you Mac

**Comment by chOOnz** [comment]
No, I'm not able to see anything there... That's pretty strange. Do you have an idea where the problem might lie?

**Comment by artygus** [comment]
@chOOnz could it be that webinspector switch is set to disabled for some reason? (Settings -> Safari -> Advanced -> Web Inspector)

**Comment by chOOnz** [comment]
Nope, it's enabled... I never had this behaviour before.

**Comment by artygus** [comment]
nope, never seen anything similar before 😞

**Comment by chOOnz** [comment]
It's funny, because I tried again an opened safari on iOS and suddenly safari on mac is noticing this webview. But it's still not noticing the webview of my app.... Man this is some strange sh**..

I will play around now and come back here when I solved it but it clearly isn't a problem caused by iwdp.

**Comment by artygus** [comment]
Hehe, I'm pretty sure you've seen it already, but just in case http://stackoverflow.com/a/16483200

**Comment by chOOnz** [comment]
We solved the problem. It was a misconfiguration of our app build tool...

Thanks for your help @artygus !

**Comment by artygus** [comment]
cool! glad you got to the bottom of it

**Comment by DewanshuAwasthi** [comment]
@buekera  hi could you please explain the solution. i am facing this issue from 2 weeks and trust my nights are sleepless :( 
Proxy 1.8

**Comment by buekera** [comment]
@DewanshuAwasthi I'm not able to tell you what fixed the issue because I'm not the one building the app, sorry :/

**Comment by DewanshuAwasthi** [comment]
Hi @buekera Thank you for the response. 

I understand we cant do anything if the issue is with app build. But for me i am able to get webview on a remote location but not able to get the webview if i am using the same app(on which test is running on remote location) on local setup
