### ISSUE TITLE
 mingw64 branch - Windows support

### ISSUE THREAD

**Issue by webmanAv** [google/ios-webkit-debug-proxy#192]
Hi,
I'm using Appium on windows with latest ios 10 device.
I understand that mingw64 branch will enable to produce windows version, from this repository instead of using https://github.com/artygus/ios-webkit-debug-proxy-win32

Do you some estimation, when will it be ready?, because it will be very helpful for me.
Thanks,
 Aviram

**Comment by artygus** [comment]
Hi @webmanAv, I'll finish it over the weekend. In the mean time you could use custom [build](https://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/ios-webkit-debug-proxy-win64.zip/download) for windows it's based on 1.7.0

**Comment by artygus** [comment]
win32 support finally made it's way into project with #193, binaries would be available through npm in the next few days (#136)
