### ISSUE TITLE
Use Scoop as package manager for Windows distribution

### ISSUE THREAD

**Issue by auchenberg** [google/ios-webkit-debug-proxy#194]
You could consider use [Scoop](http://scoop.sh/) for Windows distribution, as it's the equivalent of Homebrew but for Windows.

I have previously suggested to ship prebuilt binaries via NPM(https://github.com/google/ios-webkit-debug-proxy/issues/136), but I don't don't if this is possible for Mac and Unix? (to ship prebuilt binaries). Given this project know supports 3 platforms, it would only make sense to publish the prebuilt binaries for NPM if all platforms can be supported.

**Comment by artygus** [comment]
I'm not sure. Guys form mozilla/valence are using prebuilt binaries (https://github.com/mozilla/valence/tree/master/tools), however I have no idea if something could go wrong with numerous linux distros. What do you think?

**Comment by auchenberg** [comment]
Can we do both? Publish prebuilt binaries to NPM, and make releases to package managers (Scoop/Homebrew) too?

**Comment by artygus** [comment]
sure, shouldn't be a problem

**Comment by artygus** [comment]
opened pr in scoop repo lukesampson/scoop-extras#382

**Comment by auchenberg** [comment]
Yay!

Is the build build from this repo or https://github.com/artygus/ios-webkit-debug-proxy-win32? 

You could add the Windows binary to the release pages too for consistency

**Comment by artygus** [comment]
Nope, it's from this one. I thought to do so, but it's a bit confusing, because binary release depends on the versions of libimobildevice, libplist it's built with

**Comment by artygus** [comment]
scoop accepted PR
