### ISSUE TITLE
ios-webkit-debug-proxy not working for iOS 10.3.1

### ISSUE THREAD

**Issue by harjotcheema** [google/ios-webkit-debug-proxy#195]
OSX Version - Mac OS Sierra (10.12.4)
Xcode version - 8.3
Device - iPhone 6
Device OS version - iOS 10.3.1
Note: I have also enabled Web Inspector in the settings

Am getting the below error when trying to run ios_webkit_debug_proxy:
ios_webkit_debug_proxy -u **<udid of the device>**
Could not connect to lockdownd. Exiting.: Broken pipe
Unable to attach **<udid of the device>** inspector

Also when I run the below command:
ios_webkit_debug_proxy -c **<udid of the device>**:27753 -d
ss.add_fd(3)
ss.recv fd=3 len=976
ss.add_server_fd(4)
Could not connect to lockdownd. Exiting.: Broken pipe
ss.remove_server_fd(4)
Unable to attach **<udid of the device>** inspector

Can someone please help with this issue.

**Comment by artygus** [comment]
hi @harjotcheema please checkout troubleshooting section https://github.com/google/ios-webkit-debug-proxy#troubleshooting

**Comment by skumar1122** [comment]
I had same issue before , try this -
$brew upgrade libimobiledevice --HEAD
