### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by andydavies** [google/ios-webkit-debug-proxy#2]
When running  `examples/wdp_client.js` I'm cccasionally seeing Segmentation fault: 11 after Safari has loaded the page.

Not had a chance to dig in at any depth yet.

Test environment is iPad 2 running iOS 6.1

Running on OSX 10.8 build was using the formula @janl provided in https://github.com/google/ios-webkit-debug-proxy/issues/1#issuecomment-13546450

**Comment by artygus** [comment]
the issue is quite old now, if you still have the issue feel free to reopen
