### ISSUE TITLE
Updated DevTools UI can't inspect element styles

### ISSUE THREAD

**Issue by zwri** [google/ios-webkit-debug-proxy#20]
As noted by Umar (https://github.com/google/ios-webkit-debug-proxy/issues/12#issuecomment-18873188) and unbug (https://github.com/google/ios-webkit-debug-proxy/issues/19#issuecomment-18956398 ):

If you use "-f" to load a recent WebKit frontend inspector, e.g.:
  http://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html
the DevTools UI can't inspect element styles.

Safari's inspector was branched from WebKit and they've apparently diverged.  The likely fix is to patch the WebKit / Blink inspector JavaScript to restore Safari support.

**Comment by auchenberg** [comment]
Please see https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter, which should implement the newer API's that allow CSS inspection.

**Comment by artygus** [comment]
https://github.com/google/ios-webkit-debug-proxy#using-with-devtools
