### ISSUE TITLE
Inspect page hangs with iOS 10.3.1 on Windows 10

### ISSUE THREAD

**Issue by ghostoy** [google/ios-webkit-debug-proxy#201]
I tried to inspect pages on Safari on my iPad. The device list page on `9221` was good, and I can also get pages listed on `9222`, too. However when I try to inspect a single page, the browser hangs.

Version: 1.7.1 installed with `scoop`
Laptop: Windows 10 with Creators Update
iPad: iOS 10.3.1
Apple Mobile Device Service: version 3.3.0.0 x64 (part of iTunes installation)

**Comment by artygus** [comment]
hi @ghostoy, what do you mean hangs, does it stop to respond? do you see shield icon to the right of address bar?

**Comment by ghostoy** [comment]
Yes, it stops to respond. Browser stucks at the loading state.

**Comment by artygus** [comment]
does it also get stuck when you use external devtools, e.g. chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1

**Comment by ghostoy** [comment]
Sorry. It appears to be the issue of my cable. I tried to connect my iPad with another cable and it started to be working. So close this issue.
