### ISSUE TITLE
Video not playing on iPhone devices and simulator

### ISSUE THREAD

**Issue by Handsome2734** [google/ios-webkit-debug-proxy#202]
I want to play video automatically, by performing a click on play button.
Here are my commands: 
```
{"params": {"url": "http://m.youku.com/video/id_XMjczNDYzMzgxMg==.html"}, "id": 0, "method": "Page.navigate"}
{"params": {"expression": "document.evaluate('//div[@class=\"x-video-play-ico x-iconmode-new\"]', document.body, null, XPathResult.ANY_TYPE, null).iterateNext().click()"}, "id": 0, "method": "Runtime.evaluate"}
```
After sending these commands, video is stuck at the first frame.
But when I execute the script in chrome console, video can play just well.
Very appreciate for helping.

**Comment by Handsome2734** [comment]
Android Chrome 57.0.2987.132 has the same problem.
```
{"params": {"url": "https://m.youtube.com/watch?v=GOp02tHtCv4"}, "id": 0, "method": "Page.navigate"}
{"params": {"expression": "document.evaluate('//div[@class=\"_msi _mzf _mag _mct\"]', document, null, XPathResult.ANY_TYPE, null).iterateNext().click()"}, "id": 0, "method": "Runtime.evaluate"}
```
Video just got stuck, and loading circle and play button showed at same time.

**Comment by artygus** [comment]
@Handsome2734 probably the first click on the video has to be done via user interaction, otherwise it would be possible to implement autoplay on mobile device with javascript. I'm closing the question as it's not related to the utility functionality in any way

**Comment by artygus** [comment]
out of curiosity i checked if the scenario would work with muted video. If you set video to muted first with `document.getElementsByTagName('video')[0].muted = true` the subsequent call invoking click would make video play
