### ISSUE TITLE
The Content of the cookies are not shown

### ISSUE THREAD

**Issue by umutuzgur** [google/ios-webkit-debug-proxy#203]
When I click on the cookies section in the UI of ios webkit debug proxy, it only shows the list of the cookies that belongs to the domains but not the content of the cookies. I can see that when I use safari developer screen. Is this might be broken with ios webkit debug proxy?

**Comment by artygus** [comment]
hi @umutuzgur, please check out https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

> To use Chrome DevTools it's the recommendation to use the RemoteDebug/remotedebug-ios-webkit-adapter project, which has instructions on how to setup Chrome to remote debug iOS devices, much similar to Android debugging.
> 
> The reason is that recent versions of Chrome and Safari there're major discrepancies between Chrome Remote Debugging Protocol and Apple's Remote Web Inspector service, which means that newer versions of Chrome DevTools arne't compatible with Safari.
