### ISSUE TITLE
Unable to get webview of Hybrid application with ios_webkit_debug_proxy 1.7.1

### ISSUE THREAD

**Issue by ochubey** [google/ios-webkit-debug-proxy#207]
Unable to reach webview of the same app on real device, although it's reachable on Simulator.
> [{
   "deviceId": "SIMULATOR",
   "deviceName": "SIMULATOR",
   "url": "localhost:9222"
},{
   "deviceId": "censored :)",
   "deviceName": "DespoPhone",
   "url": "localhost:9223"
}]

When opening Simulator's URL http://127.0.0.1:9222/json I can see expected webview description:

> [{
   "devtoolsFrontendUrl": "/devtools/devtools.html?ws=localhost:9222/devtools/page/1",
   "faviconUrl": "",
   "thumbnailUrl": "censored :)",
   "title": "censored :)",
   "url": "censored :)",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/1",
   "appId": "PID:87095"
}]

When opening real device URL http://127.0.0.1:9223/json I get an empty response:
> []

Although with Safari opened on the same real device I get expected description:

> [{
   "devtoolsFrontendUrl": "/devtools/devtools.html?ws=localhost:9223/devtools/page/1",
   "faviconUrl": "",
   "thumbnailUrl": "/thumb/about:blank",
   "title": "",
   "url": "about:blank",
   "webSocketDebuggerUrl": "ws://localhost:9223/devtools/page/1",
   "appId": "PID:1017"
},{
   "devtoolsFrontendUrl": "/devtools/devtools.html?ws=localhost:9223/devtools/page/2",
   "faviconUrl": "",
   "thumbnailUrl": "/thumb/about:blank",
   "title": "",
   "url": "about:blank",
   "webSocketDebuggerUrl": "ws://localhost:9223/devtools/page/2",
   "appId": "PID:1018"
},{
   "devtoolsFrontendUrl": "/devtools/devtools.html?ws=localhost:9223/devtools/page/4",
   "faviconUrl": "",
   "thumbnailUrl": "/thumb/http://appium.io/",
   "title": "Appium: Mobile App Automation Made Awesome.",
   "url": "http://appium.io/",
   "webSocketDebuggerUrl": "ws://localhost:9223/devtools/page/4",
   "appId": "PID:1020"
}]

Version used:
ios_webkit_debug_proxy 1.7.1
Built with libimobiledevice v1.2.1, libplist v1.12
iOS: 10.3.2, 9.3
MacOS: Sierra 10.12.4

**Comment by artygus** [comment]
hi @ochubey there was a similar issue #190

**Comment by ochubey** [comment]
@artygus thank you for linking and closing.
My issue was resolved by changing provisioning profile type from AdHoc to Developer (there might be issues with debug flag in AdHoc profile.).

**Comment by skansar** [comment]
Hello @masoodmd0786/ @imurchie / @jlipps , I am facing the similar issue with Appium v1.7.2 and Java_client 4.1.2, IOS 10.3(iphone 7s), mac OS Sierra, XCODE 9.2, ios_webkit_debug_proxy 1.8
Built with libimobiledevice v1.2.1, libplist v2.0.0 and safari 11.2.

WebViews are not recognized / shown with appium desktop as well through java client.

appium server
appium --webkit-debug-proxy-port 9222 (tried with OR 27753)
[Appium] Welcome to Appium v1.7.2
[Appium] Non-default server args:
[Appium] webkitDebugProxyPort: 9222 (OR 27753)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

wda
ios_webkit_debug_proxy
Listing devices on :9221 (OR 27753)
Connected :9222 to iPhone (470ab1f19c630548f76ed0b2f8a4a31614b2c847)

capabilities:
[Appium] Creating new XCUITestDriver (v2.64.0) session
[Appium] Capabilities:
[Appium] app: com.amazon.AmazonUK.Enterprise
[Appium] newCommandTimeout: 380
[Appium] platformVersion: 10.3
[Appium] xcodeOrgId: 94KV3E626L
[Appium] automationName: XCUITest
[Appium] autoWebview: false
[Appium] platformName: iOS
[Appium] udid: 470ab1f19c630548f76ed0b2f8a4a31614b2c847
[Appium] deviceName: IOSDevice
[Appium] xcodeSigningId: iPhone Developer

appium Log:
[debug] [MJSONWP] Calling AppiumDriver.getContexts() with args: ["e5be6ced-f4ac-4e21-8618-d97e1d9991c2"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [iOS] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[debug] [RemoteDebugger] Page element JSON: []
[debug] [iOS] No web frames found.
[debug] [MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP"]

Any help appreciated. Thank You.

**Comment by ochubey** [comment]
@skansar - are you sure that mobile Safari has Web Inspector enabled and you, for example, can debug some page opened in mobile Safari from desktop Safari?
In addition - it's probably better to open separate issue ;)

**Comment by artygus** [comment]
@skansar can you confirm your app is probably signed? (with dev provisioning profile) also does safari show the app webviews? there were many similar posting as far as I can see, most of them were related to improper signing

**Comment by Warren25** [comment]
Hi, I am having the issue of not being able to view a webview INSIDE the native app that I am testing for the client. I have thoroughly read this ticket, #229, #223, and #190. 

My question is simply this, is viewing a webview within a app possible? Or was the iwdp tool only to view webviews within mobile browsers?

If this is possible, can someone please post screenshots of this is supposed to look like?

Thank you kindly.
