### ISSUE TITLE
The tool doesn't work with ios 11

### ISSUE THREAD

**Issue by ViktorGal** [google/ios-webkit-debug-proxy#208]
After 

....bplist00..._
..WIRFinalMessageKeyO..
bplist00.....Z
__selector_.._rpc_reportIdentifier:Z
__argument..._..WIRConnectionIdentifierKey
_.#6977420-6980-418f- b735-51a3692d2806 .1<?\

message sent.
Device closes connection.

**Comment by ViktorGal** [comment]
When connecting the device to El Capitan. Safari also cannot see the device.

**Comment by artygus** [comment]
If safari can not see the device iwdp won't be able to see it either

**Comment by ViktorGal** [comment]
Can not see on EL Capital. On Sierra it should work. I didn't upgrade my mini mac yet.

**Comment by artygus** [comment]
I'm on El Captain and I'm able to see the devices. If you start simulator does safari pick it?

**Comment by ViktorGal** [comment]
You are able to see ios11 devices? I'm talking about ios11. On Sierra the device with ios11 appear in develop tab of safari for a 1 second and disappear.

**Comment by ViktorGal** [comment]
I don't know how to run ios11 simulator. Maybe I need Xcode 9.

**Comment by artygus** [comment]
@ViktorGal oh I see now, didn't notice ios11 in issue's tittle, I didn't upgrade to Sierra just yet, will do later this week. I'll let you know if I have any progress

**Comment by ViktorGal** [comment]
Thanks @artygus. Need to upgrade to High Sierra beta for ios 11.

**Comment by tobsch** [comment]
Newest chrome preview works with ios 11, even in sierra. The proxy does not though.

**Comment by artygus** [comment]
@tobsch do you mean that default dev tools front-end doesn't work?

**Comment by tobsch** [comment]
yep! it only works with the newest safari preview

**Comment by artygus** [comment]
Default dev tools url is super old, but even latest dev tools are quite useless because safari/chrome protocols are quite different now, I'd recommend using adapter. You can find some info in readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

**Comment by artygus** [comment]
On El Captain call to libimobiledevice method `lockdownd_client_new_with_handshake` fails with `LOCKDOWN_E_MUX_ERROR`, probably related to protocol changes. Found some info https://github.com/libimobiledevice/libimobiledevice/issues/510

**Comment by VasilijSviridov** [comment]
@artygus how you apply patch ?

**Comment by artygus** [comment]
Latest stable Safari on Sierra gives the same result, device appears and disappears in a moment. The tool also reports disconnect with applied patch to libimobiledevice I mentioned above .

**Comment by nadavva** [comment]
We tried to run compile the code over ios11-supporting-libimobiledevice (== the device is identifies and the commands are working) and ios-webkit-debug-proxy still failing...

**Comment by AnuKadloor** [comment]
I am getting the below error while executing the below command on iOS 11 Beta device with XCode 8.3.3.
$ ios_webkit_debug_proxy -c <decideId>:27753 -d

Error:
Could not connect to lockdownd. Exiting.: Undefined error: 0
Unable to attach inspector

Can any one please help in this regard. 
Thanks !!

**Comment by AnuKadloor** [comment]
I was able to resolve the issue by cloning the libimobiledevice project from GitHub and then implementing the patch mentioned in below URL:-
https://gist.github.com/nikias/b351bf633d62703e0ff4f2fee9628401

**Comment by AnuKadloor** [comment]
@artygus 
On executing ios-debug-webkit-proxy on MAC Siera terminal, my iphone 6 (iOS 11 beta 2) is listed when I go to localhost:9221 in my browser; however it does not display any pages under the 'Inspectable pages for iPhone:' section.
I suspect due to this, appium is unable to switch to webview context of my app.
Can you let me know if this is an issue or am I missing some configuration?

ios-debug-webkit-proxy version: 1.7.1
Built with libimobiledevice v1.2.1, libplist v1.12

**Comment by artygus** [comment]
hi @AnuKadloor at this point utility doesn't support iOS 11. Even latest Safari on Sierra doesn't allow you to inspect pages of iOS 11 devices. However, on High Sierra I was able to inspect devices with iOS 11. I suspect there're certain changes in usbmuxd protocol, the issue need further investigation.

**Comment by AnuKadloor** [comment]
Thanks for the quick reply @artygus 
Any idea by when we can expect a fix for this?

PS: I'm able to inspect pages of iOS 11 devices on my Mac Sierra 10.12.6 with Safari 11.0

**Comment by artygus** [comment]
oh cool, Safari 11 Beta was only available on Sierra, look's stable works even on El Captain. I can't make any promises, but any help in investigation would be greatly appreciated 🙂

**Comment by AnuKadloor** [comment]
👍 
I can try and help 🙂
Hopefully we'll get a fix for this ASAP!
Will update here if I come across anything else.

**Comment by AnuKadloor** [comment]
Hey...any updates on this issue?

**Comment by artygus** [comment]
@AnuKadloor yes, looks like ios 11 doesn't support partial plist's, I'm thinking about workaround atm

**Comment by fabianaapateanu** [comment]
Hei guys, any updates on this issue? Many thanks!

**Comment by artygus** [comment]
@AnuKadloor @fabianaapateanu please check out the [ios11_support](https://github.com/google/ios-webkit-debug-proxy/tree/ios11_support) branch. You still need to apply patch to libimobiledevice or device handshake would fail, see comment [above](https://github.com/google/ios-webkit-debug-proxy/issues/208#issuecomment-309710128) for details

**Comment by AnuKadloor** [comment]
Thanks for the fix @artygus.

**Comment by mayureshshirodkar** [comment]
@artygus i installed the branch you created for the iOS 11 fix and it seems to be working fine.
By when can we expect the patch, on the main branch ?

**Comment by artygus** [comment]
@mayureshshirodkar I've just merged the branch to master, I think I'll keep the issue open until https://github.com/libimobiledevice/libimobiledevice/issues/510 is resolved

**Comment by fabianaapateanu** [comment]
@artygus I will test tomorrow, I just received a Macbook and iPhone on which I can install all the betas :) will come back with feedback. thanks!

**Comment by artygus** [comment]
pairing patch made it's way into libimobiledevice's master libimobiledevice/libimobiledevice@5a85432719fb3d18027d528f87d2a44b76fd3e12

**Comment by Vadim-Kovrizhkin** [comment]
brew update
brew reinstall --HEAD libimobiledevice
brew reinstall -s ios-webkit-debug-proxy

resolved issue for me

**Comment by mirza-ae** [comment]
I agree with @Vadim-Kovrizhkin. I followed his steps, and it worked.
