### ISSUE TITLE
How to use libimobiledevice 1.2.1 or newer on Windows

### ISSUE THREAD

**Issue by imReker** [google/ios-webkit-debug-proxy#209]
I can't find any notes tell the version of libimobiledevice used in Windows build.
I tried replacing the libimobiledevice.dll with the lastest release of https://github.com/libimobiledevice-win32/libimobiledevice but get crash.

**Comment by artygus** [comment]
hi @imReker it's build with 1.2.1 libimobiledevice/libimobiledevice@1d844aae, you can find version of libraries iwdp depends on in binary archive which currently located on [sourceforge](https://downloads.sourceforge.net/project/ios-webkit-debug-proxy-win32/v1.7.1/ios-webkit-debug-proxy-1.7.1-x64-bin.zip)
