### ISSUE TITLE
Cannot use it on chrome version 58.0.3029.96 (64-bit)???

### ISSUE THREAD

**Issue by lixiaodong** [google/ios-webkit-debug-proxy#210]
1.chrome version 58.0.3029.96 (64-bit)
2.windows 10

I truly appreciate you to develop this tool.but i cannot use it on chrome 58.0.3029.96

![image](https://user-images.githubusercontent.com/1568575/27273527-fbad60e8-5501-11e7-8d7d-ff471b4fb1dd.png)

**Comment by artygus** [comment]
hi @lixiaodong, what issues exactly are you facing?

**Comment by artygus** [comment]
i guess it's dup of #211
