### ISSUE TITLE
Not able to debug in Chrome Version 58.0.3029.110 (64-bit) MAC OS

### ISSUE THREAD

**Issue by alivepool** [google/ios-webkit-debug-proxy#211]
Chrome Version 58.0.3029.110 (64-bit) MAC OS, I am not able to debug.
I am able to see the sources in chrome but the debugger is not hitting the breakpoints as the passing of debug points info seems to have broken.

Getting following error(using --debug):
.~..{"error":{"code ":-32601,"message": "'Debugger.getPossibleBreakpoints' was not found","data": [{"code":-32601,"message":"'Debugger.g etPossibleBreakpoints' was not found"} ]},"id":28}

Seems to be protocol breakage??

**Comment by artygus** [comment]
hi @alivepool, exactly 😞 , please take a look at https://github.com/google/ios-webkit-debug-proxy#using-with-devtools
