### ISSUE TITLE
iOS 11 :: Could not connect to lockdownd. Exiting.: Undefined error: 0

### ISSUE THREAD

**Issue by mansis1516** [google/ios-webkit-debug-proxy#212]
I am getting the below error while executing the below command on iOS 11 Beta device with XCode 9 Beta.
$ ios_webkit_debug_proxy -c <UDID>:27753 -d

Error:
Could not connect to lockdownd. Exiting.: Undefined error: 0
Unable to attach <UDID> inspector

Can any one please help in this regard. Thanks !!

**Comment by artygus** [comment]
hi @mansis1516 the issue related to libimobiledevice, please see https://github.com/google/ios-webkit-debug-proxy/issues/208#issuecomment-309710128

**Comment by AnuKadloor** [comment]
Hi @mansis1516 were you able to resolve the issue?
I'm also facing the same issue on iOS 11.
None of the libimobiledevice commands are working.
I tried updating it from HEAD but I'm still facing this error.

**Comment by AnuKadloor** [comment]
I was able to resolve the issue by cloning the libimobiledevice project from GitHub and then implementing the patch mentioned in below URL:-
https://gist.github.com/nikias/b351bf633d62703e0ff4f2fee9628401
