### ISSUE TITLE
Problem installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by Alleno** [google/ios-webkit-debug-proxy#214]
I'm having trouble installing this on Ubuntu 16.04 following the instructions. I'm getting the following error:

No package 'libimobiledevice-1.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libimobiledevice_CFLAGS
and libimobiledevice_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by artygus** [comment]
hi @Alleno can you confirm you have libimobiledevice package installed?

**Comment by Alleno** [comment]
I apparently have libimobiledevice6 installed (it shows as installed in ubuntu software center). I also tried installing from here: https://github.com/libimobiledevice/libimobiledevice, but I get the following error:

...
checking consistency of all components of python development environment... no
configure: error: 
  Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LDFLAGS environment variable.
  Example: ./configure LDFLAGS="-L/usr/non-standard-path/python/lib"
  ============================================================================
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================

I do have python installed:
allen@Allen-Linux:~/src/libimobiledevice$ which python
/home/allen/anaconda3/bin/python

**Comment by artygus** [comment]
you could try try configure with `--without-cython` flag

**Comment by belozer** [comment]
Problem actual. How fix this problem?

**Comment by artygus** [comment]
remove libimobiledevice packages and build it from sources
