### ISSUE TITLE
iPhone with iOS 10 doesn't recognize

### ISSUE THREAD

**Issue by laurennlam** [google/ios-webkit-debug-proxy#215]
I tried to link my iPhone 7 (with iOS 10.3) to the firefix WebIDE in order to debug a website. Unfortunately, it seems that valence doesn't manage to connect to it. Firefox WebIDE doesn't  doesn't display the device. Contrary to the device with iOS 9.1 which works.
Here are the configurations :
- Windows 7
- Connected iPhone : iOS 10.3
- ios-webkit-debug-proxy.Exe comes from [sourceforge ](https://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/v1.7.1/)
- Firefox 54.0.1

Here is the browser Console of Firefox :

> valence:ios-webkit-debug-proxy.exe: Could not connect to lockdownd. Exiting.  ios-proxy.js:137
> valence:ios-webkit-debug-proxy.exe: : No error ios-proxy.js:137
> Connection status changed: disconnecting  app-manager.js:158
> Connection status changed: disconnected  app-manager.js:158
> A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
> See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise
> 
> Date: Wed Aug 02 2017 16:07:05 GMT+0200
> Full Message: connectionClosed
> Full Stack: JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: register :: line 199
> JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: completePromise :: line 711
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/client/webide/modules/tab-store.js :: listTabs/< :: line 104
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: DebuggerClient.requester/</< :: line 283
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js :: exports.makeInfallible/< :: line 101
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js :: emitOnObject :: line 112
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js :: emit :: line 89
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: emit :: line 1322
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: reject :: line 1145
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: purgeRequests/< :: line 1166
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: purgeRequests :: line 1166
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: onClosed :: line 1100
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/transport/transport.js :: close :: line 668
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/transport/transport.js :: close :: line 664
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/transport/transport.js :: close :: line 664
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: cleanup :: line 371
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: detachClients :: line 395
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: close :: line 404
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/connection-manager.js :: disconnect :: line 260
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/client/webide/modules/tab-store.js :: listTabs/< :: line 103
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: DebuggerClient.requester/</< :: line 283
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js :: exports.makeInfallible/< :: line 101
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js :: emitOnObject :: line 112
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js :: emit :: line 89
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: emit :: line 1322
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: emitReply :: line 1021
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/platform/chrome/stack.js :: callFunctionWithAsyncStack :: line 69
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js :: onPacket :: line 1023
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/transport/transport.js :: send/< :: line 570
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js :: exports.makeInfallible/< :: line 101
> JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js :: exports.makeInfallible/< :: line 101
JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js :: exports.makeInfallible/< :: line 101

Does anyone have an idea of what's wrong ?

**Comment by artygus** [comment]
are you certain that valence ships latest binaries? latest commit (https://github.com/mozilla/valence) is made on Jan 27 or did you update iwdp binary manually? anyways, what does ios-webkit-debug-proxy -V show?

**Comment by laurennlam** [comment]
I think that the valence is automatically installed when the latest version of firefox is installed. I think it ships latest binaries automatically, doesn't it ?

ios-webkit-debug-proxy -V shows:

> $ ios_webkit_debug_proxy.exe -V
> c:\Users\laula_000\Downloads\ios-webkit-debug-proxy-win64 (1)\ios-webkit-debug-proxy-win32\ios_webkit_debug_proxy.exe: unknown option -- V
> Usage: c:\Users\laula_000\Downloads\ios-webkit-debug-proxy-win64 (1)\ios-webkit-debug-proxy-win32\ios_webkit_debug_proxy.exe [OPTIONS]
> iOS WebKit Remote Debugging Protocol Proxy.

> By default, the proxy will list all attached iOS devices on:
>   http://localhost:9221
> and assign each device an incremented port number, e.g.:
>   http://localhost:9222
> which lists the device's pages and provides inspector access.

> Your attached iOS device(s) must have the inspector enabled via:
>   Settings > Safari > Advanced > Web Inspector = ON
> and have one or more open browser pages.

> To view the DevTools UI, either use the above links (which use the "frontend"
> URL noted below) or use Chrome's built-in inspector, e.g.:
>   chrome-devtools://devtools/bundled/devtools.html?host=localhost:9222&page=1


I'm a beginner in web and I'm not sure to understand how it works. But does it mean that the device needs to be connected on port 9221 ? For example http://x.x.x.x/9221 ?

**Comment by artygus** [comment]
@laurennlam  unofrtunately binaries are outdated, v. 1.7.1 supports -V flag, to make things work you could replace everything in c:\Users\laula_000\Downloads\ios-webkit-debug-proxy-win64 (1)\ios-webkit-debug-proxy-win32\ios_webkit_debug_proxy.exe with files extracted from https://sourceforge.net/projects/ios-webkit-debug-proxy-win32/files/v1.7.1/

**Comment by laurennlam** [comment]
@artygus , it's the link I used to download and unzip the current ios-webkit-debug-proxy :/

**Comment by artygus** [comment]
disregard previous message, I thought patch you specified is valence path to binaries.
I just double-cheked bianries at sf, and it certainly 1.7.1 and it supports "-V" flag. Could you please re-downlaod it from [this](https://downloads.sourceforge.net/project/ios-webkit-debug-proxy-win32/v1.7.1/ios-webkit-debug-proxy-1.7.1-x64-bin.zip) link

**Comment by laurennlam** [comment]
Thanks, this version seems better. Here is what it's display when I launched the executable with "-V" option:
>$ ios_webkit_debug_proxy.exe -V
>ios_webkit_debug_proxy 1.7.1
>Built with libimobiledevice v1.2.1, libplist v1.13.0

**Comment by artygus** [comment]
okay, now you need to place the contents of that folder to the place where valence keeps win iwdp binaries

**Comment by laurennlam** [comment]
That something I didn't know.
As I understand, Valence is an add-on of firefox. I checked and I have the 0.3.7 version. But how do you know where valence keeps win iwdp binaries ?

**Comment by laurennlam** [comment]
@artygus  I tried by launching the ios-webkit-debug-proxy.exe (without moving it as you advised) then, open Firefox WebIDE and instead of choosing "Safari, Firefox, and other..." I chose "chrome Desktop" and it works... I don't know why. I followed this tutorial : http://syntaxwarriors.com/p/17/Debug-Safari-on-iOS-using-Windows-10-and-Firefox
I hope it will continue to work.
Thank you very much for your help !

**Comment by artygus** [comment]
I'm sorry I'm not aware of how firefox manages it's plugins, etc. Anyways, glad you managed to work it out, I think it works because iwdp exposes first founds device to 9222 and Firefox WebIDE expects chrome desktop also on 9222 (at least from docs https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Chrome_Desktop)
