### ISSUE TITLE
Doesn't accept environment variables in a shell.

### ISSUE THREAD

**Issue by NOTtheMessiah** [google/ios-webkit-debug-proxy#216]
I try to write `UDID=694f5320697320612050495441 ios_webkit_debug_proxy -c $UDID:27753 -d` and it fails. Output:

```
ss.add_server_fd(3)
Listing devices on :27753
ss.add_fd(4)
Unable to bind SIMULATOR on port 27753-27753
ss.recv fd=4 len=294
ss.recv fd=4 len=684
Unable to bind 694f5320697320612050495441 on port 27753-27753
^Css.remove_server_fd(3)
ss.remove_fd(4)
```

I was able to circumvent the error for now by making command string before evaluating it.

    eval "ios_webkit_debug_proxy -c $UDID:27753 -d"

Output of `bash --version`:

_GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)_

**Comment by artygus** [comment]
it's you shell that works this way, it's not related to utility implementation
