### ISSUE TITLE
Could not connect to lockdownd. Exiting.: Permission denied

### ISSUE THREAD

**Issue by gg4u** [google/ios-webkit-debug-proxy#218]
How to solve permission denied?
iOS ProductVersion: 10.2.1
OSX version: 10.9.5
Itunes version : last updated (had to do it otherwise iPhone would not "trust" my computer :/ 

Cannot  debug a web app with safari 7.1 : safari console crash for debugging pages on device...
Jeeeez soo bad..

Maybe iOS-webkit could help, but I cannot see this Permission denied amiong the solved problems... any suggestion?

**Comment by artygus** [comment]
what does `ios-webkit-debug-proxy -V` show?

**Comment by gg4u** [comment]
I wish I knew ... I was upgrading the phone to phone 10.3.3 and does not start anymore.

**Comment by gg4u** [comment]
Ok, back again:

ios_webkit_debug_proxy -V

ios_webkit_debug_proxy 1.7.1
Built with libimobiledevice v1.2.0, libplist v2.0.0

**Comment by artygus** [comment]
you need to rebuild libimobiledevice

    brew update
    brew reinstall --HEAD libimobiledevice
    brew reinstall -s ios-webkit-debug-proxy

**Comment by gg4u** [comment]
👍

**Comment by MemoryReload** [comment]
@artygus   save my ass! 👍

**Comment by aaronmagi** [comment]
@artygus   How often is a rebuild required? Any time you are interacting to a phone with a different OS than before?

What happens when you have multiple real devices setup for testing and your swapping them in and out?

Thank you

**Comment by artygus** [comment]
hi @aaronmagi only once
