### ISSUE TITLE
Console stays blank and won't send commands

### ISSUE THREAD

**Issue by auguster** [google/ios-webkit-debug-proxy#219]
Hello World,

I was able to connect successfully from a Debian 9 running Chromium version 60.0.3112.78 (Developer Build) to a Iphone 6 running iOS 10.3.3. I had to rebuild libimobiledevice in order to connect to the device.

I'm running `ios_webkit_debug_proxy -f chrome-devtools://devtools/bundled/inspector.html`
On chromium I'm connection through: `chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1`

In the inspector I can correctly view the element, source, css, application, network... The console however stays blank (despite the numerous console.log I used in the index.html). The console is also unable to send command. It looks like the enter key doesn't validate the command. I can't seem to be able to add breakpoints either. If I press F5 in the network tab the page does refresh on the device.

I'm not sure on what do try... Anyway, I'm glad to be able to have some debug info from Linux ;-)

Best regards,

**Comment by auguster** [comment]
I was able to have full debug using [artygus/webkit-webinspector](https://github.com/artygus/webkit-webinspector) or [RemoteDebug/remotedebug-ios-webkit-adapter](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter).

The later even displayed the devices screen !

**Comment by rgdevx** [comment]
I had the same issue when using remotedebug-ios-webkit-adapter and Chromium DevTools. The console was blank.
It started working after I checked "preserve logs" in the console settings (gear icon in the top right). It was clearing them automatically after they had been outputted.

Now I need to clear the logs manually, but at least I can see the logs.
