### ISSUE TITLE
v1.8 not available from scoop on Windows (latest is v1.7.1)

### ISSUE THREAD

**Issue by KnuX** [google/ios-webkit-debug-proxy#221]
Hi,

I installed it using an updated scoop on Windows but i got the 1.7.1 version. I don't know where to find the patched libimobiledevice.dll to use it with iOS 11 beta 5.

Do I need to build it from source?

**Comment by Symbianx** [comment]
I'm having the same problem. Installed from scoop and got the 1.7.1 version.

**Comment by artygus** [comment]
Hi @KnuX, PR was sent lukesampson/scoop-extras#560 to scoop repo

**Comment by artygus** [comment]
PR was meged in, should be available now
