### ISSUE TITLE
Chrome supports direct USB connection?

### ISSUE THREAD

**Issue by strarsis** [google/ios-webkit-debug-proxy#222]
I just noticed that Chrome in Windows supports direct USB connection to an iPhone device.
It seems to work - though there seem to be missing functionality though, 
like being unable to manipulate the styles and elements in DOM tree aren't highlighted on the device.

**Comment by auchenberg** [comment]
@strarsis Do you have any links documenting this?

**Comment by strarsis** [comment]
I will look for a good one.

Prerequisites:
1. (Latest) iTunes installed.
2. iPhone connected via USB.
3. Connection on iPhone allowed.
4. Safari Debug on iPhone enabled.

1. Open new window in Chrome, normal browser mode, _not_ in Incognito mode.
2. Navigate to chrome://inspect/#devices
3. [x] Discover USB devices
[x] Discover network targets (haven't tried it out yet - iTunes sync over WiFi option?)
4. Sometimes it helps to trigger a refresh by selecting 'Port forwarding...' and closing the dialog again.
5. Under 'Remote Target' there should be now Safari tabs listed.
Selecting one of these opens a new inspector window.

**Comment by auchenberg** [comment]
@strarsis Are you sure that you don't have `Discover network targets` enabled and an instance of `ios-webkit-debug-proxy` running?

I haven't seen any commits in Chromium that should enable this, so that would surprise me.

**Comment by freimuth82** [comment]
I tried to check this and with a fresh start from Windows 10 with the latest Chrome version (63.x) without starting any powershell and there are no devices listed. Starting ios-webkit-debug-proxy does list then as expected, so I think, there was another instance running already.

**Comment by artygus** [comment]
I think the issue can be closed
