### ISSUE TITLE
GnuTLS error: Error in the pull function. Could not connect to lockdownd. Exiting.: Broken pipe

### ISSUE THREAD

**Issue by tomeraz** [google/ios-webkit-debug-proxy#223]
Following the setup instructions, getting:
```
Listing devices on :9221
GnuTLS error: Error in the pull function.
Could not connect to lockdownd. Exiting.: Broken pipe
Unable to attach c322f** inspector

```
I've followed all troubleshooting and google advices.
Running Ubuntu 16.04
Trying to connect to iphone 5, ios 10.3.1

Any ideas?
Thanks!

**Comment by artygus** [comment]
ho @tomeraz, did try check the #166 thread?

**Comment by tomeraz** [comment]
This made it work, Thanks!
https://github.com/google/ios-webkit-debug-proxy/issues/166#issuecomment-302559880
