### ISSUE TITLE
Can real device be inspect?

### ISSUE THREAD

**Issue by jzzj** [google/ios-webkit-debug-proxy#224]
I'm wondering if a real device can be inspect?

**Comment by artygus** [comment]
hi @jzzj yes, of course, checkout the readme

**Comment by jzzj** [comment]
Sorry, I did not make it clear, I'm mean: Can I inspect uiwebview element in some app (not in safari)?

**Comment by artygus** [comment]
you can inspect webview in debug mode of your own app, there were a couple of related issues #207 #190

**Comment by jzzj** [comment]
Appreciated!
