### ISSUE TITLE
Can not work in iOS 11

### ISSUE THREAD

**Issue by huyjack178** [google/ios-webkit-debug-proxy#225]
I got problem when using this tool after update my iphone to iOS 11. Anyone please help

`Listing devices on :9221
Could not connect to lockdownd. Exiting.: No error
Unable to attach f8c28baaa4b74d344629b4e41f1096d81ba5d6fe inspector`

**Comment by artygus** [comment]
what does `ios_webkit_debug_proxy -V` show?

**Comment by artygus** [comment]
most likely you need to update libimobiledevice

    brew update
    brew reinstall --HEAD libimobiledevice
    brew reinstall -s ios-webkit-debug-proxy

if you're on OSX

**Comment by rong4188** [comment]
Hi, I got the exact same problem in iOS11, is there any solution yet?

**Comment by artygus** [comment]
similar issues #226 #208 suggest the problem fixed
