### ISSUE TITLE
Unable to connect to XXX

### ISSUE THREAD

**Issue by mitulgohel** [google/ios-webkit-debug-proxy#226]
I am trying to run ios-webkit-debug-proxy on iOS11 iPad Pro 9.7" and I am getting "Unable to connect to XXX Please verify that Settings > Safari > Advanced > Web Inspector = ON"

I updated libimobiledevice using - `brew reinstall --HEAD libimobiledevice ` also updated ios-webkit-debug-proxy using - `brew reinstall --HEAD ios-webkit-debug-proxy `.

I make sure that Settings > Safari > Advanced > Web Inspector is set to ON.

I tried to restart the device, Tried to uninstall and reinstall libimobiledevice and ios-webkit-debug-proxy but I am getting same error.

Can someone please help with this issue?

**Comment by artygus** [comment]
hi @mitulgohel just in case did you verifies that "Web Inspector is ON in settings"?
what does `ios-webkit-debug-proxy -V` show?

**Comment by mitulgohel** [comment]
Hi @artygus yes I did verify that "Web Inspector is ON in settings".

`ios-webkit-debug-proxy -V ` gives me `ios_webkit_debug_proxy 1.7.1` and `Built with libimobiledevice v1.2.1, libplist v2.0.0`

**Comment by artygus** [comment]
hm, are you certain you have no other linked ios-webkit-debug-proxy installs? it must be 1.8.0

**Comment by mitulgohel** [comment]
omg that was the issue. Thanks a lot! @artygus

**Comment by sumitgos** [comment]
how can I check hm, are you certain you have no other linked ios-webkit-debug-proxy installs?" 
np other linked toinked ios-webkit-debug-proxy and how can I remove this ? please solve this issue

**Comment by sumitgos** [comment]
> omg that was the issue. Thanks a lot! @artygus
how can I check hm, are you certain you have no other linked ios-webkit-debug-proxy installs?" 
np other linked toinked ios-webkit-debug-proxy and how can I remove this ? please solve this issue

**Comment by sumitgos** [comment]
> hm, are you certain you have no other linked ios-webkit-debug-proxy installs? it must be 1.8.0
how can I check hm, are you certain you have no other linked ios-webkit-debug-proxy installs?" 
np other linked toinked ios-webkit-debug-proxy and how can I remove this ? please solve this issue

**Comment by sumitgos** [comment]
Now resolve  issue. Thanks
