### ISSUE TITLE
can't inspect pages in chrome, ubuntu 16.04.3

### ISSUE THREAD

**Issue by yushans** [google/ios-webkit-debug-proxy#228]
Hi,
ios-webkit-debug-proxy runs on terminal successfully, and I can see pages list opened in safari at localhost:9222.
However, when I click the page, url is like: 'http://localhost:9222/devtools/devtools.html?ws=localhost:9222/devtools/page/1', it will fail to load.
I check the terminal console, and it said 
'sendq retry failed: Connection timed out
recv failed: Bad file descriptor'

Does anyone have an idea of what's wrong ? Thank you.

**Comment by artygus** [comment]
Hi @yushans, thanks for the report. I'll look into the issue. In the meantime you could use chrome built-in frontend tools, chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1. For better debugging experience I recommend using other frontends, check out DevTools section of the readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

**Comment by yushans** [comment]
@artygus thanks for the suggestion.
'chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1' loads successfully, but I still can't debug the code through the source tab in chrome devtools.
 It seems that the tool only shows the static pages and files, and there is no real connection between them. Hence the breakpoints doesn't work.

**Comment by artygus** [comment]
you won't be able to do it with barebone chrome devtools frontend, please refer to  https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

**Comment by yushans** [comment]
In fact I had installed remotedebug-ios-webkit-adapter when I tried to debug, do you mean that the url, ''chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1'', can only check the static page?

**Comment by artygus** [comment]
with every chrome version it can do less and less, I don't know what's left from compatibility between and chrome and safari dev tools protocols. imho you can get the best debugging experience from webkit webinspector

**Comment by artygus** [comment]
closing the issue as it's related to dev tools frontend, not to proxy itself
