### ISSUE TITLE
Could not connect to lockdownd. Exiting.: Operation now in progress

### ISSUE THREAD

**Issue by xiangxn** [google/ios-webkit-debug-proxy#231]
- Could not connect to lockdownd. Exiting.: Operation now in progress
environment:
ubuntu 16.04
ios_webkit_debug_proxy 1.8
Built with libimobiledevice v1.2.0, libplist v1.12
IOS 11

**Comment by artygus** [comment]
brew update
brew reinstall --HEAD libimobiledevice
brew reinstall -s ios-webkit-debug-proxy

**Comment by artygus** [comment]
oh, you're on linux, just build libimobiledevice from master (if you have any libimobiledevice dev packages please remove them)

**Comment by LeFredd** [comment]
Don't work for me :(

**Comment by artygus** [comment]
hi @LeFredd  what exactly?

**Comment by LeFredd** [comment]
Sorry ;)
https://github.com/google/ios-webkit-debug-proxy/issues/239

**Comment by bserem** [comment]
I am having the same issue:

```
[bserem@travis ios-webkit-debug-proxy:master]$ idevice_id -l
928d14fb5eaf69f9619f333a42c57406c1c0e6b9
```
```
[bserem@travis ios-webkit-debug-proxy:master]$ ios_webkit_debug_proxy -V
ios_webkit_debug_proxy 1.8
Built with libimobiledevice v1.2.1, libplist v2.0.0
```
```
[bserem@travis ios-webkit-debug-proxy:master]$ ios_webkit_debug_proxy 
Listing devices on :9221
Could not connect to lockdownd. Exiting.: Operation now in progress
Unable to attach 928d14fb5eaf69f9619f333a42c57406c1c0e6b9 inspector
```

I tried building libimobiledevice both from debian repositories (v1.2.0), from github with and without openssl.

Any ideas?

**Comment by artygus** [comment]
hi @bserem checkout closed issues, there were a couple of advices that helped, you certainly need to leave only one build of libimobiledevices from github sources

**Comment by bserem** [comment]
Sure, I'll give it another go.
