### ISSUE TITLE
i can`t edit css style in chrome develop tool element tab window 

### ISSUE THREAD

**Issue by sqqlyd** [google/ios-webkit-debug-proxy#234]
hello team,

i can used the ios-webkit-debug-proxy to detect  my ipad webview app and watched my app source code.
but i can't edit the css style code  in chrome develop tool element tab window . the window's css style code area background color is light gray . readonly ???
and  i set the breakpoint in debug target js  code file then the point appeared in a named VM ***.js file, but it not work, can't debug. 

### my env:
*********************
- window 7 64bit.
- iTunes Version:  12.6.3.6
- Chrome Version: 61.0.3163.79（Official Build） （64 bit）
*********************

### my opt step is follow:
*********************
- 1.i connected my ipad to my pc.
- 2.truct my pc in ipad.
- 3.start the ios-webkit-debug-proxy with follow command
    `ios_webkit_debug_proxy.exe  -f chrome-devtools://devtools/bundled/inspector.html`
- 4.open the webview app in ipad.
- 5.open the url localhost:9221 in Chrome and choose my device in device list by device name.
- ６.in by5. opened page( localhost:9222 ) ,i opened my app`s enter page in chrome develop tool page.
- 7.i wan to edit my css code to change my page style a little.but it can't be edit like up said.
         js file can't debug also.
*********************

Please help!

**Comment by artygus** [comment]
hi @sqqlyd please refer to [Using with DevTools](https://github.com/google/ios-webkit-debug-proxy#using-with-devtools) section of readme
