### ISSUE TITLE
Can't connect with iOS 11

### ISSUE THREAD

**Issue by akuma8** [google/ios-webkit-debug-proxy#235]
Hi,
I would like to connect my iPhone 6, iOS 11.0.3, on Windows 10, with Firefox WebIDE.
I can pair the phone with libimobiledevice :
`>idevicepair.exe pair`
Resutl `SUCCESS: Paired with device f0c3a71812598b62c9a8a83fce81ed63800225b6`
But when I run : `>ios_webkit_debug_proxy.exe --debug`
I got this :
ss.add_server_fd(408)
Listing devices on :9221
ss.add_fd(564)
ss.add_server_fd(128)
ss.remove_server_fd(128)
ss.recv fd=564 len=912
ss.add_server_fd(128)
Could not connect to lockdownd. Exiting.: No error
ss.remove_server_fd(128)
Unable to attach f0c3a71812598b62c9a8a83fce81ed63800225b6 inspector

Note : I already enabled Web Inspector on Safari
Any help will be appreciate.
Thanks

**Comment by artygus** [comment]
hi @akuma8, I believe firefox web ide uses outdated version of ios-webkit-debug-proxy, you need to replace binaries with latest available from (releases page)[https://github.com/google/ios-webkit-debug-proxy/releases]

**Comment by akuma8** [comment]
Hi @artygus, thanks a lot, you saved my day :)
