### ISSUE TITLE
Starting ios_webkit_debug_proxy at port 27753 fails over wifi

### ISSUE THREAD

**Issue by lahiruw** [google/ios-webkit-debug-proxy#237]
this works fine when i connect device to Macbook via cable , any idea why this hapis not happening pens through wifi ?

**Comment by lahiruw** [comment]
Specs as below
xcode9 / iOS 11.1 / Appium 1.6.4

**Comment by lahiruw** [comment]
@artygus are you able to help me pls ???

**Comment by artygus** [comment]
hi @lahiruw, I believe usbmuxd daemon only listens devices connected via usb

**Comment by lahiruw** [comment]
@artygus Oh is it  My bad .Android has no issue in running through wifi only Ios has ..
