### ISSUE TITLE
can't use console

### ISSUE THREAD

**Issue by lslqtz** [google/ios-webkit-debug-proxy#238]
![](https://user-images.githubusercontent.com/18650291/33019512-a6485e48-ce35-11e7-9c5c-244711c3a4d8.png)
Console has many errors
```
ios_webkit_debug_proxy -f chrome-devtools://devtools/bundled/inspector.html
```

**Comment by artygus** [comment]
https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

**Comment by lslqtz** [comment]
but i can't use default frontend too

**Comment by lslqtz** [comment]
in old version, it works

**Comment by artygus** [comment]
the issue is not related to proxy, front-end tools protocols diverged, there're a few alternatives listed in readme section I mentioned above
