### ISSUE TITLE
How to inspect on ios 11 ?

### ISSUE THREAD

**Issue by ebatgerel** [google/ios-webkit-debug-proxy#240]
Hello guys i have a trouble with ios 11.
My operating  system: Windows 10;
Browser version: Chrome Version 64.0.3273.3 (Official Build) canary (64-bit)
OS version: 11.2
Phone: Iphone 5s

Problem is i can't attach my phone using webkit_proxy

Listing devices on :9221
Could not connect to lockdownd. Exiting.: No error
Unable to attach f54990cdc9c844bbea514f882058dffa03d7a878 inspector

![capture](https://user-images.githubusercontent.com/16677052/33115997-08490f84-cf9e-11e7-8bc8-4fb5d63368a6.PNG)
How to solve this ?

**Comment by artygus** [comment]
hi @ebatgerel what does ios_webkit_debug_proxy -V show?

**Comment by ebatgerel** [comment]
@artygus  Hello I am sorry it was just my ios_webkit_debug_proxy is running on 1.7.1 so i updated my my ios_webkit_debug_proxy to 1.8 its worked
