### ISSUE TITLE
How to open editable devTools ? 

### ISSUE THREAD

**Issue by ebatgerel** [google/ios-webkit-debug-proxy#241]
I have problem i can't edit my css file and i don't clear well  about [documentation](https://github.com/google/ios-webkit-debug-proxy#using-with-devtools)

![capture](https://user-images.githubusercontent.com/16677052/33299247-b33989e2-d425-11e7-8722-d00b0305016e.PNG)

And i used ios_webkit_debug_proxy -f  chrome-devtools://devtools/bundled/inspector.html
It shows the same result. How i solve this ?

**Comment by auchenberg** [comment]
See https://medium.com/@auchenberg/hello-remotedebug-ios-webkit-adapter-debug-safari-and-ios-webviews-from-anywhere-2a8553df7465

**Comment by ebatgerel** [comment]
@auchenberg can you give me some live help  ?

**Comment by ebatgerel** [comment]
I tried and i got this now i can't connect with phone ? how to solve this ?

![capture](https://user-images.githubusercontent.com/16677052/33306153-2e939b5c-d44c-11e7-973f-7716aedcae5e.PNG)

**Comment by artygus** [comment]
this is not a techincal issue, please use stackoverflow or similar resources
