### ISSUE TITLE
Install ios-webkit-debug-proxy using scoop

### ISSUE THREAD

**Issue by ricardofreeman** [google/ios-webkit-debug-proxy#242]
Hi, when I try to install ios-webkit-debug-proxy I'm getting this error

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\Ricardo> scoop install ios-webkit-debug-proxy
Installing 'ios-webkit-debug-proxy' (1.8).
Linking ~\scoop\apps\ios-webkit-debug-proxy\current => ~\scoop\apps\ios-webkit-debug-proxy\1.8
Creating shim for 'ios_webkit_debug_proxy'.
Can't shim 'ios_webkit_debug_proxy.exe': File doesn't exist.
PS C:\Users\Ricardo>
```

I followed the instructions
```
scoop bucket add extras
scoop install ios-webkit-debug-proxy
```
The first command worked okay.

After running **scoop install ios-webkit-debug-proxy** I noticed that the folders 1.8 and current inside scoop\apps\ios-webkit-debug-proxy are empty.

Can anyone help me with this installation?

Thanks in advance.

**Comment by artygus** [comment]
hi @ricardofreeman, I think you should open the issue at https://github.com/lukesampson/scoop-extras
