### ISSUE TITLE
Could not connect to lockdownd. Exiting.: Operation now in progress

### ISSUE THREAD

**Issue by tomeraz** [google/ios-webkit-debug-proxy#243]
Ubuntu 16.04.03
installed with:
brew install --HEAD ios-webkit-debug-proxy (using Linuxbrew)

**Comment by artygus** [comment]
hi @tomeraz, there're many similar closed issue, please use the search

**Comment by tomeraz** [comment]
This worked:
brew update
brew reinstall --HEAD libimobiledevice
brew reinstall -s ios-webkit-debug-proxy
