### ISSUE TITLE
Is it possible to detect WKWebview on a macos application?

### ISSUE THREAD

**Issue by atishay** [google/ios-webkit-debug-proxy#245]
It doesn't detect automatically, but since safari can, that should also be possible. Is there a way that can be enabled?

**Comment by artygus** [comment]
no, please refer to readme

**Comment by aleclarson** [comment]
@artygus I don't see anything relevant in the readme. Can you explain the technical barriers for JSContext/WKWebView support on macOS?

**Comment by artygus** [comment]
@aleclarson utility works only with ios devices, not "desktop" macos apps

**Comment by aleclarson** [comment]
@artygus Yeah but which parts of this utility are iOS-specific? Does macOS have a different protocol or something? Aren't they both using WebKit?

**Comment by artygus** [comment]
it's 100% ios specific, check https://github.com/google/ios-webkit-debug-proxy/blob/master/design.md for more info
