### ISSUE TITLE
Not able to get the webview in actual device whereas I have the same webview in simulator

### ISSUE THREAD

**Issue by suvidhapra** [google/ios-webkit-debug-proxy#246]
I am not able to get the webview in actual device whereas I have the same webview in simulator using appium.

In my application I have login screen as webview and I am not able to get the webview in actual device whereas in simulator I am easily getting both webviews(NATIVE_APP, WEBVIEW_1233), but when I run the same set of scripts in actual device it returns only one webview 'NATIVE_APP'

**Environment**
Appium version : 1.7.2
Desktop OS/version used to run Appium: OS-X 10.13.3 (17D47)
Node.js version (unless using Appium.app|exe): v9.4.0
Mobile platform/version under test: iPhone 8 Plus iOS - 11.1.1
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium CLI

**Details**
In my application I have login screen as webview and I am not able to get the webview in actual device whereas in simulator I am easily getting both webviews(NATIVE_APP, WEBVIEW_1233), but when I run the same set of scripts in actual device it returns only one webview 'NATIVE_APP'

**Appium logs**
https://gist.github.com/suvidhapra/5f75b9d2957a750d21ff302cc7c6c66c

**Code To Reproduce Issue [ Good To Have ]**
webview = @driver.available_contexts
webview.each {|st| puts st}
@driver.set_context(webview[1])

**[caps]**
platformName = "ios"
deviceName = "Test Device"
platformVersion = "11.1.1"
app = "../iOSClientPOC/app/app4815162342_qa.ipa"
automationName = "XCUITest"
udid = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
xcodeOrgId = "XXXXXXXXXX"
xcodeSigningId = "iPhone Developer"

**Output:**
|NATIVE_APP

**Questions asked to me when I posted the same issue in appium:**
Q : I am able to see my device in safari's develop menu.

A : ![issue](https://user-images.githubusercontent.com/29312893/36122945-032a2c2a-1000-11e8-83bf-5423c0c24673.png)

Q : Are you able to see the webview if you connect IWDP manually?
A : when I try to run the IWDP manually it returns empty JSON

**Note** : I have posted the same issue in appium github. They referred me to this team in order to get some resolution. https://github.com/appium/appium/issues/10095

My automation is stuck on this research so please help me to resolve this soon.

**Comment by artygus** [comment]
hi @suvidhapra, please use search there were similar issues, most likely you didn't sign the app properly (provisioning)

**Comment by artygus** [comment]
closing the issue since no replay from OP, the screenshot shows that safari is not able to detect web views as well
