### ISSUE TITLE
 on linux - spawn adapter - unable to attach inspector

### ISSUE THREAD

**Issue by rowntreerob** [google/ios-webkit-debug-proxy#247]
dev = iphone (ios 11
env : ubuntu 16.04  & libusbmuxd-dev & usbmuxd &  libimobiledevice
ios_webkit_debug_proxy 1.8
Built with libimobiledevice v1.2.1, libplist v1.12
( no wine , no itunes , no playonlinux ) therefore /var/db/lockdownd  does not exist

as seen below, the [adapter](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter) calls ios-wdp  and DEBUG shows the following:

```
 remotedebug adapter.spawnProcess, path=/usr/local/bin/ios_webkit_debug_proxy +1ms
  remotedebug adapter.spawnProcess.stderr, data=Could not connect to lockdownd. Exiting.: No such file or directory
  remotedebug Unable to attach b2e7d7381cb9bd9d2fa334075f1389f231ec797c inspector
```
relevant callstack is from 'adapter.js' in the adapter project , excerpt below:

```
    spawnProcess(path, args) {
        logger_1.debug(`adapter.spawnProcess, path=${path}`);
        return new Promise((resolve, reject) => {
            if (this._proxyProc) {
                reject('adapter.spawnProcess.error, err=process already started');
            }
...
            this._proxyProc.stderr.on('data', data => {
                logger_1.debug(`adapter.spawnProcess.stderr, data=${data.toString()}`);
            });
```

i dont know the error for sure ( please help w that ) but i can guess... 

I take  msgs above to mean that when the adapter spawns new and calls 'ios-wdp' its throwing the error on a fileSys not found relating to 'lockdownd'.  My guess that /var/db/lockdownd is missing because there is no iTunes installed on ubuntu... All the other dependencies installed OK i think. iTunes on ubuntu is not stable ( did not install it).

**Comment by artygus** [comment]
hi @rowntreerob, you need to have usbmuxd installed

**Comment by rowntreerob** [comment]
that solved the issue . thank you
