### ISSUE TITLE
Mobile chrome - scrolltop not working

### ISSUE THREAD

**Issue by jakebuttigieg** [google/ios-webkit-debug-proxy#248]
Hi, not sure if this is the correct place to inform you of my findings but i was having an issue with mobile chrome when it came to performing the scroll.

While investigating i noticed that, although in FullpageReact.js line 1620
`element[elementBoundary] = val`
the scrolltop(elementBoundary) value of html(element) was remaining zero, although it was being set to val correctly.

After some searching, i found that html regularly has issues with scrolltop on mobile browsers due to some technicalities (html not considered a node, if im not mistaken?).

I found that on line 1439
  `var docElementSet = new Set(['firefox', 'chrome', 'crios' // chrome ios`
the crios value in docElementSet was being found, therefore, on line 1442
 `if (docElementSet.has(name)) { return document.documentElement;  }`

rather than falling back to line 1447 
`return document.body`

By returning body, correct functionality was achieved on mobile chrome also (with some small issues regarding the address bar haha).

For whoever is interested in the address bar hack, i used the following in componentDidMount
`if(document.height < window.outerHeight) { document.body.style.height = (window.outerHeight + 50) + 'px'; }`

**Comment by artygus** [comment]
hi @jakebuttigieg, I'm not sure how it's related to the proxy. Could you elaborate please?

**Comment by jakebuttigieg** [comment]
Wrong package, so sorry haha
