### ISSUE TITLE
Enable click on overlay to close on iOS

### ISSUE THREAD

**Issue by johncookv** [google/ios-webkit-debug-proxy#249]
**Summary:**
On iOS 11, with onClickOverlay enabled, when the user taps on an overlay, the overlay doesn't close.

Seems similar to another react modal library. The relevant links are below.

[https://github.com/reactjs/react-modal/issues/301](url)
[https://github.com/reactjs/react-modal/pull/304](url)

**Comment by artygus** [comment]
hi @johncookv, how is that related to proxy?

**Comment by johncookv** [comment]
Well that's embarrasing. I"m sorry for posting this in the wrong github repo. :(
