### ISSUE TITLE
IWDP does not detect webviews anymore on iOS 11.3 Simulator (Xcode 9.3-beta3)

### ISSUE THREAD

**Issue by mykola-mokhnach** [google/ios-webkit-debug-proxy#250]
Mac OS 10.13.3, Xcode 9.3-beta3

1. Install IWDP with brew
2. Start iPhoneX 11.3 Simulator and open Safari in it
3. Start `ios_webkit_debug_proxy` in terminal

Actual result:
No devices are shown in the list

Expected device:
The simulator should be shown in the list.
On the same system with Xcode 9.2 the output is

```
Listing devices on :9221
Connected :9222 to SIMULATOR (SIMULATOR)
```

It might be that Apple has deprecated debugging via TCP port in the recent Xcode SDK and it is only available via Unix socket (probably, because this is the only thing I can se in `lsof ` output of `launchd_sim` process so far: `/private/tmp/com.apple.launchd.r4UKA9gcsI/com.apple.webinspectord_sim.socket`

**Comment by artygus** [comment]
hi @mykola-mokhnach thanks for the report, I'll take a look. the bad pard is I need to update OS to install new Xcode, it would take some time

**Comment by benzhe** [comment]
xcode 9.3 is released, experiencing the same issue.

**Comment by skansar** [comment]
Upgraded to IOS on the device 11.03 and xocde 9.2 and facing below issue.  

Unable to connect to iPhone (00000000000000blah) 
  Please verify that Settings > Safari > Advanced > Web Inspector = ON

>>>>ios_webkit_debug_proxy -V 
ios_webkit_debug_proxy 1.8 
Built with libimobiledevice v1.2.1, libplist v2.0.0

tried to reinstall libimobiledevice does not seem to work

**Comment by artygus** [comment]
hi @skansar the issue is not related to this thread please open another one, what does ios_webkit_debug_proxy -d shows, any output? do you see webviews in Safari browser under Developer tab?

**Comment by artygus** [comment]
I confirm the issue is there. Looks like since XCode 9.3.3 there's a unix socket connection for each webinsepctord of simulator. The question is how to detect unix socket locations. One way is lsof (somewhat like https://github.com/appium/appium-ios-simulator/pull/145), but I hope there's a better a way

**Comment by kdthomas2121** [comment]
Has there been any progress made on this?

**Comment by artygus** [comment]
all the updates will be posted in this thread, also everybody is welcome to contribute

**Comment by artygus** [comment]
Simulators from Xcode 9.3-beta3 and up are only inspectable in safari technology preview for now AFAIK. Just to clarify the issue is only about simulators and Xcode 9.3-beta3 (and up)

**Comment by iTOYS** [comment]
The same issue with Xcode 9.3

**Comment by alastaircoote** [comment]
I've had some success in finding the unix socket via the method described in appium/appium-ios-simulator#145, then [piping that socket](https://stackoverflow.com/a/25433538/470339) over TCP to port 27753, which is where the proxy expects to find a connection. Once I've done that the proxy finds the simulator fine and I can open the debugger. (I'm not able to send commands over the console, but I just tested with iOS 10 and it doesn't work there either, so there must be some other issue going on)

I don't have any good suggestions on avoiding lsof, though.

**Comment by AL-locator** [comment]
Hi, is there any progress?
Still having the issue since XCode 9.3

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/872

**Comment by zhenshub** [comment]
And iOS 12.2 simulator is not support, if the lib can`t support I think you should describe in README.md to make all user know "iOS 10+ `s simulator not support "

**Comment by artygus** [comment]
there's a possiblity to provide simulator socket to iwdp since 1.8.5
