### ISSUE TITLE
Unable to attached iOS 11

### ISSUE THREAD

**Issue by laurennlam** [google/ios-webkit-debug-proxy#251]
Hi,

I'd like to debug an iPad with iOS 11. i'm in windows 10 and when I launched the app, here is the output :
> Could not connect to lockdownd. Exiting.: No error
I used the exe file to launch ios-webkit-debug-proxy.
I tried to relaunch it, deplugged the cable but without success. Do you have any idea ?

thanks,

**Comment by artygus** [comment]
hi @laurennlam, what does 'ios_webkit_debug_proxy -V' show?

**Comment by laurennlam** [comment]
It doesn't seem to work. It display the help information.
I used your binary file downloaded here : https://sourceforge.net/projects/ios-webkit-debug-proxy-win32/?source=typ_redirect

**Comment by artygus** [comment]
@laurennlam looks like you're using the old version, new releases available on github https://github.com/google/ios-webkit-debug-proxy/releases

**Comment by laurennlam** [comment]
Thanks @artygus I didn't find the right one. The iPad is now detected !
