### ISSUE TITLE
How to support jscore debugging on devices without developer certificates？

### ISSUE THREAD

**Issue by menglexiang** [google/ios-webkit-debug-proxy#252]
There are two current issues:
1. Is Safari debugging JSCore's protocol the same as WKWebView.
2. Debug on devices without developer certificates.

**Comment by artygus** [comment]
hi @menglexiang you can't debug devices without dev certificates, this limitation comes from system, not utility.

**Comment by menglexiang** [comment]
If I use the jscore generated by the source code and not provided by the system, can I bypass this limitation?

**Comment by artygus** [comment]
I guess you should be able to expose debugger on a certain port, similar to what react native does. In this case you don't need proxy here as you wont't interact with apple's webinspector and usbmuxd service
