### ISSUE TITLE
Timeline events intermittent in iOS 11.3

### ISSUE THREAD

**Issue by pmeenan** [google/ios-webkit-debug-proxy#256]
It's a bit strange and not exactly clear what is going on but the devtools timeline events look like they are mostly missing with the iOS 11.3 rollout.  The network events all still look accurate so it looks like a change in how the inspector interacts with the js profiler (or a move away from timeline events).

For example, [this CNN test](https://www.webpagetest.org/result/180420_9P_8f26e6a35eb6fd13b6956afd4db75186/) in WebPageTest shows a little timeline activity at the beginning of the load (up until 6 seconds) and then goes silent).  

![image](https://user-images.githubusercontent.com/444165/39052030-8e88e66a-4478-11e8-81bc-533dcf6d8903.png)

Viewing it in the [timeline viewer](https://www.webpagetest.org/chrome/timeline.php?test=180420_9P_8f26e6a35eb6fd13b6956afd4db75186&run=1) shows the same result and looking at the [raw timeline events](https://www.webpagetest.org/getTimeline.php?test=180420_9P_8f26e6a35eb6fd13b6956afd4db75186&run=1) also looks to match what the UI is showing.

Up until the iOS 11.3 (Safari 11.1) release it would capture the events through the whole load.  Here is what it looks like on the iPhone 5c which is stuck at iOS 9.x:

![image](https://user-images.githubusercontent.com/444165/39052198-3e1320e6-4479-11e8-9a40-30d870546126.png)

Hopefully it is just a new event that needs to be mapped and I'll see if I can debug it but I haven't worked on the proxy code before so it may take me a while.

**Comment by artygus** [comment]
hi @pmeenan please see https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

**Comment by pmeenan** [comment]
@artygus It's not a dev tools problem.  The timeline view I linked above is the old viewer.  The proxy was originally implemented for the WebPageTest iOS agents and I'm very familiar with how to use it (the team that originally released it worked for me at the time).  

The problem is that the underlying events aren't in the websocket stream (well, most of them aren't) starting with the 11.3 release.  WebPageTest talks directly to the Websocket interface exposed by the proxy and parses the events itself.  The Network.* events and Page.* events all still look good but a lot of the Timeline.* events are no longer generated.

If Safari no longer emits the events then there's not much we can do but I expect they need to be available in there somewhere if the Web Inspector can still remote-profile pages.

**Comment by pmeenan** [comment]
Just to be clear, I am planning on debugging it and seeing if I can figure out what changed on the Safari side.  It may just take me a few days to get time to look at it.

**Comment by artygus** [comment]
oh that's interesting! let me know if you need help in debugging the issue

**Comment by pmeenan** [comment]
Looks like it isn't a protocol issue (at the proxy level anyway).  They moved the profiling, debugger, etc to different events.  It does mean that using an old version of dev tools will no longer be able to debug it.  For WebPageTest I just need to teach it how to understand the new top-level events.
