### ISSUE TITLE
Click event

### ISSUE THREAD

**Issue by VasilijSviridov** [google/ios-webkit-debug-proxy#257]
Is it possible to send javascript click event to ios-webkit-debug-proxy to initiate click on real device ?

**Comment by artygus** [comment]
hi @VasilijSviridov yes, you can find example of sending commands in examples directory, for dev tools protocol reference see https://chromedevtools.github.io/devtools-protocol/

**Comment by artygus** [comment]
closing as this is not a techincal issue, please use stackoverflow or similar resources

**Comment by VasilijSviridov** [comment]
Cheers for your help, figured it out.
