### ISSUE TITLE
Chrome does not mirror screen [UBUNTU 17.10]

### ISSUE THREAD

**Issue by brunoslash76** [google/ios-webkit-debug-proxy#261]
Hi, 

After installing ios-webkit-debug-proxy and [remotedebug-ios-webkit-adpter](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter) everythings works fine. 
I can control safari from Chrome DevTools, but I just can only edit HTML, Styles are disabled to edit and the mirror of mobile screen on Chrome does not appear. 

Thank you.

**Comment by artygus** [comment]
hi @brunoslash76, please see readme section https://github.com/google/ios-webkit-debug-proxy#using-with-devtools
