### ISSUE TITLE
Issue installing graph-tool library to conda installed python 3.5

### ISSUE THREAD

**Issue by joanna350** [google/ios-webkit-debug-proxy#262]
Brew seems quicker, but I have no idea how to link it to my conda-installed python.
So followed this link-> https://gist.github.com/dlozeve/ed59bba8bc8cb9b21e2af36cc9766938

Also checked the installation instruction in the tar file of graph-tool 2.26,
returned the following error after typing `./config`

Package 'cairo', required by 'cairomm-1.0', not found

<img width="486" alt="screen shot 2018-06-04 at 2 17 29 pm" src="https://user-images.githubusercontent.com/19216902/40899528-6ddf5bc6-6802-11e8-95bd-9fc27dc59bd4.png">

1. Tried adding to .bash_profile the PKG_CONFIG_PATH = $PKG_CONFIG_PATH:<directory under anaconda where there is cairomm>
2. Tried `./configure -with--CAIROMM_CFLAGS -with--CAIROMM_LIBS`

Not working.. not sure I implemented alternate solutions correctly either

**Comment by artygus** [comment]
hi @joanna350 I think you posted in the wrong repo 😕
