### ISSUE TITLE
About iwdp and iOS connection via WiFi

### ISSUE THREAD

**Issue by masakazu-k** [google/ios-webkit-debug-proxy#263]
* It is concluded that issue #237 can not connect via WiFi, based on usbmuxd specifications.
 * The answer to the issue [#22](https://github.com/libimobiledevice/libusbmuxd/issues/22) for libimobiledevice says that, usbmuxd can connect to iOS terminal via WiFi.

Therefore, we investigated the following whether able to connect iOS via WiFi or not.

1. Verify whether Attach / Detach of real iOS device (udid) can be detected via WiFi

As a result of the verification, we found that Attach / Detach of real iOS device can be detected via WiFi by using libimobiledevice's idevice_event_subscribe function.
Attach / Detach by switching WiFi on / off was detectable (there is a time difference).

Supplement

> If USB on connecting and "via network" is ON, the same iOS terminal will be detected twice.

2. Verify whether the Web Inspector service can be activated

It was possible to start without modification in IWDP.

3. Verify whether Web Inspector service and data can be transmitted / received

In the case of via WiFi, the ssl_enabled flag becomes true after executing the idevice_connect function of libimobiledevice.
When the ssl_enabled flag is true, since the subsequent process becomes an error,  modified the idevice_connection_enable_ssl function to execute as follows.

```
  if(service->ssl_enabled){
    fprintf(stdout, "INFO: %s(%s) is connected via WiFi\n", *to_device_name, device_id);
    if(idevice_connection_enable_ssl(connection) != IDEVICE_E_SUCCESS){
        perror("idevice_connection_enable_ssl failed!");
        goto leave_cleanup;
    }
  } else {
    fprintf(stdout, "INFO: %s(%s) is connected via USB\n", *to_device_name, device_id);
  }
```

However, the following error occurs when sending / receiving data between iwdp and Web Inspector service.

Error contents

on iOS:

```
webinspectord	Launched (Device)
webinspectord	Automatic Inspection Configuration Changed : enabled(0)
webinspectord	XPC Application Connection Event: 68 - <private>
webinspectord	Error getting name for <private>: Error Domain=NSOSStatusErrorDomain Code=-50 "(null)"
webinspectord	Application Connected: 68 - PID:68 - <private>
webinspectord	Device: Starting lockdown XPC checkin process
webinspectord	Device: Received Client Connection
webinspectord	Received Pending Client Connection: <_RWIRelayClientTCPConnection: 0x127d0d300>
webinspectord	Unexpected type: <private>, Expected type: <private>
webinspectord	_RWITCPConnection read failed: 5 - Input/output error
webinspectord	Shutting Down, last client disconnected.
webinspectord	Automatic Inspection Configuration Changed : enabled(0)
```

on IWDP:

```
Unable to connect to my ipad name (my ipad udid)
  Please verify that Settings > Safari > Advanced > Web Inspector = ON
```

Supplement
> Web Inspector is on.

Until the Web Inspector service starts up, it is executing with the API of libimobiledevice, but actual data transmission / reception is directly written to the file descriptor (src / rpc.c).
Due to this, Is the SSL related error occurred when sending and receiving data between iwdp and the Web Inspector service?
If 3. is cleared, I think that iwdp and iOS terminal can connect via WiFi.
Please solve the issue so that can connect to iOS via WiFi.

**Comment by auchenberg** [comment]
This is quite exciting!

**Comment by artygus** [comment]
hi @masakazu-k, thanks for the research. Looks very interesting! I'll take a look next week

**Comment by masakazu-k** [comment]
@artygus 
I continue to investigate, but I have no success.
Did you have any results?

I expect it!

**Comment by joehoyle** [comment]
Any update on this? As I understand it at the moment, no one has developed a way to use the Safari Debugging Protocol over anything but a USB connection?

**Comment by artygus** [comment]
I can see progress in libusbmuxd https://github.com/libimobiledevice/libusbmuxd/commit/f5a7387a54ae08c9cd1d83a415393e0e909dc6e6
Going to look closer in how to handle Wi-Fi devices in ios-webkit-debug-proxy

**Comment by codermapuche** [comment]
Any progress about this?
