### ISSUE TITLE
Connect function failed with error 10061

### ISSUE THREAD

**Issue by Vermat99** [google/ios-webkit-debug-proxy#264]
Hi, i needed this tool after some months, but now i only get the following error:
```
ios_webkit_debug_proxy -d
ss.add_server_fd(500)
Listing devices on :9221
device_listener: connect function failed with        error 10061
No device found, is it plugged in?
```

I tried to reinstall but with no luck. I'm currently on Windows 10, using scoop on Powershell. What can i do?

**Comment by artygus** [comment]
hi @Vermat99, looks like itunes service is not running

**Comment by artygus** [comment]
or you have firewall blocking tcp port 27015

**Comment by Vermat99** [comment]
Thank you! It was something with the firewall. I don't know exactly what because accessing the firewall was crashing my entire PC. I reinstalled Windows and it works almost fine. I have the #255 issue but it's ok.
