### ISSUE TITLE
Can't select any node

### ISSUE THREAD

**Issue by debute** [google/ios-webkit-debug-proxy#265]
When I'm debugging problem, then `body` element is selected. Whenever I try to select any other element/node, it does nothing. I can't try to change the font-size or anything.

**Comment by artygus** [comment]
he @debute check out the readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

**Comment by debute** [comment]
`Couldn't find manifest for 'remotedebug-ios-webkit-adapter'.`
