### ISSUE TITLE
extra tools needed

### ISSUE THREAD

**Issue by Marineau** [google/ios-webkit-debug-proxy#266]
I think there should be a package for this since it need scoop for windows, and scoop need elixir, and elixir needs other updates, looks like we have to guess it all for install the tools needed.

**Comment by artygus** [comment]
hi @Marineau I'm not sure what you mean exactly

**Comment by artygus** [comment]
do you mean that scoop installation seem complicated? I think it's related to scoop documentation, not to current project

**Comment by Marineau** [comment]
Yea well, needed also to configure path variables, install openssh, set other environment params, check for scoop installation issue indeed because there is powershell glitch in the extract process. Indeed it's essentially related to scoop, but since this project rely on those tool I don't know maybe just a bit more detailled instructions on what's need globally

**Comment by artygus** [comment]
It doesn't rely on scoop, you can download fresh build from releases page https://github.com/google/ios-webkit-debug-proxy/releases. I'm closing the issue since it would require extra efforts to keep scoop installation docs up date. One can always refer to scoop documentation.
