### ISSUE TITLE
Could not connect to lockdownd (with an error code)

### ISSUE THREAD

**Issue by linus-xuzixuan** [google/ios-webkit-debug-proxy#267]
Using macOS 10.14 DB7, with an iPhone running iOS 10.3.3
The error code is either 17 or 21 (and 19 once, but not anymore), depending on whether my iPhone is unlocked.
Verbose output:
```
ss.add_server_fd(3)
Listing devices on :9221
ss.add_fd(4)
ss.add_server_fd(5)
ss.remove_server_fd(5)
ss.recv fd=4 len=978
ss.add_server_fd(5)
Could not connect to lockdownd, error code -21. Exiting.
ss.remove_server_fd(5)
Unable to attach 08cab09174966004fa6fd26a2ac37ecb29d7f5b3 inspector
^Css.remove_server_fd(3)
ss.remove_fd(4)
```

**Comment by artygus** [comment]
hi @linus-xuzixuan,

could you please send the output of `ios_webkit_debug_proxy -V`?

and also can you confirm permission on lockdown dir as follows 

    ls -ld /var/db/lockdown/
    drwx------  7 _usbmuxd  _usbmuxd ...

**Comment by artygus** [comment]
closing since no reply from OP. lockdown connection errors either configuration problems, or the issue related to libimobiledevice library
