### ISSUE TITLE
Could not connect to lockdownd, error code -13. Exiting.

### ISSUE THREAD

**Issue by varjay** [google/ios-webkit-debug-proxy#270]
➜  ~ ios_webkit_debug_proxy -f chrome-devtools://devtools/bundled/inspector.html
Listing devices on :9221
Could not connect to lockdownd, error code -13. Exiting.
Unable to attach a41ee5ebda0bf889793fdb88b6ff256cdb103440 inspector

ios_webkit_debug_proxy 1.8.1
Built with libimobiledevice v1.2.0, libplist v2.0.0
macOS 10.14 Beta (18A377a)
iphone 7plus 10.13.1
mac chrome  68.0.3440.106

Why is it wrong, ask for help! Thank you.

**Comment by artygus** [comment]
hi @varjay, seems like libimobiledevice is an old one, did you try to rebuild it from sources?

    brew update
    brew reinstall --HEAD libimobiledevice
    brew reinstall -s ios-webkit-debug-proxy

**Comment by artygus** [comment]
closing since no reply from OP

**Comment by cjnchk** [comment]
https://github.com/libimobiledevice/libimobiledevice/issues/717
it works in my mac version 10.14.4 Beta (18E174f).
