### ISSUE TITLE
recv failed: Connection reset by peer on PPC64 linux

### ISSUE THREAD

**Issue by jeisom** [google/ios-webkit-debug-proxy#271]
I getting recv failed. I am wondering if this is an big endian issue. I have tried with an iPad with iOS 12 PB and an iPad mini with iOS 9.3.5. Both debug logs from IWDP are the same.  ideviceinfo gives expected output, idevicesysinfo works and idevicepair gives success.

I have the latest github code of IWDP,  libimobiledevice, libusbmuxd and usbmuxd installed.

Any suggestions on how I can get this to work?

> ./src/ios_webkit_debug_proxy -d
ss.add_server_fd(3)
Listing devices on :9221
ss.add_fd(4)
ss.add_server_fd(5)
ss.remove_server_fd(5)
recv failed: Connection reset by peer
ss.remove_fd(4)

**Comment by artygus** [comment]
hi @jeisom, it certainly could be! utility works correctly on LE machines only
