### ISSUE TITLE
Could not connect to lockdownd, error code -2. Exiting.

### ISSUE THREAD

**Issue by LitileXueZha** [google/ios-webkit-debug-proxy#272]
What happens?Already run command in this [issue](https://github.com/google/ios-webkit-debug-proxy/issues/270)

**Comment by artygus** [comment]
hi @LitileXueZha, the error refers to unsuccessful handshake attempt by libimobiledevice lib, usually it happens on unsuccessful pairing. I would suggest clearing /var/db/lockdown/ dir

**Comment by LitileXueZha** [comment]
thank you.
just not granted when connecting

**Comment by cjnchk** [comment]
https://github.com/libimobiledevice/libimobiledevice/issues/717
it works in my mac version 10.14.4 Beta (18E174f).
