### ISSUE TITLE
Could not connect to lockdownd, error code -21. Exiting.

### ISSUE THREAD

**Issue by ccorcos** [google/ios-webkit-debug-proxy#273]
I tried `brew reinstall --HEAD ios-webkit-debug-proxy` and it still didn't work.

```
❯❯❯ ios_webkit_debug_proxy --debug
ss.add_server_fd(3)
Listing devices on :9221
ss.add_fd(4)
ss.add_server_fd(5)
ss.remove_server_fd(5)
ss.recv fd=4 len=984
ss.add_server_fd(5)
Could not connect to lockdownd, error code -21. Exiting.
ss.remove_server_fd(5)
Unable to attach 6a028994cf281be807bf80c5557c3f2eb3fbb8b0 inspector

❯❯❯ ios_webkit_debug_proxy --version
ios_webkit_debug_proxy 1.8.1
Built with libimobiledevice v1.2.0, libplist v2.0.0
```

**Comment by ccorcos** [comment]
First time after I plug my phone in, it says 

```
Listing devices on :9221
Could not connect to lockdownd, error code -19. Exiting.
Unable to attach 6a028994cf281be807bf80c5557c3f2eb3fbb8b0 inspector
```

and I have to click "Trust" on my device. Then nothing happens. I quit and try again and I get the -21 error. If I unplug my phone, and try again, it starts over at the -19 error.

**Comment by ccorcos** [comment]
Ok. I tried this now:

```
brew reinstall --HEAD libimobiledevice
brew reinstall -s ios-webkit-debug-proxy
```

and now I get a -2 error.

**Comment by ccorcos** [comment]
Restarting my computer didn't help.

**Comment by ccorcos** [comment]
Installed the latest MacOS update. Didn't help either.

**Comment by ccorcos** [comment]
I have an iPhoneX with the latest iOS as well. 11.4.1

**Comment by ccorcos** [comment]
![image](https://user-images.githubusercontent.com/1794527/45569970-0bb4f500-b816-11e8-962c-6f5bf7446113.png)

Now Safari dev tools won't even work. Ugh. "Use for Development" showed up and when I click it, nothing happens.

**Comment by ccorcos** [comment]
Hmm. When I try to run an app with Xcode, it asks to Trust the computer and it doesn't appear to work...

![image](https://user-images.githubusercontent.com/1794527/45570200-aca3b000-b816-11e8-8423-c12ddb344c2a.png)

**Comment by ccorcos** [comment]
When I open iTunes, I get this error.

![image](https://user-images.githubusercontent.com/1794527/45570330-1de36300-b817-11e8-9c1f-bf07900a9cb6.png)

Man, this library really caused me some problems...

**Comment by ccorcos** [comment]
*Luckily*, I didn't actually `rm -rf /var/db/lockdown` but just moved it to the trash. Restoring this folder fixed everything!

**Comment by nelhu** [comment]
do not rm -rf /private/var/db/lockdown , It will make itunes did not recoginze iphone at all, I spent hours to restore this.

**Comment by nelhu** [comment]
I tried like you, but god does not like me, I tried all operation in offical README.md, But it still not work

**Comment by artygus** [comment]
just recreate folder with proper permissions 

drwx------  owned by _usbmuxd/_usbmuxd

**Comment by cjnchk** [comment]
https://github.com/libimobiledevice/libimobiledevice/issues/717

**Comment by cjnchk** [comment]
https://github.com/libimobiledevice/libimobiledevice/issues/717

**Comment by cjnchk** [comment]
https://github.com/libimobiledevice/libimobiledevice/issues/717
it works in my mac version 10.14.4 Beta (18E174f).
