### ISSUE TITLE
Invalid packet header 0x1ffffff91ffffffa0ffffff9d == .... == 26321053

### ISSUE THREAD

**Issue by ccorcos** [google/ios-webkit-debug-proxy#274]
When trying to open the dev tools tools, I get this error and it immediately closes:

```
❯❯❯ ios_webkit_debug_proxy
Listing devices on :9221
Connected :9222 to 🍉 (6a028994cf281be807bf80c5557c3f2eb3fbb8b0)
Invalid packet header 0x1ffffff91ffffffa0ffffff9d == .... == 26321053
Disconnected :9222 from 🍉 (6a028994cf281be807bf80c5557c3f2eb3fbb8b0)
```

**Comment by artygus** [comment]
hi @ccorcos the error occurs because message from webinspector is larger than 16mb, which is a bot suspicious. are you debugging any particular page or is it an app?

could you please attach output of `ios_webkit_debug_proxy -d`?

**Comment by artygus** [comment]
@ccorcos pushed changes, can you confirm has been fixed for you?

    brew reinstall -s ios-webkit-debug-proxy

**Comment by ccorcos** [comment]
I had to run `brew install --HEAD ios-webkit-debug-proxy` to install ios-webkit-debug-proxy HEAD-a724e10.

Still disconnected though: https://gist.github.com/ccorcos/096940a1e342cc4468b31801b2ef37eb

**Comment by artygus** [comment]
Well, I see no Invalid packet header in output log. Not sure what could go wrong this time, let me craft a sample with heavy js and I'll get back to you

**Comment by artygus** [comment]
can't reproduce the disconnection thing, would be great if you could provide reproduce steps

**Comment by ccorcos** [comment]
Hmm. When I open the production version of the app <www.notion.so> in iOS Safari, I don't get the disconnect error. However, it doesn't seem fully functional. The console doesn't work and click to select element thing doesn't work either. Is that expected?

As for a reproduction,  I'll have to try to set some things up. I'm async loading some more large JS files right after startup, so that could be it.

**Comment by artygus** [comment]
safari/chrome dev tools diverged a lot, please see https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

**Comment by ccorcos** [comment]
I see. Well let me see what I can recreate for you. Thanks for the help.

**Comment by ccorcos** [comment]
Just a thought, could the issue be large source maps? I'd imagine those are expensive to load, especially in a 39MB JS file.

**Comment by artygus** [comment]
Can't be 100% sure, but technically they're just another asset file. Crafted 28MB javascript with source maps, still no luck. The only achievement hanging dev tools page so far 🙂

**Comment by ccorcos** [comment]
Hmm. Turning sourcemaps off seems to have fixed the problem. Let me see if I can minimally reproduce.

**Comment by ccorcos** [comment]
More progress: 82MB generate js file with sourcemaps worked.

**Comment by ccorcos** [comment]
Alright, I have a repro! I generated a bunch of async typescript code (which would generate a bunch of sourcemaps). I also have a few async imports. Everything built with webpack.

[reproduction.zip](https://github.com/google/ios-webkit-debug-proxy/files/2394786/reproduction.zip)

**Comment by artygus** [comment]
it worked thanks! interesting thing is that Safari Dev Tools on OSX also gets disconnected immediately after opening, I bet that usbmuxd service fails to handle connection for some reason. I'm going to open new issue as the issue with inavalid packet header should've been fixed after increasing max websocket body limit
