### ISSUE TITLE
UDID format change with iPhone XS and XS Max

### ISSUE THREAD

**Issue by umutuzgur** [google/ios-webkit-debug-proxy#276]
Hi there,

With the release of iPhone XS and XS Max, the iPhone udid format changed and it became a value of 25 digits with a hyphen in between. ios_webkit_debug_proxy command line client with the argument -c is no longer valid. The regex to check the udid length is hardcoded to 40 but is now 25. Maybe removing the regex would be the cool solution since it is a command line client and the port number min max number can be passed separately than the udid.

Thanks a lot.

**Comment by artygus** [comment]
hi @umutuzgur, thanks for the report! I'd prefer to not break compatibility with  existing versions, at least two special characters should be reserved ",:" and possible null value. Can't find any official information about how new UDIDs going to be structured, only posts over the internet that it's going to be changed to variable length + dashes

**Comment by artygus** [comment]
@umutuzgur I pushed the changes to master, could you please verify the utility recognizes iphone xs? `brew reinstall -s ios-webkit-debug-proxy` or `brew install --HEAD ios-webkit-debug-proxy`

**Comment by umutuzgur** [comment]
Yeap, checking it. Thanks a lot

**Comment by umutuzgur** [comment]
Works perfectly
