### ISSUE TITLE
When will "ios-webkit-debug-proxy-1.8.1-win64-bin.zip" be released

### ISSUE THREAD

**Issue by whh8162880** [google/ios-webkit-debug-proxy#277]
When will "ios-webkit-debug-proxy-1.8.1-win64-bin.zip" be released

**Comment by JamieMcDonnell** [comment]
+1

**Comment by artygus** [comment]
it's coming this week I need to setup building machine, sorry for the delay

**Comment by artygus** [comment]
latest binaries for windows available on [releases page](https://github.com/google/ios-webkit-debug-proxy/releases)

**Comment by whh8162880** [comment]
thanks!!!
