### ISSUE TITLE
Illegal instruction: 4 when running ios_webkit_debug_proxy -c udid:9227

### ISSUE THREAD

**Issue by vjmaiky** [google/ios-webkit-debug-proxy#278]
MacOS: High Sierra 10.13.6
xCode: 10
Device: iPhone 6+, 11.4.1
Web Inspector; ON

Version: 
ios_webkit_debug_proxy 1.8.1
Built with libimobiledevice v1.2.1, libplist v2.0.0

user:~ itslocaladmin$ ios_webkit_debug_proxy -c udid:9227
Illegal instruction: 4

Basically happens for each command except help, version.
Any hints how I can bypass it?

**Comment by artygus** [comment]
hi @vjmaiky, you could try installing iwdp from sources `brew reinstall --HEAD ios-webkit-dbug-proxy`

**Comment by vjmaiky** [comment]
hi @artygus, I did following:

```
Leventes-Mac-mini:~ itslocaladmin$ brew reinstall --HEAD ios-webkit-debug-proxy
==> Reinstalling ios-webkit-debug-proxy 
==> Cloning https://github.com/google/ios-webkit-debug-proxy.git
Updating /Users/itslocaladmin/Library/Caches/Homebrew/ios-webkit-debug-proxy--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 86fed39 fixes #276, iPhone XS udid format change
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/ios-webkit-debug-proxy/HEAD-86fed39
==> make install
==> Not running post_install as we're building a bottle
You can run it manually using `brew postinstall ios-webkit-debug-proxy`
🍺  /usr/local/Cellar/ios-webkit-debug-proxy/HEAD-86fed39: 13 files, 334.3KB, built in 1 minute 2 seconds
Leventes-Mac-mini:~ itslocaladmin$ ios_webkit_debug_proxy -c 2ccf30dd21fa31a77967a66580e6c7ee62ecce88:27345
Illegal instruction: 4
Leventes-Mac-mini:~ itslocaladmin$ brew postinstall ios-webkit-debug-proxy
==> Postinstalling ios-webkit-debug-proxy
Leventes-Mac-mini:~ itslocaladmin$ ios_webkit_debug_proxy -c 2ccf30dd21fa31a77967a66580e6c7ee62ecce88:27345
```

**Comment by artygus** [comment]
did it work?

**Comment by vjmaiky** [comment]
nop

Leventes-Mac-mini:~ itslocaladmin$ ios_webkit_debug_proxy -c 2ccf30dd21fa31a77967a66580e6c7ee62ecce88:27345
Illegal instruction: 4

**Comment by artygus** [comment]
doest idevice_id -l work?
what does ios_webkit_debug_proxy -d -c ... show?

**Comment by vjmaiky** [comment]
```
Leventes-Mac-mini:~ itslocaladmin$ idevice_id -l. (Shows connected devices)
5d3c119a141e3842c2bb7ac77de8e47bf0c578c4
2ccf30dd21fa31a77967a66580e6c7ee62ecce88
```

```
Leventes-Mac-mini:~ itslocaladmin$ ios_webkit_debug_proxy -d
ss.add_server_fd(3)
Listing devices on :9221
ss.add_fd(4)
ss.add_server_fd(5)
ss.remove_server_fd(5)
ss.recv fd=4 len=1664
ss.add_server_fd(5)
Illegal instruction: 4
```


Leventes-Mac-mini:~ itslocaladmin$ ios_webkit_debug_proxy -c
ios_webkit_debug_proxy: option requires an argument -- c
Usage: ios_webkit_debug_proxy [OPTIONS]
iOS WebKit Remote Debugging Protocol Proxy v1.8.1.

By default, the proxy will list all attached iOS devices on:
  http://localhost:9221
and assign each device an incremented port number, e.g.:
  http://localhost:9222
which lists the device's pages and provides inspector access.

Your attached iOS device(s) must have the inspector enabled via:
  Settings > Safari > Advanced > Web Inspector = ON
and have one or more open browser pages.

To view the DevTools UI, either use the above links (which use the "frontend"
URL noted below) or use Chrome's built-in inspector, e.g.:
  chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1

OPTIONS:

  -u UDID[:minPort-[maxPort]]	Target a specific device by its 40-digit ID.
        minPort defaults to 9222.  maxPort defaults to minPort.
        This is shorthand for the following "-c" option.

  -c, --config CSV	UDID-to-port(s) configuration.
        Defaults to:
          null:9221,:9222-9322
        which lists devices ("null:") on port 9221 and assigns
        all other devices (":") to the next unused port in the
        9222-9322 range, in the (somewhat random) order that the
        devices are detected.
        The value can be the path to a file in the above format.

  -f, --frontend URL	DevTools frontend UI path or URL.
        Defaults to:
          http://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html
        Examples:
          * Use Chrome's built-in inspector:
              chrome-devtools://devtools/bundled/inspector.html
          * Use a local WebKit checkout:
              /usr/local/WebCore/inspector/front-end/inspector.html
          * Use an online copy of the inspector pages:
              http://chrome-devtools-frontend.appspot.com/static/33.0.1722.0/devtools.html
            where other online versions include:
              18.0.1025.74
              25.0.1364.169
              28.0.1501.0
              30.0.1599.92
              31.0.1651.0
              32.0.1689.3

  -F, --no-frontend	Disable the DevTools frontend.

  -d, --debug		Enable debug output.
  -h, --help		Print this usage information.
  -V, --version		Print version information and exit.

Leventes-Mac-mini:~ itslocaladmin$

**Comment by artygus** [comment]
okay, could you please try one more thing

    lldb ios_webkit_debug_proxy -c 2ccf30dd21fa31a77967a66580e6c7ee62ecce88:27345

when it prompts you for input, type `run` and hit enter, please send the output

**Comment by vjmaiky** [comment]
Leventes-Mac-mini:~ itslocaladmin$ lldb ios_webkit_debug_proxy -c 2ccf30dd21fa31a77967a66580e6c7ee62ecce88:27345
error: file specified in --core (-c) option doesn't exist: '2ccf30dd21fa31a77967a66580e6c7ee62ecce88:27345'

**Comment by artygus** [comment]
oh, yeah, sorry it should be 

    lldb ios_webkit_debug_proxy -- -c 2ccf30dd21fa31a77967a66580e6c7ee62ecce88:27345

**Comment by vjmaiky** [comment]
Please see attached log:
https://gist.github.com/vjmaiky/912649d14ab48ae613f8b49aaf332d13

**Comment by artygus** [comment]
looks like you have python version other than system installed, I see no useful output from lldb. could you please try installing six module `pip install six` and run lldb command again?

just in case you also need to connect with provided udid, to cause "illegal instruction" failure

**Comment by vjmaiky** [comment]
```
Leventes-Mac-mini:~ itslocaladmin$ lldb ios_webkit_debug_proxy -- -c 2ccf30dd21fa31a77967a66580e6c7ee62ecce88:27345
(lldb) target create "ios_webkit_debug_proxy"
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Current executable set to 'ios_webkit_debug_proxy' (x86_64).
(lldb) settings set -- target.run-args  "-c" "2ccf30dd21fa31a77967a66580e6c7ee62ecce88:27345"
(lldb) run
Process 6571 launched: '/usr/local/bin/ios_webkit_debug_proxy' (x86_64)
Process 6571 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00000001000b924c libimobiledevice.6.dylib`internal_plist_send + 127
libimobiledevice.6.dylib`internal_plist_send:
->  0x1000b924c <+127>: movbel %eax, (%rsi)
    0x1000b9250 <+131>: movq   (%r14), %rdi
    0x1000b9253 <+134>: leaq   -0x24(%rbp), %rbx
    0x1000b9257 <+138>: movl   $0x4, %edx
Target 0: (ios_webkit_debug_proxy) stopped.
(lldb) 
```

**Comment by artygus** [comment]
that's something, thanks! one last thing, could be please also send the output of `ls -l /usr/local/lib/libimobiledevice.6.dylib`?

**Comment by vjmaiky** [comment]
```
Leventes-Mac-mini:~ itslocaladmin$ ls -l /usr/local/lib/libimobiledevice.6.dylib
lrwxr-xr-x  1 itslocaladmin  admin  70 Oct  3 08:46 /usr/local/lib/libimobiledevice.6.dylib -> ../Cellar/libimobiledevice/HEAD-26373b3_2/lib/libimobiledevice.6.dylib
```

**Comment by vjmaiky** [comment]
```
Leventes-Mac-mini:~ itslocaladmin$ brew reinstall --HEAD libimobiledevice
==> Reinstalling libimobiledevice 
==> Cloning https://git.libimobiledevice.org/libimobiledevice.git
Updating /Users/itslocaladmin/Library/Caches/Homebrew/libimobiledevice--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at b34e343 tools: Remove length check on device UDID arguments to support newer devices
==> ./autogen.sh
Last 15 lines from /Users/itslocaladmin/Library/Logs/Homebrew/libimobiledevice/01.autogen.sh:
checking for Python site-packages path... /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
checking python extra libraries...  -ldl  -framework CoreFoundation
checking python extra linking flags... -Wl,-stack_size,1000000  -framework CoreFoundation /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/Python
checking consistency of all components of python development environment... no
configure: error: 
  Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LDFLAGS environment variable.
  Example: ./configure LDFLAGS="-L/usr/non-standard-path/python/lib"
  ============================================================================
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================
```

**Comment by vjmaiky** [comment]
it does'n recognise my python

**Comment by vjmaiky** [comment]
manged to reslove it; thanks for your support
