### ISSUE TITLE
 iOS 12.0.1 - Could not connect to lockdownd, error code -3. Exiting.

### ISSUE THREAD

**Issue by AsteaDevelopment** [google/ios-webkit-debug-proxy#279]
Hello,

I am having the following issue when trying to test against a new iPhone XS running iOS 12.0.1:

ios_webkit_debug_proxy --debug
ss.add_server_fd(3)
Listing devices on :9221
ss.add_fd(4)
ss.add_server_fd(5)
ss.remove_server_fd(5)
ss.recv fd=4 len=965
ss.add_server_fd(5)
Could not connect to lockdownd, error code -3. Exiting.
ss.remove_server_fd(5)
Unable to attach 00008020-0019181C02F8002E inspector

I have tried all the troubleshooting solutions here but nothing seems to be working.

I am currently on macOS using mojave 11.4, I did also try testing against an iPad Air 2.

Any suggestions please?

**Comment by artygus** [comment]
hi @AsteaDevelopment error -3 corresponds to LOCKDOWN_E_PLIST_ERROR, you could try clearing up lockdown dir or repairing device with your pc

**Comment by AsteaDevelopment** [comment]
@artygus I have tried clearing /var/db/lockdown dir and reconnected my device allowing to trust it but that didn't help. What do you mean "repairing device with your pc"?

**Comment by AsteaDevelopment** [comment]
I also have Xcode 10, Safari with a tab open and web inspector is on.

**Comment by artygus** [comment]
by 're-pairing' I meant untrusting your computer, the procedure could be painful. you could also try idevicepair utility.

are you using latest libimobiledevice? (1.2.1)

**Comment by AsteaDevelopment** [comment]
I will give those a try, no here is what -V shows:

ios_webkit_debug_proxy -V
ios_webkit_debug_proxy 1.8.1
Built with libimobiledevice v1.2.0, libplist v2.0.0

**Comment by artygus** [comment]
`brew reinstall --HEAD libimobiledevice` should help

**Comment by AsteaDevelopment** [comment]
I receive this error when doing that:

checking for libusbmuxd >= 1.1.0... no
configure: error: Package requirements (libusbmuxd >= 1.1.0) were not met:

Requested 'libusbmuxd >= 1.1.0' but version of libusbmuxd is 1.0.10

**Comment by AsteaDevelopment** [comment]
`brew install --HEAD usbmuxd` fixed the issue I had in my previous comment...testing now.

**Comment by AsteaDevelopment** [comment]
Working, thank you for the help!
