### ISSUE TITLE
IWDP does not support the Xcode10

### ISSUE THREAD

**Issue by gao2q** [google/ios-webkit-debug-proxy#280]
Mac OS 10.14
Xcode 10

Install IWDP with brew
Start iPhoneXS 12.0 **Simulator** and open Safari
Start ios_webkit_debug_proxy in terminal

Result:
No devices are shown in the list

**Comment by artygus** [comment]
he @gao2q please checkout readme regarding ios 10+ support, libimobiledevice should fix your issue. also make sure web inspector is on on your device and safari is able to see it

**Comment by gao2q** [comment]
Thanks you @artygus.

I has upgrade the libimobiledevice to latest as your say.
But it still not work.
My device is ios 12.0 simulator of Xcode 10.

**Comment by artygus** [comment]
can you confirm you're seeing your device in desktop Safari under develop tab?

**Comment by gao2q** [comment]
@artygus

**Comment by gao2q** [comment]
@artygus 
Yes, I can see the ios 12 simulator device in  desktop Safari under develop tab.

**Comment by artygus** [comment]
ah, sorry, you're talking about simulator! there's already an opened issue for that problem #250
