### ISSUE TITLE
Abort trap: 6 error when attempting to connect iOS 12 device

### ISSUE THREAD

**Issue by VinceBarresi** [google/ios-webkit-debug-proxy#281]
Hello,

I'd like to automate mobile web on my iOS devices via Appium but running into an issue. Here is the error log trying to start the proxy on port 27753:

```
✘-2 ~
10:18 $ ios_webkit_debug_proxy -u 1e32462a7f8e6fcd471acd9d55eab77a5d5349a6:27753 -d
ss.add_fd(3)
ss.recv fd=3 len=294
ss.recv fd=3 len=684
ss.add_server_fd(4)
Abort trap: 6
```

My environment is:
OSX Mojave 10.14
iPhone X / iOS 12.0
ios_webkit_debug_proxy 1.8.1
Built with libimobiledevice v1.2.0, libplist v2.0.0
Xcode 9.2
Web Inspector is toggled ON

**Comment by artygus** [comment]
hi @VinceBarresi never seen that exact error before, but you need latest libimobiledevice to debug ios 12 device, please refer to readme

**Comment by VinceBarresi** [comment]
@artygus Apologies as I didn't see that note at the bottom of the readme. I updated to 1.2.1 and it connected without issue. I believe you can close this out. Thanks.

**Comment by s2mh** [comment]
> @artygus Apologies as I didn't see that note at the bottom of the readme. I updated to 1.2.1 and it connected without issue. I believe you can close this out. Thanks.

how could you updated to 1.2.1

**Comment by aryalakshmi** [comment]
i am facing the same issue. and not able to update to 1.2.1. brew install gives only 1.2.0 version. please help!

**Comment by artygus** [comment]
@aryalakshmi use `--HEAD` flag, see readme for moe info
