### ISSUE TITLE
Debug proxy not working on iOS 12 ?

### ISSUE THREAD

**Issue by Dark-Kun** [google/ios-webkit-debug-proxy#282]
Hi!

After update to iOS 12.0.1, the ios-webkit-debug-proxy --debug return me the follow error :
`Unable to connect to iPhone de Logan (4d86e016c926b135d95c50a96a33df7c660b0264)
  Please verify that Settings > Safari > Advanced > Web Inspector = ON`

But I'm sure that Web Inspector is activated on my iOS device.

Thanks for help

**Comment by artygus** [comment]
hi @Dark-Kun do you have latest libimobiledevice installed? please see troubleshooting section of the readme

**Comment by Dark-Kun** [comment]
Hi @artygus, yes, all is up-to-date but I've the same issue

**Comment by artygus** [comment]
are you on mac? can you confirm you're seeing your device in Safari under Develop tab?

**Comment by Dark-Kun** [comment]
No, I'm on Windows 10, I'll try on my Mac now

**Comment by Dark-Kun** [comment]
With Safari, my iPhone is immediatly recognized on inspector without ios-webkit

**Comment by sebastianreinig** [comment]
Same here on windows :(

**Comment by artygus** [comment]
latest binaries for windows available on [releases page](https://github.com/google/ios-webkit-debug-proxy/releases)

**Comment by artygus** [comment]
if it won't pick up ios12 device feel free to reopen the issue

**Comment by sumitgos** [comment]
AutomationiMac:~ automation_svc$ ios_webkit_debug_proxy -c d4cea373043b83f3ff9e2628c46102566a765552:27753 -d
ss.add_fd(3)
ss.recv fd=3 len=294
ss.recv fd=3 len=851
ss.add_server_fd(4)
ss.add_fd(6)
wi.send_packet[174]:
00 00 00 AA 62 70 6C 69 73 74 30 30 D2 01 03 02 04 5A 5F ....bplist00.....Z_
5F 73 65 6C 65 63 74 6F 72 5F 10 16 5F 72 70 63 5F 72 65 selector..rpc_re
70 6F 72 74 49 64 65 6E 74 69 66 69 65 72 3A 5A 5F 5F 61 portIdentifier:Z__a
72 67 75 6D 65 6E 74 D1 05 06 5F 10 1A 57 49 52 43 6F 6E rgument.....WIRCon
6E 65 63 74 69 6F 6E 49 64 65 6E 74 69 66 69 65 72 4B 65 nectionIdentifierKe
79 5F 10 24 38 36 33 46 38 42 30 32 2D 31 41 44 34 2D 34 y_.$863F8B02-1AD4-4
44 31 30 2D 38 46 42 35 2D 38 43 34 36 37 30 33 36 43 45 D10-8FB5-8C467036CE
30 43 08 0D 18 31 3C 3F 5C 00 00 00 00 00 00 01 01 00 00 0C...1<?..........
00 00 00 00 00 07 00 00 00 00 00 00 00 00 00 00 00 00 00 ...................
00 00 83 ...
ss.recv fd=3 len=1546
ss.recv fd=6 len=0
ss.remove_fd(6)
Unable to connect to iPhone (d4cea373043b83f3ff9e2628c46102566a765552)
Please verify that Settings > Safari > Advanced > Web Inspector = ON
ss.remove_server_fd(4)

Have any update for this issue? I have got the same issue
The Safari can be launched but cannot load the URL ??? any update on this
Andyes, all is up-to-date but I've the same issue
