### ISSUE TITLE
ios-webkit-debug-proxy launch error

### ISSUE THREAD

**Issue by csharsha** [google/ios-webkit-debug-proxy#286]
When I try to launch ios-webkit-debug-proxy to access webview contexts in ios device using ios capabilities in appium desktop, I am getting error like "Error: Timed out waiting for ios_webkit_debug_proxy to open" and "Could not connect to lockdownd, error code -21. Exiting.,Unable to attach 92818ac7d66960e2b5bd76dcbf5355953f536555 inspector"

I eventually tried to update

brew update
brew reinstall libimobiledevice
brew reinstall ios-webkit-debug-proxy

but nothing worked. Please help.

**Comment by artygus** [comment]
hi @csharsha did you pair device and pc?

**Comment by csharsha** [comment]
Yes I have paired the device and the app is getting lauched from automated script which is done using c#. The thing is I want to access webview in this app so am using startIWDP capability and when I do so I am getting the above issue.

**Comment by csharsha** [comment]
Yes I have paired the device and the app is getting lauched from automated script which is done using c#. The thing is I want to access webview in this app so am using startIWDP capability and when I do so I am getting the above issue.

Please tell me if I have missed out something else which is important...

**Comment by csharsha** [comment]
Yes I have paired the device and the app is getting lauched from automated script which is done using c#. The thing is I want to access webview in this app so am using startIWDP capability and when I do so I am getting the above issue.

**Comment by artygus** [comment]
just in case brew reinstall libimobiledevice must be run with --HEAD flag, you could  also try clearing lockdown directory (/var/db/lockdown)

**Comment by cbioley** [comment]
I had to swap the first packages order, like so: 

`brew install --HEAD usbmuxd libimobiledevice ios-webkit-debug-proxy`

Oh, and the lockdown error is now gone. Thanks @artygus.

**Comment by artygus** [comment]
what do you mean similar? #285 clearly states the error messages returned by iwdp, #233 is closer to what you've described, can you see your devices in Safari under Develop tab?

**Comment by csharsha** [comment]
Sorry I tagged the issue wrongly, as mentioned in issue #207 and #233 I am not able to view or spy the webview inside my hybrid app even after starting ios_Webkit_debug_proxy. I have installed the latest (1.8) of it. If I open Safari browser inside the device, and I am able to see the available webpages in http://localhost:9221 but not from the hybrid app. Is it something I am really missing? Please help!

**Comment by artygus** [comment]
it means your app is not available for debugging, it's related to app configuration, probably provisioning profile. are you the dev of the app?

**Comment by csharsha** [comment]
No am not the dev, but I can ask for particular configuration to the dev if anything is missing while building the app. Can you tell me what exactly I should look for?

**Comment by csharsha** [comment]
No am not the dev, but I can ask for particular configuration to the dev if anything is missing while building the app. Can you tell me what exactly I should look for in provisioning profile?

**Comment by csharsha** [comment]
Thanks @artygus :) , I have asked my dev team, they have built the application with developer provisioning profile which has debugging capability. Thanks for your support. I hope this solution reach to as many as people who are scratching their heads thinking it as appium / ios_webkit_debug_proxy issue.

**Comment by viktorgogulenko** [comment]
@csharsha could you please share how your developers did that? I built an app with developer provisioning profile, but I'm not seeing any specific point how to add 'debugging' capability into provisioning. This is really crazy issue - on iOS simulator the same .ipa file is running perfectly with such logs: 

> [0-0] 2019-09-04T13:08:28.598Z INFO webdriver: RESULT iVBORw0KGgoAAAANSUhEUgAABGUAAAmECAIAAAAjR0TuAAAAAXNSR0IArs4c6...
> [0-0] 2019-09-04T13:08:33.925Z INFO webdriver: RESULT [ 'NATIVE_APP', 'WEBVIEW_23107.2' ]
> [0-0] 2019-09-04T13:08:33.927Z INFO webdriver: COMMAND getContexts()
> [0-0] 2019-09-04T13:08:33.927Z INFO webdriver: [GET] http://127.0.0.1:4723/wd/hub/session/42983aed-ab98-4a19-b512-29f06b0c78d9/contexts
> [0-0] 2019-09-04T13:08:34.022Z INFO webdriver: RESULT [ 'NATIVE_APP', 'WEBVIEW_23107.2' ]
> [0-0] 2019-09-04T13:08:34.023Z INFO webdriver: COMMAND switchContext("WEBVIEW_23107.2")
> [0-0] 2019-09-04T13:08:34.023Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/42983aed-ab98-4a19-b512-29f06b0c78d9/context
> [0-0] 2019-09-04T13:08:34.023Z INFO webdriver: DATA { name: 'WEBVIEW_23107.2' }


But when I'm trying to run on real device application starting, going to the page with webview and fails because no webview was found:

> [0-0] 2019-09-04T13:12:51.022Z INFO webdriver: COMMAND getContexts()
> [0-0] 2019-09-04T13:12:51.022Z INFO webdriver: [GET] http://127.0.0.1:4723/wd/hub/session/13704297-b0bf-4961-8324-81c81612e7de/contexts
> [0-0] 2019-09-04T13:12:51.032Z INFO webdriver: RESULT [ 'NATIVE_APP' ]
> [0-0] 2019-09-04T13:12:52.022Z INFO webdriver: COMMAND getContexts()
> [0-0] 2019-09-04T13:12:52.023Z INFO webdriver: [GET] http://127.0.0.1:4723/wd/hub/session/13704297-b0bf-4961-8324-81c81612e7de/contexts
> [0-0] 2019-09-04T13:12:52.032Z INFO webdriver: RESULT [ 'NATIVE_APP' ]
> [0-0] 2019-09-04T13:12:53.022Z INFO webdriver: COMMAND getContexts()
> [0-0] 2019-09-04T13:12:53.022Z INFO webdriver: [GET] http://127.0.0.1:4723/wd/hub/session/13704297-b0bf-4961-8324-81c81612e7de/contexts
> [0-0] 2019-09-04T13:12:53.032Z INFO webdriver: RESULT [ 'NATIVE_APP' ]
> [0-0] 2019-09-04T13:12:54.022Z INFO webdriver: COMMAND getContexts()
> [0-0] 2019-09-04T13:12:54.023Z INFO webdriver: [GET] http://127.0.0.1:4723/wd/hub/session/13704297-b0bf-4961-8324-81c81612e7de/contexts
> [0-0] 2019-09-04T13:12:54.033Z INFO webdriver: RESULT [ 'NATIVE_APP' ]

I've updated to the latest versions all possible dependencies but issue is still there. Thanks in advance for any help!

My libimobiledevice version is 1.2.0_3

**Comment by artygus** [comment]
@viktorgogulenko libimobiledevice should be built from master branch. you could also try new appium beta, it doesn't depend on libimobiledevice

**Comment by viktorgogulenko** [comment]
@artygus thanks for answer. I've installed libimobiledevice using brew. And it shows to me that latest version is 1.2.0_3. Should I install some other version instead?
Regarding Appium beta-version I've tried both 1.14.0-beta.2 and 1.14.2 (https://www.npmjs.com/package/appium?activeTab=versions) but issue is still there (even appeared more another issues which are not related to this one). I'm completely pissed off as it's completely crazy to be able to run same tests on simulator and can't run them on real devices.

**Comment by artygus** [comment]
@viktorgogulenko if you still can't see webviews, might be related to provisioning profiles, unfortunately I can't help you with this.

Regarding fresh versions of libimobile* libraries you could try these set of commands

```
brew uninstall --force libimobiledevice ios-webkit-debug-proxy usbmuxd
brew install --HEAD usbmuxd
brew install --HEAD libimobiledevice
brew install -s ios-webkit-debug-proxy
```

then if ios_webkit_debug_proxy will show webiews and the problem could be solved. 

PS. current release of iwdp doesn't support iOS 13 beta

**Comment by viktorgogulenko** [comment]
Thanks @artygus 
Unfortunately it didn't work for me :( Webview page appeared, Appium was trying to get context till the timeout but still just NATIVE_APP without webview. Hopefully @csharsha will help me with provisioning profile.

**Comment by kkallu** [comment]
Hi Team,

I'm facing similar issue with Appium 1.14 ,can you please help me in details ,how to resolve that ,Currently i'm able to switch from native to webview only when my chrome driver version and the chrome which is installed in the device are same.

Any detail explanations are highly appreciated .

Thanks in advance.
