### ISSUE TITLE
Compiling on CYGWIN creates exe that doesn't work

### ISSUE THREAD

**Issue by JonGabilondoAngulo** [google/ios-webkit-debug-proxy#287]
Hi,

I have compiled libimobiledevice, lisusbmuxd... and iOS-webkit-debug-proxy for Mac, Linux, Win. I have used CYGWIN for Windows. All the libimobiledevice tools work on Windows. ios-webkit-debug-proxy doesn't. It says the device is not found, ("log asks if usbmuxd is running"). usbmuxd is running , iTunes installed it and runs. The other commands, e.g ideviceinfo, are working.
It looks like you are building it with MinGW ? Anyone had success with CYGWIN ?
The binaries from the Release in this site are working for me, but I'd like to use the ones I build with CYGWIN.
Thanks.

**Comment by artygus** [comment]
I recommend using mingw64 for the task
