### ISSUE TITLE
Could not connect to lockdownd, error code -21. Exiting

### ISSUE THREAD

**Issue by pjodonova** [google/ios-webkit-debug-proxy#289]
Hi there,
 
I'm getting:
Listing devices on :9221
Could not connect to lockdownd, error code -21. Exiting.
Unable to attach 7165efd741ccc49558a88f6733b721441d1055e9 inspector

I tried some advice on another thread:
brew update
brew reinstall --HEAD libimobiledevice
brew reinstall -s ios-webkit-debug-proxy

But when I run brew reinstall --HEAD libimobiledevice I get "Error: invalid option: --HEAD"
I ran it without the --HEAD and still getting the same error that I posted up top.

MacOS 10.13.6 
Iphone 8 IOS 12.1.1

**Comment by artygus** [comment]
please look how to fix the problem on stackoverflow or look through the issues, it was answered many times
