### ISSUE TITLE
WebSocket frame length too large when requesting cached items

### ISSUE THREAD

**Issue by ticky** [google/ios-webkit-debug-proxy#29]
When requesting network responses which do not have a content-length, such as network responses returned from cache, the WebSocket response gives a ridiculous content-length (in this case, nearly a Petabyte - but it varies).

```
WebSocket connection to 'ws://192.168.7.82:9222/devtools/page/2' failed: WebSocket frame length too large: 898872230752645 bytes
```

As I can't see any code wherein `ios-webkit-debug-proxy` reads response headers, I can only presume that this is an issue with Safari's inspector WebSocket implementation, and that the limitation is suppressed when Safari sends data over USB.

This can be reproduced by following these steps;
1. Load any page which uses cachable resources (A web page using jQuery from Google's CDN is a good example)
2. Open the inspector (A) to monitor network requests
3. Open your browser's inspector (B) on the inspector page (A) which is pointed at the device
4. Reload the page
5. Click on the cached resource in inspector A (and note that the response headers do not include content-length)
6. Click "Preview" or "Response"
7. A WebSocket error such as the one above appears in the browser's error console (inspector B)

Is this likely to be something that can be fixed?

**Comment by artygus** [comment]
the issue seemed to affect 32bit machines only, see #150
