### ISSUE TITLE
Could not connect to lockdownd, error code -21

### ISSUE THREAD

**Issue by lrecknagel** [google/ios-webkit-debug-proxy#290]
* I had the issue mentioned in the title
* The _ Troubleshooting_ section in the repo with brew did not helped me
* What help instead was a comment from here: https://github.com/libimobiledevice/libimobiledevice/issues/587

* With the following steps:

```bash
brew update
brew uninstall --ignore-dependencies libimobiledevice
brew uninstall --ignore-dependencies usbmuxd
brew install --HEAD usbmuxd
brew unlink usbmuxd & brew link usbmuxd
brew install --HEAD libimobiledevice
brew link --overwrite libimobiledevice
brew install ideviceinstaller
brew link --overwrite ideviceinstaller
```

**Comment by artygus** [comment]
@lrecknagel did you resolve the issue?

**Comment by lrecknagel** [comment]
Yeah, sorry for leaving it open. Should I add a PR?

**Comment by artygus** [comment]
the snippet you provided looks like a resolution to a messed up environment, the point of what provided in readme and in the snippet is the same - use latest libimobiledevice

**Comment by lrecknagel** [comment]
Sure thats right. Then I leave it here as closed issue. Maybe other people have the same problem. Upgraded to mojave yesterday. Maybe was messed up because of that, even when `brew doctor` doesnt complain.

**Comment by Valehero** [comment]
This command is not working:
brew unlink usbmuxd & brew link usbmuxd

Should be:
brew unlink usbmuxd && brew link usbmuxd
