### ISSUE TITLE
ios-webkit-debug-proxy can not detect webview on real ios device

### ISSUE THREAD

**Issue by wangcodefind** [google/ios-webkit-debug-proxy#292]
**Environment**
macos sierra 10.12.6
xcode 9.2 ,
node 8.2.1
appium 1.10
real device ios 11.3 
ios-webkit-debug-proxy 1.8.3

Install IWDP with brew and start IWDP with desired_caps, startIWDP=true
connected real device to PC,
The real device Settings > Safari > Advanced > Web Inspector = ON

I run scripts on real ios device,when the page enter webviewpage，use getcontexts()
But can not get webview only native_app
Actual result:
> [debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
> [debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
> [debug] [RemoteDebugger] Page element JSON: []
> [debug] [iOS] No web frames found.
> [debug] [W3C (8edaea2a)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]

Start ios-webkit-debug-proxy in terminal:
```
issuserissuser$ ios_webkit_debug_proxy
Listing devices on :9221
Connected :9222 to iPhone8new (c2b1c13804867257faf463711e36498415a5****)
```
please someone know this problem help me,thanks!

**Comment by artygus** [comment]
please use search, there're many similar issues (e.g. #199, #286), most likely it's related to app invalid signing. to debug the ios app you need to have it properly signed

**Comment by artygus** [comment]
I believe the similar issues were answered many times before, closing
