### ISSUE TITLE
Not able to start IWDP on iPhone XR

### ISSUE THREAD

**Issue by kolyakrasnik** [google/ios-webkit-debug-proxy#293]
I'm trying to start ios-webkit-debug-proxy on iPhone Xr. Web inspector is turned on on device. 

There is appium logs :
`[debug] [iOS] Starting ios_webkit_debug_proxy at port 27753 on device 00008020-001A28822E88003A
[IWDP] Unknown file: 00008020-001A28822E88003A:27753
[IWDP] Unknown file: 00008020-001A28822E88003A:27753
[IWDP] Unknown file: 00008020-001A28822E88003A:27753
[debug] [iOS] Starting ios_webkit_debug_proxy at port 27753 on device 00008020-001A28822E88003A
[iOS] Error: Timed out waiting for ios_webkit_debug_proxy to open
[iOS]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[iOS]     at IWDP.start$ (/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/lib/iwdp.js:61:14)
[iOS]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[iOS]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[iOS]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[iOS]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at XCUITestDriver.start$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:397:13)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Error: Could not start ios_webkit_debug_proxy server: Timed out waiting for ios_webkit_debug_proxy to open
[XCUITest]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[XCUITest]     at XCUITestDriver.start$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:397:13)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
`

If I try in console i see the same issue: 
`$ios_webkit_debug_proxy -c 00008020-001A28822E88003A:20004`

`
Unknown file: 00008020-001A28822E88003A:20004
Unknown file: 00008020-001A28822E88003A:20004
Unknown file: 00008020-001A28822E88003A:20004
`

I'm able to start IWDP for iPhoneX and iPhone6s, but no results for iPhone Xr

There is lib version:
`ios_webkit_debug_proxy 1.8.1
Built with libimobiledevice v1.2.0, libplist v2.0.0
`

Environment:
MacOS: Mojave 10.14
XCode: Version 10.1

**Comment by artygus** [comment]
hi @kolyakrasnik you need to upgrade libimobiledevice to 1.2.1 please use search or checkout readme on the ways to do it
