### ISSUE TITLE
Support for iOS 12.2

### ISSUE THREAD

**Issue by Dan-Maor** [google/ios-webkit-debug-proxy#294]
It appears as if there was a change in the way Web Inspector works with iOS 12.2; when I try to check the inspectable pages none are retrieved (using the latest version from brew, 1.8.3).

It should be noted that as of the latest Mojave release the official Safari inspector is not working as well, however I am not able to test it with the latest Mojave beta since I can't upgrade my machine.

Your assistance will be highly appreciated.

Thanks,
Dan.

**Comment by carrollcai** [comment]
i have the same problem. https://www.zhihu.com/question/313614095

**Comment by artygus** [comment]
hi @Dan-Maor is it still an issue? and does it happen for both simulator and ios devices?

**Comment by oberhamsi** [comment]
i'm testing with an ios device and with the latest master from a few min ago i can now see the pages and open the inspector but nothing shows up. not even the URL in the address bar. i tried the default safari inspector and the chrome dev tools.

**Comment by artygus** [comment]
@oberhamsi check out readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

**Comment by oberhamsi** [comment]
thanks, i'm trying this now. chrome used to work before 12.2 with a few glitches.

**Comment by artygus** [comment]
oh then it could be something else

**Comment by artygus** [comment]
the messages looks good, meaning iwdp proxies messages. seems like some changes must be done in compatibility layer

can't promise when, but if I have some time anytime soon I'll take a look and ping you back

**Comment by imurchie** [comment]
On iOS 12.2 everything is wrapped in `Target` messages and events, and the rest of the protocol is not exposed.

**Comment by auchenberg** [comment]
Interesting set of changes. This is essentially Apple adopting the Target domains in DevTools Protocol. 

Work for mapping this to Chrome DevTools should probably land in https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/

**Comment by auchenberg** [comment]
Tracking in https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/138

**Comment by benmalka** [comment]
Why this is a closed issue? It seems that it's proxying the messages but there's still a problem with the protocol like @imurchie said

**Comment by artygus** [comment]
@benmalka protocol problems out of the scope of the utility, it's sole purpose is proxying requests from usbmuxd daemon over a websocket connection, please see readme

**Comment by fsiliadin** [comment]
It seems like some messages sent over ws induce unhandled exception on the embed browser or the proxy side:
 `Raw message {"id":1,"method":"Network.enable","params":{"maxTotalBufferSize":10000000,"maxResourceBufferSize":5000000}}
Raw message {"id":2,"method":"Page.enable"}
Raw message {"id":3,"method":"Page.getResourceTree"}
Raw message {"id":4,"method":"Profiler.enable"}
Raw message {"id":5,"method":"Runtime.enable"}
Raw message {"id":-1,"method":"Debugger.setBreakpointsActive","params":{"active":true}}
Raw message {"id":6,"method":"Debugger.enable"}
Raw message {"id":7,"method":"Debugger.setPauseOnExceptions","params":{"state":"none"}}
Raw message {"id":10,"method":"CSS.enable"}
Raw message {"id":11,"method":"Console.enable"}
Raw message {"id":12,"method":"Log.startViolationsReport","params":{"config":[{"name":"longTask","threshold":200},{"name":"longLayout","threshold":30},{"name":"blockedEvent","threshold":100},{"name":"blockedParser","threshold":-1},{"name":"handler","threshold":150},{"name":"recurringHandler","threshold":50},{"name":"discouragedAPIUse","threshold":-1}]}}
Raw message {"id":13,"method":"ServiceWorker.enable"}
Raw message {"id":14,"method":"Target.setAutoAttach","params":{"autoAttach":true,"waitForDebuggerOnStart":true}}
Raw message {"id":15,"method":"Target.setRemoteLocations","params":{"locations":[{"host":"localhost","port":9229}]}}
Raw message {"id":16,"method":"Target.setDiscoverTargets","params":{"discover":true}}
Raw message {"id":17,"method":"Page.setAutoAttachToCreatedPages","params":{"autoAttach":false}}
Raw message {"id":18,"method":"Page.setScriptExecutionDisabled","params":{"value":false}}
Raw message {"id":19,"method":"Rendering.setShowViewportSizeOnResize","params":{"show":true}}
Raw message {"id":20,"method":"Inspector.enable"}
Raw message {"id":-2,"method":"Runtime.evaluate","params":{"expression":"window.location.href"}}
(node:27928) UnhandledPromiseRejectionWarning: #<Object>
(node:27928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:27928) UnhandledPromiseRejectionWarning: #<Object>
(node:27928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Raw message {"id":23,"method":"Runtime.runIfWaitingForDebugger"}
Raw message {"id":-3,"method":"CSS.getAllStyleSheets","params":{}}
Raw message {"id":24,"method":"DOM.getDocument"}`

**Comment by annidy** [comment]
> https://github.com/appium/appium-remote-debugger/blob/master/lib/remote-debugger-message-handler.js#L174-L248

iOS didn't sends Target.targetCreated message if connect a JSContext, nor the WebView. How could I dump the Protocol that Safari send to iOS?

test with iOS 13.0.
