### ISSUE TITLE
error code -13. Exiting

### ISSUE THREAD

**Issue by Panhaiwei** [google/ios-webkit-debug-proxy#295]
~ ios_webkit_debug_proxy --debug
ss.add_server_fd(3)
Listing devices on :9221
ss.add_fd(4)
ss.add_server_fd(5)
ss.remove_server_fd(5)
ss.recv fd=4 len=982
ss.add_server_fd(5)
Could not connect to lockdownd, error code -13. Exiting.
ss.remove_server_fd(5)
Unable to attach 25cf7fcea677513cfa0f8490a8e4d5db20b5e025 inspector
^Css.remove_server_fd(3)
ss.remove_fd(4)

ask for help! Thank you.

**Comment by artygus** [comment]
https://github.com/google/ios-webkit-debug-proxy#could-not-connect-to-lockdownd-or-doesnt-work-with-ios10
