### ISSUE TITLE
when i used chrome inspect to link ios iphone xs, the chrome page is white screen?

### ISSUE THREAD

**Issue by carrollcai** [google/ios-webkit-debug-proxy#296]
![https://i.stack.imgur.com/kzQB7.png](https://i.stack.imgur.com/kzQB7.png)

Problem description: as you can see, when i used mac chrome inspect to link ios iphone xs, i can open the page, also the page is showing the DOM structure in the Elements, but the page is not rendered, the address bar is blank and the page is white screen.

Ps: i can use mac safari to debug the iphone safari, so the link in mac and ios iphone is ok. and the debug between mac and android iphone is ok. And i update my hosts. the link which [https://chrome-devtools-frontend.appspot.com/](https://chrome-devtools-frontend.appspot.com/) is not block. while i refresh the chrome page like [chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/2](chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/2)， the ios iphone also is refreshed.

Your assistance will be highly appreciated.

Thanks, carroll

**Comment by artygus** [comment]
hi @carrollcai please see readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools. remotedebug-ios-webkit-adapter project has the compatibility adapter for screencast
