### ISSUE TITLE
scoop install failed

### ISSUE THREAD

**Issue by ResponseState200** [google/ios-webkit-debug-proxy#297]
URL https://github.com/google/ios-webkit-debug-proxy/releases/download/v1.8.3/ios-webkit-debug-proxy-1.8.3-win64-bin.zip is not valid

system is window10

**Comment by artygus** [comment]
what do you mean not valid?

**Comment by ResponseState200** [comment]
run  scoop install ios-webkit-debug-proxy   
result  URL https://github.com/google/ios-webkit-debug-proxy/releases/download/v1.8.3/ios-webkit-debug-proxy-1.8.3-win64-bin.zip is not valid   

install failed   @artygus

**Comment by artygus** [comment]
please open the issue at scoop? url works fine, I'm not aware of scoop internals

**Comment by ResponseState200** [comment]
@artygus Thank

**Comment by artygus** [comment]
I see similar issues there  https://github.com/lukesampson/scoop/issues/2722 https://github.com/lukesampson/scoop/issues/2702
