### ISSUE TITLE
Error *** stack smashing detected ***: idevice_id terminated

### ISSUE THREAD

**Issue by justinmklam** [google/ios-webkit-debug-proxy#298]
## Environment
- Ubuntu 16.04.06 LTS
- Output from `ios_webkit_debug_proxy -V`:
```
ios_webkit_debug_proxy 1.8.3
Built with libimobiledevice v1.2.0, libplist v2.0.0
```
## Issue

Running `ios_webkit_debug_proxy` results in:

```
Listing devices on :9221
*** stack smashing detected ***: ios_webkit_debug_proxy terminated
Aborted (core dumped)
```

## Additional Info

Output from `ios_webkit_debug_proxy --debug`:

```
ss.add_server_fd(4)
Listing devices on :9221
ss.add_fd(5)
ss.add_server_fd(6)
ss.remove_server_fd(6)
ss.recv fd=5 len=974
ss.add_server_fd(6)
*** stack smashing detected ***: ios_webkit_debug_proxy terminated
Aborted (core dumped)
```

Executing `idevice_id -l` successfully returns the ID of my connected iPad (A1893).

**Comment by artygus** [comment]
hi @justinmklam you definitely need libimobiledevice from master, though "stack smashing detected" is something new, let's see upgrade will solve the problem

**Comment by justinmklam** [comment]
Thanks for the reply. I figured out the issue, I had installed both `libimobiledevice-dev` `libimobiledevice-utils` through `apt`, AND installed from source ([GitHub](https://github.com/libimobiledevice/libimobiledevice)). Uninstalling from `apt` fixed the gcc stack smashing error.
