### ISSUE TITLE
Only can get one webview on real device but there are two webviews except NATIVE_APP.

### ISSUE THREAD

**Issue by zhangliang1588** [google/ios-webkit-debug-proxy#299]
I can only get one webview on real  device  but there are two webviews except NATIVE_APP. But it's OK on simulator with Appium.

In the application there are two webviews and one is UIWebview and another is WKWebview. And the UIWebview is nested inside of WKWebview.

I am not able to get the UIWEbview on real device whereas in simulator I am easily getting both two webviews, but when I run the same set of scripts on real device it returns only  'NATIVE_APP' and WKWebview.

Code:
driver.getContextHandles();(Java)
only can get NATIVE_APP and WEBVIEW_xxx(WKWebview)

Environment
Appium version : 1.9.1
Desktop OS/version used to run Appium: OS-X 10.1 (10B61)
Mobile platform/version under test: iPhone 8 iOS - 12.1
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium Desktop

[caps]
platformName = "ios"
deviceName = "Automation Test"
platformVersion = "12.1"
app = "Apps/iOS/iOS.app"
automationName = "XCUITest"
udid = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
START_IWDP = "true"

I block on this issue for a long time, very hope getting help from your team side, thanks.

**Comment by artygus** [comment]
hi @zhangliang1588 do you see all webviews in Safari under develop tab? I believe not, if so I won't be available to help you, regarding the reasons it's hard to say why it's happening, AFAIR I've seen similar issue posted here, it was related to appium beta

**Comment by zhangliang1588** [comment]
hi @artygus I can see all webviews in Safari under develop tab.

**Comment by artygus** [comment]
when you run ios-webkit-debug-proxy in terminal, can you check if you see all of them at http://localhost:9221?

**Comment by artygus** [comment]
wait a second, so you see all of them in Safari even on real device? 

the "except native app" in the title of the issue suggests app misconfiguration, similar issues were posted a couple of times

**Comment by zhangliang1588** [comment]
Thanks for your fast response.
I have checked at http://localhost:9221 and found an interesting problem.
I start ios_webkit_debug_proxy in terminal and then login the app. At  http://localhost:9221 I can only see the html file of the WKWebview.
If I keep the app login status and kill the ios_webkit_debug_proxy process and restart it, at  http://localhost:9221 I can see two html files of the Webviews.

**Comment by zhangliang1588** [comment]
> wait a second, so you see all of them in Safari even on real device?
> 
> the "except native app" in the title of the issue suggests app misconfiguration, similar issues were posted a couple of times
> 
> UPD: title confused me, the description clarifies it. question about real device stands 🙂

Sorry for making it confusing.Actually the app has totally three Webviews if including Native_APP.
On iOS real device,I can only get the WKWebview, but can't get the UIWebview.

**Comment by artygus** [comment]
> If I keep the app login status and kill the ios_webkit_debug_proxy process and restart it, at http://localhost:9221 I can see two html files of the Webviews.

sorry for stupid question, but just in case, did you refresh the page? or reopened page only after restart?

**Comment by zhangliang1588** [comment]
> > If I keep the app login status and kill the ios_webkit_debug_proxy process and restart it, at http://localhost:9221 I can see two html files of the Webviews.
> 
> sorry for stupid question, but just in case, did you refresh the page? or reopened page only after restart?

Yes. After restart the ios_webkit_debug_proxy in terminal.I need refresh the page to get the new response.

**Comment by artygus** [comment]
sorry for not making it clear, what I asked for is: before you restart ios-webkit-debug-proxy did you try to refresh the page? webpage is not updated automatically on webview detection

**Comment by zhangliang1588** [comment]
> sorry for not making it clear, what I asked for is: before you restart ios-webkit-debug-proxy did you try to refresh the page? webpage is not updated automatically on webview detection

Yes.I tried to refresh the page several times before I restart ios_webkit_debug_proxy. But I still can only see one html file on the webpage.

**Comment by artygus** [comment]
great, now could you please send me the output of `ios-webkit-debug-proxy -d` when it has only one webview and another one after restart when it detects two

**Comment by zhangliang1588** [comment]
> great, now could you please send me the output of `ios-webkit-debug-proxy -d` when it has only one webview and another one after restart when it detects two

[iwdp_after_restart.log](https://github.com/google/ios-webkit-debug-proxy/files/2951456/iwdp_after_restart.log)
[iwdp_before_restart.log](https://github.com/google/ios-webkit-debug-proxy/files/2951457/iwdp_before_restart.log)

**Comment by artygus** [comment]
interesting, from iwdp_before_restart.log I see that it detects multiple webviews, but you're not able to see it in the webinterface. I'll analyze logs and get back to you probably tomorrow

**Comment by zhangliang1588** [comment]
> thanks for the logs! interesting, from iwdp_before_restart.log I see that it detects multiple webviews, but you're not able to see it in the webinterface. I'll analyze logs and get back to you probably tomorrow

Thanks a lot.

**Comment by zhangliang1588** [comment]
Hi @artygus,any updates about this?

**Comment by zhangliang1588** [comment]
@artygus sorry for asking again, are there any updates?Expect your feedback.Thanks.

**Comment by artygus** [comment]
@zhangliang1588 sorry for late reply, I believe PR #300 should fix your problem. please try master branch

    brew reinstall --HEAD

if you're on OS X

**Comment by zhangliang1588** [comment]
Thank you very much! It works!!
