### ISSUE TITLE
Unable to attach iOS 12.2

### ISSUE THREAD

**Issue by benjaminwood** [google/ios-webkit-debug-proxy#302]
I believe this is different than #294. I've got an iPhone XS Max running iOS 12.2. The device is detected over usb:

```
➜ idevice_id -l
00008020000315141ED8002E
```

But when I run `ios_webkit_debug_proxy`, I receive a message that it's unable to attach:

```
➜ ios_webkit_debug_proxy
Listing devices on :9221
No iPhone found, is it plugged in?: Operation now in progress
Unable to attach 00008020-000315141ED8002E inspector
```

I'm on Linux (Ubuntu/Bionic). I built `ios_webkit_debug_proxy` from master. I followed the readme/setup instructions initially, installing `libimobiledevice` from my package manager. When I encountered this issue, I went ahead and installed the following from source (master):

1. https://github.com/libimobiledevice/libplist.git
1. https://github.com/libimobiledevice/libusbmuxd.git
1. https://github.com/libimobiledevice/libimobiledevice.git

Yet the issue remains. Is anyone else experiencing this? I've done all I can think of, and yes, safari Web Inspector is enabled on my device!

Thanks!

**Comment by artygus** [comment]
Hi @benjaminwood, seems like iwdp fails to connect to usbmuxd. Did you remove libimobil* packages you had before building and installing libimobile* libraries?

**Comment by benjaminwood** [comment]
@artygus thanks for your response! I didn't remove anything before building from source. I've done that now and rebuilt the three libimobile libraries as well as ios_webkit_debug_proxy. Same result unfortunately.

Any guidance on additional steps I can take are appreciated, thanks again!

**Comment by artygus** [comment]
to be sure, could you please provide output of `ios_webkit_debug_proxy -V` also can you confirm  you're running usbmuxd daemon?

**Comment by benjaminwood** [comment]
Yes! Here it is:

```
➜  ios_webkit_debug_proxy -V
ios_webkit_debug_proxy 1.8.3
Built with libimobiledevice v1.2.1, libplist v2.0.0
```

Regarding `usbmuxd`:

With my device disconnected:
```
➜ ps -ax | grep usbmuxd
19137 pts/5    S+     0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn usbmuxd
```

With my device connected over USB
```
➜ ps -ax | grep usbmuxd
19187 ?        Ssl    0:00 /usr/sbin/usbmuxd --user usbmux --systemd
19222 pts/5    S+     0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn usbmuxd
```

Seems like usbmuxd is being started when it should.

**Comment by artygus** [comment]
what if you start in advance `/usr/sbin/usbmuxd` in one terminal window and run `ios_webkit_debug_proxy -d` in another?

**Comment by dcharbonnier** [comment]
Same issue for me
```
ios_webkit_debug_proxy -V
ios_webkit_debug_proxy 1.8.3
Built with libimobiledevice v1.2.1, libplist v2.0.0
```
```
➜  ios-webkit-debug-proxy git:(master) sudo /usr/sbin/usbmuxd --user usbmux -f
[17:42:08.337][3] usbmuxd v1.1.0 starting up
[17:42:08.338][3] Successfully dropped privileges to 'usbmux'
[17:42:08.343][3] Connecting to new device on location 0x1000a as ID 1
[17:42:08.343][3] Initialization complete
[17:42:08.343][3] Connected to v2.0 device 1 on location 0x1000a with serial number 00008020001B648802D8003A
```
```
➜  ios-webkit-debug-proxy git:(master) ios_webkit_debug_proxy -d
ss.add_server_fd(3)
Listing devices on :9221
ss.add_fd(4)
ss.add_server_fd(5)
ss.remove_server_fd(5)
ss.recv fd=4 len=958
ss.add_server_fd(5)
No iPhone found, is it plugged in?: Operation now in progress
ss.remove_server_fd(5)
Unable to attach 00008020-001B648802D8003A inspector
```

**Comment by artygus** [comment]
@dcharbonnier did you build usbmuxd/libusbmuxd from master too?

**Comment by artygus** [comment]
@benjaminwood did build usbmuxd from master?

**Comment by artygus** [comment]
closing since no reply from OP
