### ISSUE TITLE
Blank Devtools after selecting website

### ISSUE THREAD

**Issue by sewerynkalemba** [google/ios-webkit-debug-proxy#303]
Hey. I've established connection with my iPhone via `ios-webkit-debug-proxy`. When I access `localhost:9222` I see websites opened on my iPhone's Safari. 
![image](https://user-images.githubusercontent.com/37031328/55408471-5868df00-5560-11e9-8127-a03415548baf.png)

I want to debug a website, so I click hyperlink and it opens up devtools, but there is no content.
![image](https://user-images.githubusercontent.com/37031328/55408735-e93fba80-5560-11e9-8c05-fdc728a5034b.png)

These are errors I'm getting in debug mode:
```javascript
{ code: -32601,
  message: '\'Debugger\' domain was not found',
  data:
   [ { code: -32601, message: '\'Debugger\' domain was not found' } ] }
{ code: -32601,
  message: '\'Runtime\' domain was not found',
  data:
   [ { code: -32601, message: '\'Runtime\' domain was not found' } ] }
{ code: -32601,
  message: '\'Runtime\' domain was not found',
  data:
   [ { code: -32601, message: '\'Runtime\' domain was not found' } ] }
{ code: -32601,
  message: '\'Runtime\' domain was not found',
  data:
   [ { code: -32601, message: '\'Runtime\' domain was not found' } ] }
{ code: -32601,
  message: '\'CSS\' domain was not found',
  data:
   [ { code: -32601, message: '\'CSS\' domain was not found' } ] }
{ code: -32601,
  message: '\'Runtime\' domain was not found',
  data:
   [ { code: -32601, message: '\'Runtime\' domain was not found' } ] }
```

Version of phone and software:
```
iPhone: iOS 12.2
ios_webkit_debug_proxy: 1.8.3 (Built with libimobiledevice v1.2.1, libplist v2.0.0)
```

Thanks.

**Comment by artygus** [comment]
hi @sewerynkalemba, please check the readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

**Comment by dev-seahouse** [comment]
having same issue
