### ISSUE TITLE
Windows build instructions

### ISSUE THREAD

**Issue by dustinsoftware** [google/ios-webkit-debug-proxy#304]
I've taken a look at #53 to see if I can infer build instructions for Windows, is that documented somewhere? There's an iOS 12.2 fix on master that isn't released yet, so trying to build from source as a workaround.

Thanks!

**Comment by artygus** [comment]
Hi @dustinsoftware for windows build you can use mingw64 or cygwin, procedures are same as for linux build. Unfortunately it won't help with debugging via chrome dev tools, because there're are even more discrepancies in protocols in latest iOS release.

**Comment by artygus** [comment]
no plans to provide build instructions for windows atm
