### ISSUE TITLE
Inspectable pages list is empty for iOS 12.2

### ISSUE THREAD

**Issue by kolyakrasnik** [google/ios-webkit-debug-proxy#308]
List of inspectable pages is empty after IWDP has been started. 
Real device with iOS 12.2;
Xcode 10.2.1
`ios_webkit_debug_proxy 1.8.3
Built with libimobiledevice v1.2.1, libplist v2.0.0`
To start IWDP I use the next command:
`ios_webkit_debug_proxy -c 9f53aa9bd1638255f48ca6beac4285cae4f43eef:27753 -d`

Settings -> Safari -> Advanced -> Web Inspector is turned on.
<img width="1088" alt="Screen Shot 2019-04-29 at 19 43 30" src="https://user-images.githubusercontent.com/16190512/56915435-ca2c3e00-6ab6-11e9-81b1-f092cebaa062.png">

NOTE: I see webviews in Safari browser under Developer tab

**Comment by artygus** [comment]
hi @kolyakrasnik , did you build usbmuxd from master too?

what is the output of the command?

**Comment by kolyakrasnik** [comment]
Hi, @artygus!
It works fine after updating usbmuxd from master. Thanks for the help!
