### ISSUE TITLE
Only works when having more than 1 tab open

### ISSUE THREAD

**Issue by skerit** [google/ios-webkit-debug-proxy#310]
I never got the proxy to work until I read this line:

    Your attached iOS devices must have ≥1 open browser tabs

So while it clearly says "more or equal to 1 open browser tabs", I only had 1 tab open. As soon as I opened another it started working.

Should the `≥` become a simple `>`?

**Comment by artygus** [comment]
Having zero tabs also works, it will list your device, but won't show any inspectable pages. Please provide more information on the device (iOS version, whether it's simulator or real device, app or safari, etc.) and also `ios_webkit_debug_proxy -V` output

**Comment by artygus** [comment]
closing since no reply from OP
