### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by xiaomaiwang** [google/ios-webkit-debug-proxy#311]
Not allowed to load local resource: chrome-devtools://devtools/bundled/inspector.html?ws=127.0.0.1:9222/devtools/page/1
<img width="461" alt="WeChatd98f4d2b024315a6081d978b42ada21e" src="https://user-images.githubusercontent.com/16459417/57442029-b84c5700-727d-11e9-94a7-23d588afbeec.png">
<img width="905" alt="WeChat50791da893f555f546d049024dd989dc" src="https://user-images.githubusercontent.com/16459417/57442117-dd40ca00-727d-11e9-895d-d59cd29d5801.png">

**Comment by artygus** [comment]
just do exactly what it says, right click and open the link in new windows. this limitation comes from chrome itself. also check out readme for better debugging experience https://github.com/google/ios-webkit-debug-proxy#using-with-devtools
