### ISSUE TITLE
Version 1.8.5 missing windows build

### ISSUE THREAD

**Issue by rasa** [google/ios-webkit-debug-proxy#316]
Version 1.8.4 has ios-webkit-debug-proxy-1.8.4-win64-bin.zip, but version 1.8.5 is missing ios-webkit-debug-proxy-1.8.5-win64-bin.zip

**Comment by artygus** [comment]
no useful changes for windows platform in 1.8.5

**Comment by artygus** [comment]
on the other hand one is present though, device os version. thanks for bringing it up

**Comment by rasa** [comment]
Because the .zip file is missing, the scoop update function ("Excavator") reports an error. See https://github.com/lukesampson/scoop-extras/issues/2308

**Comment by artygus** [comment]
fixed https://github.com/google/ios-webkit-debug-proxy/releases
