### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xuguanqun** [google/ios-webkit-debug-proxy#318]
Couldn't find manifest for 'ios-webkit-debug-proxy'.

**Comment by artygus** [comment]
what does that supposed to mean?

**Comment by Nekomant** [comment]
@artygus 
Windows 10
run `scoop install ios-webkit-debug-proxy`
result: Couldn't find manifest for 'ios-webkit-debug-proxy'.

**Comment by artygus** [comment]
have been fixed in https://github.com/lukesampson/scoop-extras/pull/2504
