### ISSUE TITLE
Can´t get it to work

### ISSUE THREAD

**Issue by bootsmann95** [google/ios-webkit-debug-proxy#319]
Hello im trying to debug a iphone 8. 

I can get a connection betweeen the pc on windows and ios. 
but i can´t see anything in the inspector 

here is how it looks, 
what can be wrong? 

![image](https://user-images.githubusercontent.com/53180316/61633555-a16bad00-ac8f-11e9-8e18-2ae369b19cd7.png)

![image](https://user-images.githubusercontent.com/53180316/61633572-afb9c900-ac8f-11e9-93cc-79addeea0ce3.png)

![image](https://user-images.githubusercontent.com/53180316/61633598-b8120400-ac8f-11e9-8cd1-4acd1e6b6a3d.png)

![image](https://user-images.githubusercontent.com/53180316/61633618-c3652f80-ac8f-11e9-921e-5a32b8b720a5.png)

Thank you in advance. 
Anders

**Comment by artygus** [comment]
hi @bootsmann95, please check out readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

**Comment by bootsmann95** [comment]
@artygus  i did this

**Comment by artygus** [comment]
posting the issue to the tool's repo you're using would be more appropriate
