### ISSUE TITLE
ios_webkit_debug_proxy not working with iOS 13 Public Beta

### ISSUE THREAD

**Issue by abhilashsiyer** [google/ios-webkit-debug-proxy#320]
I have ios_webkit_debug_proxy and supporting tools (libimobiledevice, usbmux) installed on my MAC machine. The proxy is able to do the connection to an iOS 12 device , but when I try running it on a iOS 13 , I only get error as :

Unable to connect to XXX iPhone (xxxx-xxxxxx)
  Please verify that Settings > Safari > Advanced > Web Inspector = ON

Although, I have turned on the Web inspector, I am seeing the above error. Looks like an iOS 13 specific issue. In addition, I have Xode 11 Beta installed and set it as default XCode.  

Could anyone provide inputs for fix ?

**Comment by artygus** [comment]
hi @abhilashsiyer please look for similar issue before opening a new one, see #314. There's a PR to fix the issue #317, it's not ready for master just yet, but you could certainly build it from sources
