### ISSUE TITLE
webkit remote socket disconnects

### ISSUE THREAD

**Issue by mfestrada** [google/ios-webkit-debug-proxy#321]
Hello,

I am running e2e tests using WDIO with Appium on physical iOS devices.  When I run my full suite of tests, the remote debugger socket will drop.  (same as: https://github.com/google/ios-webkit-debug-proxy/issues/165)

I cannot share my full logs publicly, please contact me for details.

ios_webkit_debug_proxy's output when the drop occurs:

```bash
stderr: Page 27754/0 not found

stderr: Already sent close_frame

stderr: Page 27754/0 not found

stderr: Already sent close_frame
```

I am running:
iOS 12.1.2
ios_webkit_debug_proxy 1.8.5
Built with libimobiledevice v1.2.1, libplist v2.0.0

**Comment by artygus** [comment]
appium > 1.15 doesn't depend on iwdp https://github.com/appium/appium/pull/13368
