### ISSUE TITLE
Updating to newest iOS / MacOS format

### ISSUE THREAD

**Issue by EGreg** [google/ios-webkit-debug-proxy#323]
It seems the format for sending the data has changed. See this:

https://stackoverflow.com/questions/47460142/safari-web-inspector-is-blank

Have you updated the proxy to match? I get blank inspector in Chrome, and even the tab titles are not correct.

**Comment by spozsgai** [comment]
I have the same issue. :(

**Comment by goleary** [comment]
lots of people running into this issue over here: https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/166

Has anyone found a workaround?

**Comment by artygus** [comment]
I believe these changes must be handled by [dev tools adapter](https://github.com/google/ios-webkit-debug-proxy#using-with-devtools), 
if you're using remotedebug-ios-webkit-adapter and see a blank page check out https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/pull/149
