### ISSUE TITLE
DevTools.js:4931 Protocol Error: the message is for non-existing domain 'Target'

### ISSUE THREAD

**Issue by bknill** [google/ios-webkit-debug-proxy#324]
Hi, 

I've just done the update and I'm now getting a solid connection to the iPhone from a Linux machine. Great thanks! 

I can see the pages in the remote target and can load the front end. 

In Chrome I get these errors: 
```
DevTools.js:4965 Request with id = 180 failed. [object Object]
reportProtocolError @ DevTools.js:4965
132DevTools.js:4931 Protocol Error: the message is for non-existing domain 'Target'
```

And there is nothing in any of the pages, it's console I'm particularly interested in.

**Comment by artygus** [comment]
this should be handled by dev tools adapter, checkout readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools
