### ISSUE TITLE
Unable to connect with iPad Pro 10.5" on iPadOS 13.1

### ISSUE THREAD

**Issue by jaredyork** [google/ios-webkit-debug-proxy#327]
Hello everyone,

I'm having some difficulties trying to connect my iPad Pro 10.5" running iPadOS 13.1.  There error message is the following:

Unable to connect to Jared’s iPad (1518f84dd3281f1b070fadd7398eba5501be4b4b)
  Please verify that Settings > Safari > Advanced > Web Inspector = ON

The output of ios_webkit_debug_proxy -V is:
ios_webkit_debug_proxy 1.8.5
Built with libimobiledevice v1.2.1, libplist v2.0.0

Any help would be appreciated.  Thanks!

**Comment by artygus** [comment]
hi @jaredyork, ios 13 support is in progress

**Comment by jaredyork** [comment]
> hi @jaredyork, ios 13 support is in progress

Thanks @artygus.  How is development coming along?  Looking forward to trying this out on my Linux rig. :)

**Comment by artygus** [comment]
I hope to have PR ready by next Monday

**Comment by jaredyork** [comment]
Thanks for the update!  I will be checking it out then.

**Comment by githubdhina** [comment]
@artygus, will this change be available today?

**Comment by MikeVasylchenko** [comment]
+1 to question above

**Comment by ymn** [comment]
When will the update be available?

**Comment by artygus** [comment]
almost there, I think tomorrow beta will be out

**Comment by githubdhina** [comment]
Thanks for the update @artygus

**Comment by MikeVasylchenko** [comment]
thank you @artygus

**Comment by ymn** [comment]
thanks for the update.
