### ISSUE TITLE
Segmentation fault on libssl

### ISSUE THREAD

**Issue by kddlb** [google/ios-webkit-debug-proxy#331]
Target device is a 2018 iPad (6th gen) running iOS (iPadOS) 13.1.2.

```
kevin@ruxtower:~> ios_webkit_debug_proxy
Listing devices on :9221
Segmentation fault (core dumped)
```
GDB output:
```
kevin@ruxtower:~> gdb ios_webkit_debug_proxy
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ios_webkit_debug_proxy...
(gdb) run
Starting program: /usr/local/bin/ios_webkit_debug_proxy 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Listing devices on :9221

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7cff1d3 in ?? () from /usr/lib/libssl.so.1.1
(gdb) 
```

**Comment by artygus** [comment]
hi @kddlb, does idevice_ utilities work for you? did you build libimobiledevice with openssl support?

**Comment by kddlb** [comment]
I used libimobiledevice as provided by Arch Linux. I installed the git versions from AUR and it seems to work... it lists the debuggable tabs, but I can't connect to any. Seems like a different issue now.

**Comment by nobody-65534** [comment]
I have the exact same issue when lauching debug proxy on Ubuntu 19.10 with an iOS 13.2 device attached. 
```
foo@local:~$ ios_webkit_debug_proxy 
Listing devices on :9221
Segmentation fault (core dumped)

foo@local:~$ gdb ios_webkit_debug_proxy 
GNU gdb (Ubuntu 8.2.91.20190405-0ubuntu3) 8.2.91.20190405-git
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ios_webkit_debug_proxy...
(gdb) run
Starting program: /usr/local/bin/ios_webkit_debug_proxy 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Listing devices on :9221

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f139ef in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
```

I tried the apt-installed `libimobiledevice` and the one I built from source on github (I believe it uses openssl by default), both result the same error. 
The idevice utilities work well, they identify my device with no problem.

**Comment by bencarp** [comment]
For anyone still getting this error: After recompiling `libimobiledevice` and `usbmuxd` from their git sources and not having any success, I managed to get it to work simply by running **`sudo ldconfig`** again, which apparently doesn't happen automatically when running `sudo make install`.

**Comment by nolanlawson** [comment]
I'm seeing what is apparently the same error on Ubuntu 20.04 with an iPod Touch running iOS 13.4.1. Sometimes it crashes with the segfault, sometimes it says:

```
Listing devices on :9221
ssl connection failed!: Success
Unable to attach <id> inspector
```

Here is the segfault in gdb:

```
(gdb) run
Starting program: /usr/local/bin/ios_webkit_debug_proxy
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Listing devices on :9221

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f1acb6 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
```

@bencarp's suggestion of `sudo ldconfig` didn't work for me, although I didn't try installing anything from source as described.

http://localhost:9221/ shows no iOS devices, but `idevice_id -l` does list the device.

**Comment by nolanlawson** [comment]
Update: installing `libimobiledevice` from source apparently fixes it. I can see my device listed now.

**Comment by nolanlawson** [comment]
For anyone looking for a complete solution, here's what worked for me on Ubuntu 20.04:

```bash
sudo apt install python-dev autoconf automake libusb-dev \
  libusb-1.0-0-dev libplist-dev libplist++-dev usbmuxd libtool \
  libimobiledevice-dev libssl-dev libimobiledevice-utils

git clone https://github.com/libimobiledevice/libimobiledevice.git
cd libimobiledevice
./autogen.sh
make
sudo make install
cd ..

git clone https://github.com/google/ios-webkit-debug-proxy.git
cd ios-webkit-debug-proxy
./autogen.sh
make
sudo ldconfig
sudo make install
```

You may also have to plug/unplug the iOS device a few times and click the "Trust" button. But eventually you'll see the device listed on localhost:9221.

**Comment by sriksm19** [comment]
@nolanlawson i keep getting this error: configure: error: Package requirements (libusbmuxd-2.0 >= 2.0.2) were not met:

No package 'libusbmuxd-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

and when i try to install that package manually from source, i get the same for another package and so on.

> For anyone looking for a complete solution, here's what worked for me on Ubuntu 20.04:
> 
> ```shell
> sudo apt install python-dev autoconf automake libusb-dev \
>   libusb-1.0-0-dev libplist-dev libplist++-dev usbmuxd libtool \
>   libimobiledevice-dev libssl-dev libimobiledevice-utils
> 
> git clone https://github.com/libimobiledevice/libimobiledevice.git
> cd libimobiledevice
> ./autogen.sh
> make
> sudo make install
> cd ..
> 
> git clone https://github.com/google/ios-webkit-debug-proxy.git
> cd ios-webkit-debug-proxy
> ./autogen.sh
> make
> sudo ldconfig
> sudo make install
> ```
> 
> You may also have to plug/unplug the iOS device a few times and click the "Trust" button. But eventually you'll see the device listed on localhost:9221.

while trying to install libimobiledevice, i keep getting this error: configure: error: Package requirements (libusbmuxd-2.0 >= 2.0.2) were not met:

No package 'libusbmuxd-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

and when i try to install that package manually from source, i get the same for another package and so on.

**Comment by totalolage** [comment]
I have tried everything suggested so far. I'm getting the exact same segfault and SSL error as @nolanlawson . I'm on Arch-lts, there is an AUR package but its install is broken (it never satisfies a dependency which is blatantly present).
Do you have any other ideas as to how to solve this? I need to get it working for work.

**Comment by artygus** [comment]
@totalolage I guess you can always opt for building from sources 🤔

**Comment by totalolage** [comment]
> @totalolage I guess you can always opt for building from sources

That is the first thing I tried, I built everything relating to `libimobiledevice` then this. The issue persists. Using the package from aur was option B.

**Comment by artygus** [comment]
did you also build ios-webkit-debug-proxy from sources?

**Comment by artygus** [comment]
I'm not using linux, messages above suggests is does work on ubuntu, I don't see why it wouldn't on arch linux. probably related to messed up environment in some way 🤔 you could try docker 💡

**Comment by totalolage** [comment]
> did you also build ios-webkit-debug-proxy from sources?

Yes, I did. I'll try docker, thank you for the suggestion.

**Comment by artygus** [comment]
@totalolage look for --device option, good stackoverflow answer can be found here https://stackoverflow.com/a/24231872
