### ISSUE TITLE
Inspection "domains" not found

### ISSUE THREAD

**Issue by kddlb** [google/ios-webkit-debug-proxy#332]
Target device, again, is a 2018 iPad (6th gen) running iOS (iPadOS) 13.1.2. Target app is Safari.
Inspecting the WebSockets between the inspector and the proxy, it seems that it's not finding the inspection "domains".

```json
{"error":{"code":-32601,"message":"'CSS' domain was not found","data":[{"code":-32601,"message":"'CSS' domain was not found"}]},"id":22}
{"error":{"code":-32601,"message":"'Console' domain was not found","data":[{"code":-32601,"message":"'Console' domain was not found"}]},"id":23}
{"error":{"code":-32601,"message":"'Inspector' domain was not found","data":[{"code":-32601,"message":"'Inspector' domain was not found"}]},"id":24}
{"error":{"code":-32601,"message":"'Database' domain was not found","data":[{"code":-32601,"message":"'Database' domain was not found"}]},"id":25}
``` 
and so on...

**Comment by artygus** [comment]
please check out readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

**Comment by kddlb** [comment]
I'm getting the same errors in both Chrome and VS Code.

**Comment by artygus** [comment]
@kddlb mapping dev protocols is out of the scope of this utility, it's sole job is to purpose webkit messages via websockets
