### ISSUE TITLE
ios-webkit-debug-proxy doesn't list my iphone  simulator with ios 13.1

### ISSUE THREAD

**Issue by Vpuertol** [google/ios-webkit-debug-proxy#335]
Environment

ios_webkit_debug_proxy 1.8.5
Built with libimobiledevice v1.2.1, libplist v2.0.0

Xcode 11.1, ios simulator 13.1

As you can see ios-webkit-debug-proxy is stuck listing connected devices and none appears.

![Captura de pantalla 2019-10-31 a las 13 04 52](https://user-images.githubusercontent.com/38435603/67945688-d1581400-fbdf-11e9-96c4-6e7f1aa76c87.png)

If I turn on an iPhone 7 simulator with ios 10.3.1 I can see it connected

![Captura de pantalla 2019-10-31 a las 13 26 10](https://user-images.githubusercontent.com/38435603/67946955-c94da380-fbe2-11e9-9502-67cbfeceba60.png)

**Comment by artygus** [comment]
see #250

**Comment by Vpuertol** [comment]
I saw the thread but does it means that is impossible work with xcode simulator and ios-webkit-debug-proxy since xcode version 9.3-beta3?

**Comment by artygus** [comment]
it means there's no good way to get a sim sockets AFAIK, no plans to introduce hacky work arounds atm. what you can do is run `ios_webkit_debug_proxy -s unix:<path to sim socket>`, socket address could be found using `lsof` command, for see https://github.com/appium/appium-ios-simulator/pull/145/files for more details
