### ISSUE TITLE
ios-webkit-debug-proxy 1.8.5_1 cant't connect Ipados13 devices

### ISSUE THREAD

**Issue by ylkjick532428** [google/ios-webkit-debug-proxy#337]
ios_webkit_debug_proxy -f chrome-devtools://devtools/bundled/inspector.html
Listing devices on :9221
Unable to connect to you’s iPad (137feca4073f253b\)
  Please verify that Settings > Safari > Advanced > Web Inspector = ON

**Comment by artygus** [comment]
please use search instead opening duplicates
