### ISSUE TITLE
error on make, ubuntu 16

### ISSUE THREAD

**Issue by trainingnote** [google/ios-webkit-debug-proxy#341]
I have an error when I run make, I can list my device and web inspector is on.

./autogen.sh
make

`webinspector.c:95:32: error: field ‘type’ has incomplete type
   enum idevice_connection_type type;
                                ^~~~
webinspector.c: In function ‘idevice_connection_get_ssl_session’:
webinspector.c:117:24: error: ‘CONNECTION_USBMUXD’ undeclared (first use in this function)
   if (!c || c->type != CONNECTION_USBMUXD || c->data <= 0) {
                        ^~~~~~~~~~~~~~~~~~
`

**Comment by artygus** [comment]
please look for similar issues before posting a new one, master branch should be built with masters branches of libimobile-, usbmuxd- libraries

**Comment by fadykstas** [comment]
@artygus have same issue on Ubuntu 18.04.3 LTS, could you explain how to solve it? 

```
webinspector.c:95:32: error: field ‘type’ has incomplete type
   enum idevice_connection_type type;
                                ^~~~
webinspector.c: In function ‘idevice_connection_get_ssl_session’:
webinspector.c:117:24: error: ‘CONNECTION_USBMUXD’ undeclared (first use in this function)
   if (!c || c->type != CONNECTION_USBMUXD || c->data <= 0) {
                        ^~~~~~~~~~~~~~~~~~
webinspector.c:117:24: note: each undeclared identifier is reported only once for each function it appears in
Makefile:569: recipe for target 'webinspector.lo' failed
make[1]: *** [webinspector.lo] Error 1
make[1]: Leaving directory '/home/.../ios-webkit-debug-proxy/src'
Makefile:405: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

**Comment by artygus** [comment]
hi @fadykstas check out message above, also #340
