### ISSUE TITLE
Not receiving information in DevTools from page

### ISSUE THREAD

**Issue by SethRedwine** [google/ios-webkit-debug-proxy#343]
I'm running this tool on OS X 10.15.1 (19B88) with an iPad running iOS 13.2.3

I've gotten the tool set up and running fine and I can even get the iPad to connect and display the list of pages I'm trying to debug. However, when I open up the DevTools for a specific page everything is blank - no captured http requests, no console log, no html elements, etc. Nothing seems to be coming through.

There doesn't seem to be any erroneous output anywhere, but I'd be happy to provide any more details you might need.

**Comment by artygus** [comment]
hi @SethRedwine check out read me https://github.com/google/ios-webkit-debug-proxy#using-with-devtools
