### ISSUE TITLE
iOS13 ios-webkit-debug-proxy will disconnected Once the Json is over 200k

### ISSUE THREAD

**Issue by liu6x6** [google/ios-webkit-debug-proxy#344]
hi there 
today i found an issue on iOS13, and i am using the wdp_client.html to send json string to the safari. Once the JSON size is over than 200KB, then iOS-webkit-debug-proxy will disconnected.

the error logs like:
_

> ss.sendq<0x7fb70d504630> new fd=10 recv_fd=14 length=200416, prev=<0x0>
> ss.sendq<0x7fb70d504630> disable recv_fd=14
> ss.sendq<0x7fb70d504630> resume send to fd=10 len=200416
> ssl sendq retry failed: Undefined error: 0
> ss.remove_fd(10)
> Disconnected :9222 from xiao’s iPhone (9cd6921d1f5f908f06f295b52b0346aacca81234)
> ss.remove_server_fd(5)
> ss.remove_fd(14)
> ss.remove_fd(9)
> ss.remove_fd(12)
> ss.remove_fd(11)
> ss.remove_fd(13)
> ^Css.remove_server_fd(3)
> ss.remove_fd(4)

_

my json command look like:

{"id":8,"method":"Target.sendMessageToTarget","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"message":"{\"method\":\"Runtime.evaluate\",\"params\":{\"expression\":\"var func = function(){console.debug(\\\"touch\\\");console.debug(\\\"touch\\\"); ...
;}, true);};func();\"},\"id\":8}","id":8,"targetId":"page-6"}} 

I add lot of console.debug(\\\"touch\\\"); to make sure the json size is big enough.
it's the SSL problem? how can i fix this?

**Comment by liu6x6** [comment]
After some inverstgation i found there are 2 problems. hope someone can tell me the reason.
The problem is at socket_manager.c sm_send function

1. Once the data length bigger than 131000 then SSL_write will always return -1
2. So i split the data size. i send 130000 each time. But the last one (the size is small then 130000) will always return -1, so I add a sleep(1) after the  SSL_write. And then it working.

The code like this:
	long sendLength = tail - head;
          if (sendLength >= 130000) {
              sendLength = 130000;
          }
          sent_bytes = SSL_write((SSL *)ssl_session, (void*)head, sendLength);
          sleep(1);
 
I am not good at C and ssl. Hope someone could help me.

**Comment by artygus** [comment]
hi @liu6x6 interesting observation 🤔 I got back from holidays, will take a look possible this weekend. what OS are you using?

**Comment by ElielCohen** [comment]
Hi Artygus, I'm working with @liu6x6  and I've experienced similar issue on any platform, macOS, linux, and windows. The issue is happening as soon as the idevice is running on iOS13+. Any idea what have changed there ? I know that from iOS13+ we are obliged to use SSL for the web inspector communication it's probably linked.
