### ISSUE TITLE
Ios 13 the inspect page is blank

### ISSUE THREAD

**Issue by dihak** [google/ios-webkit-debug-proxy#350]
![image](https://user-images.githubusercontent.com/10445482/72776302-503f7480-3c44-11ea-8518-b8b3f16635ff.png)

After click the link

![image](https://user-images.githubusercontent.com/10445482/72776317-5afa0980-3c44-11ea-8c19-e9c879c70611.png)

**Comment by artygus** [comment]
hi @dihak please check out closed issues
