### ISSUE TITLE
[RemoteDebugger] Page element JSON: [] [debug] [iOS] No web frames found.

### ISSUE THREAD

**Issue by siddhantraut** [google/ios-webkit-debug-proxy#352]
**No web frames found.**
WebView are not getting listed....... everything looks good

**ios :12.3.1
ios_webkit_debug_proxy 1.8.5
Appium v1.13.0**
Capabilities 

Appium v1.13.0 creating new XCUITestDriver (v2.113.2) session
[Appium] Capabilities:
[Appium]   platformName: ios
[Appium]   wdaStartupRetries: 4
[Appium]   wdaStartupRetryInterval: 20000
[Appium]   app: /Users/x/x/x/rtyyhhh-x-tests/ipa/xxxxxx_3.ipa
[Appium]   automationName: XCUITest
[Appium]   deviceName: iPhone
[Appium]   fullReset: false
[Appium]   language: en
[Appium]   locale: en_CA
[Appium]   noReset: true
**[Appium]   startIWDP: true**
[Appium]   udid: 189588458cc6ecfad1aaaaaaaaaaaaaaaa
[Appium]   xcodeOrgId: saasassaasass
[Appium]   xcodeSigningId: iPhone Developer

**Logs**:
[debug] [iOS] Starting ios_webkit_debug_proxy at port 27753 on device 189588458cc6ecfad1aaaaaaaaaaaaaaaa
[debug] [BaseDriver] Event 'iwdpStarted' logged at 1584132123344 (16:42:03 GMT-0400 (Eastern Daylight Time))
[debug] [XCUITest] Started ios_webkit_debug proxy server at: http://localhost:27753

[debug] [iOS] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false 
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray. Host: 'localhost', port: '27753'
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
**[debug] [RemoteDebugger] Page element JSON: []
[debug] [iOS] No web frames found.**
[debug] [W3C (66912abd)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/66912abd-b64f-418b-a67d-e69003c5aa74/contexts 200 18 ms - 24
[HTTP] 
**available contextNames 
NATIVE_APP**

**Comment by artygus** [comment]
hi @siddhantraut, what does `ios_webkit_debug_proxy -V` show? what OS do you use?

PS. I see you're using old appium, new versions doesn't use iwdp at all

**Comment by siddhantraut** [comment]
> hi @siddhantraut, what does `ios_webkit_debug_proxy -V` show? what OS do you use?
> 
> PS. I see you're using old appium, newer versions doesn't use iwdp at all        

Mac :10:13
 ios :12.3.1
ios_webkit_debug_proxy 1.8.5
Appium v1.13.0

**Comment by artygus** [comment]
@siddhantraut  can you provide the output of `ios_webkit_debug_proxy -V`?

**Comment by siddhantraut** [comment]
> @siddhantraut can you provide the output of `ios_webkit_debug_proxy -V`?
> it would show whether it's compiled with latest libimobiledevice which unfortunately has to be built from sources, b/c there were no releases after 1.2.0 but a lot of things changed, checkout readme or closed issues for instructions

**ios_webkit_debug_proxy 1.8.5
Built with libimobiledevice v1.2.1, libplist v2.1.0**

**Comment by siddhantraut** [comment]
FYI...
if I open safari any web url i can see it in Developer > DeviceName > web app url.

but when open Native app webView safari not display Developer > DeviceName > web app url.

**Comment by artygus** [comment]
sounds like you have issues with provisioning profile, you need to obtain a developer profile

**Comment by siddhantraut** [comment]
> sounds like you have issues with provisioning profile, you need to obtain a developer profile for the app to debug it's webviews

I don't think  so @artygus, as I am able to move till webView after launching app and performing some steps.

1. Launch app [Native_View]
2. Click on sign in button [Native_View]
3. Here WebView comes in picture and i am getting "[iOS] No web frames found"

**Comment by artygus** [comment]
@siddhantraut if you don't see view under developer tab in Safari, iwdp won't be able to detect it either
