### ISSUE TITLE
Runtime' domain was not found

### ISSUE THREAD

**Issue by CankingApp** [google/ios-webkit-debug-proxy#354]
{\"code\":-32601,\"message\":\"'Runtime' domain was not found\"}],\"message\":\"'Runtime' domain was not found\"}

run js  on iOS 13+ get the error above. Any one has the solution？ help～

**Comment by artygus** [comment]
please check out readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

**Comment by CankingApp** [comment]
> please check out readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

Thx，I will try it now.

**Comment by wwwyyy1** [comment]
> > please check out readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools
> 
> Thx，I will try it now.

Hi, did you solved this problem? I met this problem, but have no idea.
