### ISSUE TITLE
Start the error

### ISSUE THREAD

**Issue by ws745630** [google/ios-webkit-debug-proxy#356]
After successful installation,I failed to execute the  ` ios_webkit_debug_proxy` command，
`dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/opt/libimobiledevice/lib/libimobiledevice.6.dylib
  Reason: image not found
Abort trap: 6`

**Comment by artygus** [comment]
the error states that openssl utility was built with is missng, try reinstalling brew openssl
