### ISSUE TITLE
Can't open chrome-devtools:// address

### ISSUE THREAD

**Issue by lemchen** [google/ios-webkit-debug-proxy#357]
when i use localhost:9222 to connect to iPhone

Inspectable pages for iPhone:
https://slkjdflksjdfl.com
Note: Your browser may block1,2 the above links with JavaScript console error:
  Not allowed to load local resource: chrome-devtools://...
To open a link: right-click on the link (control-click on Mac), 'Copy Link Address', and paste it into address bar.

after i copy the link address, and paste it into address bar , the chrome just go to google search page.
how to use it correctly.

**Comment by artygus** [comment]
check out readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools https://github.com/google/ios-webkit-debug-proxy#using-with-devtools
