### ISSUE TITLE
Unable to connect to chrome-devtools-frontend.appspot.com:80

### ISSUE THREAD

**Issue by vanswang** [google/ios-webkit-debug-proxy#358]
Hi, I have a problem, and I need your help.

Env:
PC: Windows 10 (10.0.18363 Build 18363)
Chrome: Google Chrome 83.0.4103.61
iwdp: v1.8.6
mobile: iPhone X + ios 13.4.1

1. Windows can connect the iphone:
`Listing devices on :9221
Connected :9222 to iPhone X (0f27191661cb9)`

2. Open `http://localhost:9221/`:
`iOS Devices:
localhost:9222 - iPhone X`

3. I click the `localhost:9222`, chrome open this page:
`Inspectable pages for iPhone X:
https://m.baidu.com/?from=844b&vit=fps`

4. Then I click the `https://m.baidu.com/?from=844b&vit=fps` (http://localhost:9222/devtools/devtools.html?ws=localhost:9222/devtools/page/1), I find this error:
`Unable to connect to chrome-devtools-frontend.appspot.com:80`

5. I follow this issue: [#176 ,](https://github.com/google/ios-webkit-debug-proxy/issues/176) but it isn't work:
I install the `https://github.com/artygus/webkit-webinspector`, but it open a empty page.

6. I open this URL, but it is a empty page: 
`chrome-devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1`

What can I do for the problem?

Thank you very much.

**Comment by Zohar727** [comment]
I have the same problem

**Comment by github177** [comment]
> I have the same problem

I haven't heard back for a month......

**Comment by artygus** [comment]
hi @github177 did you try using other inspectors https://github.com/google/ios-webkit-debug-proxy#chrome-devtools? built in proxied url is not useful for debugging anyways.

**Comment by github177** [comment]
> hi @github177 did you try using inspector adapters https://github.com/google/ios-webkit-debug-proxy#chrome-devtools? built in proxied url is not useful for debugging anyways.

I will have a try, then get back to you.

**Comment by carlosjunod** [comment]
hi @vanswang .. did you find the issue?

**Comment by supersonictw** [comment]
Try this:
<devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1>

**Comment by Redemption198** [comment]
> 
> 
> Try this:
> 
> Command:
> `ios_webkit_debug_proxy -f devtools://devtools/bundled/inspector.html`
> 
> URL:
> `devtools://devtools/bundled/inspector.html?ws=localhost:9222/devtools/page/1`
> 
> The solution is according to
> https://stackoverflow.com/questions/62066780/chrome-devtools-opens-as-a-search-rather-then-the-dev-tools-themselves.

I can't get it to work on Windows using Chrome/Chromium, i get a bunch of errors in console from protocol_client.js.
I'm currently testing iOS 15.

**Comment by WANNANANANA** [comment]
2023年了还没解决。。。

**Comment by vanswang** [comment]
> 2023年了还没解决。。。

我已经放弃不用了

**Comment by artygus** [comment]
please see the readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools
