### ISSUE TITLE
"Unable to link with libimobiledevice" when running autogen, can't run make (no targets)

### ISSUE THREAD

**Issue by dandv** [google/ios-webkit-debug-proxy#363]
After managing to [install libplist](https://github.com/libimobiledevice/libplist/issues/165), I get this error when running autogen:

$ ./autogen.sh 
libtoolize --force
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
aclocal
autoheader
automake --add-missing
configure.ac:13: installing './compile'
configure.ac:8: installing './missing'
examples/Makefile.am: installing './depcomp'
autoconf
./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libimobiledevice... yes
checking for libplist... yes
checking for openssl... yes
checking for plist_to_xml in -lplist-2.0... yes
checking for log10 in -lm... yes
checking for idevice_new in -limobiledevice-1.0... no
configure: error: in `/home/dandv/prg/ios-webkit-debug-proxy':
configure: error: *** Unable to link with libimobiledevice

**Comment by artygus** [comment]
hi @dandv, you need to have libimobiledevice and libusbmuxd installed too
