### ISSUE TITLE
Brew install failed

### ISSUE THREAD

**Issue by jacksun101** [google/ios-webkit-debug-proxy#365]
`brew install --HEAD ios-webkit-debug-proxy`

> Updating Homebrew...
> ==> Downloading https://github.com/google/ios-webkit-debug-proxy/commit/7195575f
> Already downloaded: /Users/jacksun/Library/Caches/Homebrew/downloads/621458fa4464858eea87bb6a35f04a883378f0c583232c13d55c0fff02ec06f6--7195575fc5981c9c92ad337029ee90d997551369.patch
> ==> Cloning https://github.com/google/ios-webkit-debug-proxy.git
> Updating /Users/jacksun/Library/Caches/Homebrew/ios-webkit-debug-proxy--git
> ==> Checking out branch master
> Already on 'master'
> Your branch is up to date with 'origin/master'.
> HEAD is now at 6d499e0 Merge pull request #361 from alebcay/libplist-update
> ==> Patching
> ==> Applying 7195575fc5981c9c92ad337029ee90d997551369.patch
> patching file configure.ac
> Hunk #1 FAILED at 17.
> 1 out of 1 hunk FAILED -- saving rejects to file configure.ac.rej
> Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/ios-webkit-debug-proxy--patch-20200701-6605-emh04q/7195575fc5981c9c92ad337029ee90d997551369.patch` exited with 1.
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Discourse, Twitter or IRC.

**Comment by artygus** [comment]
fixed by https://github.com/Homebrew/homebrew-core/pull/57426
