### ISSUE TITLE
How to see all Logs?

### ISSUE THREAD

**Issue by simonluebker** [google/ios-webkit-debug-proxy#367]
## Question
Thank you for this awesome tool.
Is it possible to see all logs written to the console by the app? 
In my ionic based app i write some logs to the console. But these logs won't appear on the remote inspect console. The only thing i can do is during the start of the app to enable printing the logs to the shell i startet the server. In the remote inspect console i only see the xhr and http logs. 

best regards

**Comment by artygus** [comment]
hi @simonluebker, do you mean javascript console.log? you can see raw messages between iwdp and usbmuxd using `--debug` flag
