### ISSUE TITLE
Stopped Working after iOS v 13.3 upgrade

### ISSUE THREAD

**Issue by FightingRicardo** [google/ios-webkit-debug-proxy#368]
Hi, My ios version is 13.3. When I tried to inspect a web in my safari using post: 9222. It prints 'HTTP/1.1 404 Not Found'.

**Comment by artygus** [comment]
hi @FightingRicardo, what is the output of

`ios_webkit_debug_proxy -V`

just curious, what do you need this utility if you have safari installed?

**Comment by AdaRoseCannon** [comment]
I have the same issue:

Output:

```
ios_webkit_debug_proxy 1.8.8
Built with libimobiledevice v1.3.1, libplist v2.2.1
```

Issue:

Could not start com.apple.webinspector!: No error

**Comment by artygus** [comment]
@AdaRoseCannon can you confirm that Settings -> Safari -> Advanced -> Web Inspector is on?

**Comment by AdaRoseCannon** [comment]
Yep, confirmed.

**Comment by artygus** [comment]
did you try to build from sources both libimobiledevice and ios-webkit-debug-proxy? did you install utility via package manager?

**Comment by AdaRoseCannon** [comment]
Installed via scoop

**Comment by artygus** [comment]
oh, it's windows! do you have latest itunes installed? and can you confirm you have Apple Mobile Device Support and Apple Application Support applications in control panel -> programs and features? does the problem occcur to all ios devices you tried?

**Comment by AdaRoseCannon** [comment]
I installed the latest iTunes as the guide suggested.

It seems neither of those two programs also got installed. How do I install
those if iTunes did not do it?

**Comment by AdaRoseCannon** [comment]
I reinstalled itunes and those programs are now added.

I wonder if it needed to be installed twice or something to work.

**Comment by goleary** [comment]
I ended up here because running this command: `ios_webkit_debug_proxy`

results in this:
```
Listing devices on :9221
device_listener: connect function failed with        error 10061
No device found, is it plugged in?
```

After reading through this issue, @artygus I saw what you wrote:

>oh, it's windows! do you have latest itunes installed? and can you confirm you have Apple Mobile Device Support and Apple Application Support applications in control panel -> programs and features? does the problem occcur to all ios devices you tried?

I did not have iTunes installed because there is no mention of it in the readme.
