### ISSUE TITLE
Empty console

### ISSUE THREAD

**Issue by rusicsemenov** [google/ios-webkit-debug-proxy#369]
Hello, i'm use ipad + windows, and `ios-webkit-debug-proxy` not showing any console log information. 

For example i start on localhost (windows) server on 8080 port, 
create frunction 
```
        setInterval(() => {
            console.log(`log ${new Date()}`);
        }, 1000);

```

But console is empty alltime.

```
ios_webkit_debug_proxy -V
ios_webkit_debug_proxy 1.8.8
Built with libimobiledevice v1.3.1, libplist v2.2.1
```

If i use `--debug` i see trafic, but no have conlsole information. `remotedebug_ios_webkit_adapter` same in empty/

windows: 10
ipad: 5 
ios:  13.6.1 
web-inspecron: on

**Comment by artygus** [comment]
please see https://github.com/google/ios-webkit-debug-proxy#using-with-devtools
