### ISSUE TITLE
version 13.6.1 doesnt work on windows

### ISSUE THREAD

**Issue by vzaidman** [google/ios-webkit-debug-proxy#370]
using a new pc with windows 10 (latest packages of all freshly installed)

my phone is on version 13.6.1.
i see safari (not chrome) sites on the list:
![image](https://user-images.githubusercontent.com/5188459/91286882-ad317900-e797-11ea-9208-1c1a0bd22ff7.png)

but clicking on it shows no dom no network no console

**Comment by artygus** [comment]
@vzaidman check out readme https://github.com/google/ios-webkit-debug-proxy#using-with-devtools
