### ISSUE TITLE
examples/wdp_client.js cannot work well

### ISSUE THREAD

**Issue by zyscoder** [google/ios-webkit-debug-proxy#373]
I want to follow webkit inspector protocol to send control commands to my ios device.  I found examples/wdp_client.js is a perfect example for me, so I tried it:
 
First, I setup a simulator of iphone 12 pro max and setup ios-webkit-debug-proxy to connect to the simulator.
```
~ » ios_webkit_debug_proxy -s unix:/private/tmp/com.apple.launchd.Aq33EeLxKu/com.apple.webinspectord_sim.socket
Listing devices on :9221
Connected :9222 to SIMULATOR (SIMULATOR)
```
Then I tried examples/wdp_client.js to send commands through the websocket, but an error occurred:
```
~» examples/wdp_client.js
open ws://localhost:9222/devtools/page/1
connected
send {"id": 1, "method": "Page.navigate", "params":{"url": "http://www.baidu.com"}}
recv {"method":"Target.targetCreated","params":{"targetInfo":{"targetId":"page-7","type":"page"}}}
recv {"error":{"code":-32601,"message":"'Page' domain was not found","data":[{"code":-32601,"message":"'Page' domain was not found"}]},"id":1}
disconnected
```

Can someone tell me what wrong happend ?

**Comment by artygus** [comment]
hi @zyscoder, examples use the old dev tools protocol, it changed a lot. latest protocol commands can be found at https://github.com/WebKit/webkit/tree/master/Source/JavaScriptCore/inspector/protocol

**Comment by quanru** [comment]
@artygus I found there is a Page domain, why is 'Page.navigate' still reporting an error?

https://github.com/WebKit/WebKit/blob/main/Source/JavaScriptCore/inspector/protocol/Page.json#L148

**Comment by artygus** [comment]
@quanru examples are quite outdated, the format of messages has been changed quite a bit. this should be reworked to something like

```json
{
  "id": 123,
  "method": "Target.sendMessageToTarget",
  "params": {
     "targetId": "page-123",
     "message": "{\"id\":124,\"method\":\"Page.navigate\",\"params\":{\"url\":\"http://www.baidu.com\"}}"
  }
}
```

**Comment by artygus** [comment]
I went ahead and updated html example https://github.com/google/ios-webkit-debug-proxy/pull/411
