### ISSUE TITLE
【M1】Cannot install in Homebrew under Rosetta 2 in ARM default prefix (/opt/homebrew)!

### ISSUE THREAD

**Issue by april04ths** [google/ios-webkit-debug-proxy#376]
MAC mini(M1,2020)
i want to execute ios-webkit-debug-proxy like this:
brew install ios-webkit-debug-proxy
but return ERROR :
Cannot install in Homebrew under Rosetta 2 in ARM default prefix (/opt/homebrew)!
how can i install  ios-webkit-debug-proxy in M1,thx

**Comment by valentino22** [comment]
First install homebrew for M1 chip: 
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

Then install the package on this new architecture: 
arch -x86_64 brew install ios-webkit-debug-proxy

This solution works for every other brew package as well on M1 chip once you run the first step above:
arch -x86_64 brew install <package>

**Comment by april04ths** [comment]
问题1:curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
修改/etc/hosts
问题2:curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to raw.githubusercontent.com:443 &nbsp; 替换国内镜像

arch -x86_64 /bin/bash -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)"



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google/ios-webkit-debug-proxy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月11日(星期四) 凌晨0:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [google/ios-webkit-debug-proxy] 【M1】Cannot install in Homebrew under Rosetta 2 in ARM default prefix (/opt/homebrew)! (#376)





 
First install homebrew for M1 chip:
 arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
 
Then install the package on this new architecture:
 arch -x86_64 brew install ios-webkit-debug-proxy
 
This solution works for every other brew package as well on M1 chip once you run the first step above:
 arch -x86_64 brew install

**Comment by nassef333** [comment]
**Run this command**
`export PATH=/usr/local/bin:${PATH}`

**Comment by BekzatKalybay** [comment]
If you guys faced that type of error, this one is for you:
arch -arm64 brew upgrade nameOfLibrary
example: arch -arm64 brew install ios-webkit-debug-proxy
