### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by subjectdenied** [google/ios-webkit-debug-proxy#377]
nT

**Comment by artygus** [comment]
@subjectdenied it's not dead, but not under active development. do you have any issues?

**Comment by subjectdenied** [comment]
yes, i need a way to debug ios safari in linux, im not sure if the issue is in the proxy and/or the adapter that now got replaced with a commercial product not available for linux

**Comment by artygus** [comment]
FIY I'm working on making standalone copy of Webkit Devtools work, similar to https://github.com/artygus/webkit-webinspector

**Comment by Ebuall** [comment]
Seems like all related projects are now dead. Is there anything that still works?

**Comment by artygus** [comment]
you might wanna check out the [HimbeersaftLP/ios-safari-remote-debug-kit](https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit). I guess I'll remove the webinspector frontend part from the project in the next version, it doesn't make sense to debug with chrome devtools, protocols are just incompatible at this point.

**Comment by meszaros-lajos-gyorgy** [comment]
these didn't solve the issue for me, whatever I do I get errors:
![image](https://github.com/google/ios-webkit-debug-proxy/assets/2386064/f1b3619a-c667-4a76-8343-cad29b8836ce)

**Comment by artygus** [comment]
@meszaros-lajos-gyorgy there's a readme section with a few alternatives  https://github.com/google/ios-webkit-debug-proxy?tab=readme-ov-file#using-with-devtools
