### ISSUE TITLE
can not work on ios 14.4

### ISSUE THREAD

**Issue by fb0122** [google/ios-webkit-debug-proxy#378]
I can use it normally on ios12.1, but it cannot be used on ios14.4 and ios13.1. What is the reason?

**Comment by adambirds** [comment]
I can't get it to work on ios 14.4 either. I don't even get any out put when running it.

**Comment by auchenberg** [comment]
You could consider trying http://inspect.dev for iOS 14+ debugging

**Comment by fb0122** [comment]
Thank you, but I am using it for automated testing, so I want to control the elements of the webView through scripts

**Comment by adambirds** [comment]
@fb0122 run it on port 9221 instead of 9000 and it will work.

And @auchenberg and whilst inspect.dev might be a great tool, not all of us can justify paying for it for just a small amount of debugging we might do. And archiving the WebKit-adapter and closing all the issues wasn't the best idea. You should have left open and someone may have offered to become its maintainer if you'd didn't want to contribute to it anymore.

**Comment by fb0122** [comment]
[log.txt](https://github.com/google/ios-webkit-debug-proxy/files/6293660/log.txt)

This is the log file, it seems that there is an error: ~..{"error":{"code":-32601,"message":"'Debugger' domain was not found","data":[{"code":- 32601,"message":"'Debugger' domain was not found"}]},"id":43}

**Comment by fb0122** [comment]
![image](https://user-images.githubusercontent.com/10530632/114342564-9e64ce80-9b8e-11eb-8e83-8b737e8b8acf.png)
@adambirds What does it mean to run on 9221? It seems to run on port 9221 by default

**Comment by fb0122** [comment]
@artygus Do you have any suggestions?

**Comment by beckietech** [comment]
dear all,
I'm face similar issue on iOS 15, this proxy works on my old iPhone 5se with iOS 12.5.5 with no problem. I'm working on project that reply on this proxy. Does any one come with any idea? I tried closing all tabs on Safari experimental features with no luck!

**Comment by beckietech** [comment]
A new release appium now seems to uspport iOS 15 and other new iOS updates:https://github.com/appium/appium/releases,
aren't there any one who has a clue of iwdp?

**Comment by artygus** [comment]
should've been addressed in [v1.9.0](https://github.com/google/ios-webkit-debug-proxy/releases/tag/v1.9.0)
