### ISSUE TITLE
Proxy unable to connect to iOS7 lockdownd

### ISSUE THREAD

**Issue by christianboyle** [google/ios-webkit-debug-proxy#38]
![screen shot 2013-09-20 at 9 57 24 pm](https://f.cloud.github.com/assets/1605754/1184932/9d9600ba-2269-11e3-82f2-00b7ca3f5003.png)

This is what I see when I run the proxy. Everything is fully updated (Xcode 5, etc.).

![screen shot 2013-09-20 at 10 00 35 pm](https://f.cloud.github.com/assets/1605754/1184935/149b9102-226a-11e3-8cb6-9e6483573bee.png)

This is what I see when I go to to http://localhost:9221 (which I assume is correct). That link takes me to a full-screen inspector view, but styles don't populate in the Styles pane on the right and nothing populates in the Timeline when reloading the page in the Simulator window. The rendered source does load in the Inspector and corresponding elements highlight correctly in the Simulator when hovering in Inspector, so I presume everything is getting hung up on the problem with the proxy.

Any ideas on what could be wrong?

**Comment by jasonsilver** [comment]
Frustrating, I've just not been able to figure out what's wrong. I compiled and installed everything in Ubuntu from libimobiledevice.org, but have the following issues:
[code]
 - idevicepair pair
 - SUCCESS: Paired with device 7ec15b69bf887499a6a92ab905bb95088c694a50
 - ios_webkit_debug_proxy -f http://chrome-devtools-frontend.appspot.com/static/18.0.1025.74/devtools.html  
 - Listing devices on :9221
Could not connect to lockdownd. Exiting.: Operation now in progress
Unable to attach 7ec15b69bf887499a6a92ab905bb95088c694a50 inspector
[/code]
Now the pairing seems to be lost, and I have to click the 'Trust' dialogue to repair.

What have I done wrong?

**Comment by christianboyle** [comment]
I just tried this again and things are working as expected now. Starting from scratch on OSX:

1. brew install ios-webkit-debug-proxy
2. start iOS simulator
3. ios_webkit_debug_proxy
4. open http://localhost:9221
5. select device
6. use the websocket URL instead of host: chrome-devtools://devtools/bundled/devtools.html?ws=//localhost:9222/devtools/page/1

**Comment by qLb** [comment]
Linux ios7 trust issue is still a major problem...

**Comment by sargin48** [comment]
i fixed this error on mac with 

brew reinstall --HEAD libimobiledevice
