### ISSUE TITLE
configure: error: Package requirements (libimobiledevice-1.0 >= 1.3.0) were not met:

### ISSUE THREAD

**Issue by DanielTate** [google/ios-webkit-debug-proxy#382]
Following instructions exactly.

configure: error: Package requirements (libimobiledevice-1.0 >= 1.3.0) were not met:

**Comment by Linch1** [comment]
on Ubuntu20 i had to install from source the following packages ( in order ):

libplist : https://github.com/libimobiledevice/libplist
libimobiledevice-glue: https://github.com/libimobiledevice/libimobiledevice-glue
libusbmuxd: https://github.com/libimobiledevice/libusbmuxd
libimobiledevice: https://github.com/libimobiledevice/libimobiledevice

after that the installation was working, but when i tried to execute i had to solve also the following issue
https://github.com/google/ios-webkit-debug-proxy/issues/94#issuecomment-122009172

**Comment by artygus** [comment]
added libimobiledevice-glue requirement to readme  https://github.com/google/ios-webkit-debug-proxy/commit/c5d2e959043293ee7d0587618af2bcc4dde7feef. missing shared object is mentioned in troubleshooting section.
