### ISSUE TITLE
In the iphone13 pro max simulator、ios 15(not real device), chrome://inspect can't detect any webview?

### ISSUE THREAD

**Issue by renrenguiwei** [google/ios-webkit-debug-proxy#384]
Until now i don't try the real ios device, but simulator is more convenience for developing.

**Comment by artygus** [comment]
there's no point in using this utility on mac with chrome, safari is a better option. if you want to use it anyways, you need to obtain webinspectord socket from simulator using `lsof -aUc launchd_sim`, then grab path to unix socket, e.g. something like `/private/tmp/com.apple.launchd.ABC/com.apple.webinspectord_sim.socket` and provide it as argeumtn to the `-s` flag
