### ISSUE TITLE
On win10,  iOS 15.3 , how to solve this problem: 'could not start com.apple.webinspector'. The safari webinspector has set ‘on’.

### ISSUE THREAD

**Issue by df257** [google/ios-webkit-debug-proxy#385]
ss.add_server_fd(484)
Listing devices on :9221
ss.add_fd(132)
ss.add_server_fd(692)
ss.remove_server_fd(692)
ss.recv fd=132 len=988
ss.add_server_fd(692)
Could not start com.apple.webinspector!: No error
ss.remove_server_fd(692)
Unable to attach 9a96c0b3f8af60e0253f45ce4538d4e16229865d inspector

**Comment by df257** [comment]
I'm found this software(https://inspect.dev/) is work fine

**Comment by df257** [comment]
Can anyone help me?
![image](https://user-images.githubusercontent.com/7835444/155089498-9709b2bd-2037-4c2f-b6c2-59da6ae6b478.png)

**Comment by liesauer** [comment]
+1

**Comment by jpf904652237** [comment]
+1

**Comment by jpf904652237** [comment]
IOS 15.5 Could not start com.apple.webinspector!

**Comment by df257** [comment]
> IOS 15.5 Could not start com.apple.webinspector!

nobody can help us😂

**Comment by darkfiredarkhalo** [comment]
+1

**Comment by gland2015** [comment]
+10000000

**Comment by AlienC** [comment]
Who can help me？

**Comment by FanningHau** [comment]
Did this solved? Anyone can help?

**Comment by df257** [comment]
> Did this solved? Anyone can help?

Can't solve it, I have given up😂

**Comment by ValueXu** [comment]
Seems we need to use vmware or buy a mac, shit Cook.

**Comment by artygus** [comment]
@ValueXu tool was abandoned for a while, since there're better analogues here like inspect.dev. it's a bit tricky to follow libimobiledevice implementation with current architecture. are you planning to use it as an inspector tool or to send devtools command via websockets?

**Comment by ValueXu** [comment]
> @ValueXu tool was abandoned for a while, since there're better analogues here like inspect.dev. it's a bit tricky to follow libimobiledevice implementation with current architecture. are you planning to use it as an inspector tool or to send devtools command via websockets?

inspector

**Comment by artygus** [comment]
okay, some debugging information may be useful. I don't see issues with ios 15.4.1. can you confirm you have latest itunes installed?

**Comment by ValueXu** [comment]
> okay, some debugging information may be useful. I don't see issues with ios 15.4.1 and windows 10. can you confirm you have latest itunes installed?

Yes,I do. The environment I have used is Windows 11 22621.1344, iTunes 12.12.7.1, iPhone 13 with iOS 16.3.1. Meanwhile, thanks for your help, but  I have finished my debugging using macOS on VMware.

**Comment by artygus** [comment]
I believe this should've been addressed in https://github.com/google/ios-webkit-debug-proxy/pull/394 version 1.9.0
