### ISSUE TITLE
ios-webkit-debug-proxy dependencies not built for the x86_64 CPU architecture

### ISSUE THREAD

**Issue by XdYangXiaoRong** [google/ios-webkit-debug-proxy#388]
Error: ios-webkit-debug-proxy dependencies not built for the x86_64 CPU architecture:
 ca-certificates was built for arm64
  openssl@1.1 was built for arm64

how to solve it?

**Comment by artygus** [comment]
which os is this?

**Comment by artygus** [comment]
I guess you're building it on x86, but dependenices were pulled from arm64 brew
