### ISSUE TITLE
Can't connect my ios device!!!

### ISSUE THREAD

**Issue by tsung-sc** [google/ios-webkit-debug-proxy#393]
My opearting system: ubuntu 22.04.02LTS
My ios device: iPhone 7 with ios13.2.3
 
ios_webkit_debug_proxy: 1.8.8
libimobiledevice: v1.3.0-176-gcc540a2
libplist: v2.2.0

question: i can connect my ios device in the very first use,but i can't use it when i try again,it console
`Listing devices on :9221
ssl send failed: Success
Unable to send 198 bytes to inspector
Unable to connect to “Administrator”的 iPhone (d7478316789706e43346b1c4004d3abb7dcd9e81)
  Please verify that Settings > Safari > Advanced > Web Inspector = ON
Segmentation fault (core dumped)`
and i'm sure the Web Inspectoris is on,please tell me how to solve it?

**Comment by artygus** [comment]
should be addressed by https://github.com/google/ios-webkit-debug-proxy/pull/394, check out the latest release
