### ISSUE TITLE
make compilation error on fedora 37

### ISSUE THREAD

**Issue by zionbr** [google/ios-webkit-debug-proxy#395]
[felipe@fedora ios-webkit-debug-proxy]$ make
make  all-recursive
make[1]: Entrando no diretório '/home/felipe/ios-webkit-debug-proxy'

Making all in src
make[2]: Entrando no diretório '/home/felipe/ios-webkit-debug-proxy/src'

gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../include/ios-webkit-debug-proxy        -g -O2 -Wall -Werror -MT ios_webkit_debug_proxy-idevice_ext.o -MD -MP -MF .deps/ios_webkit_debug_proxy-idevice_ext.Tpo -c -o ios_webkit_debug_proxy-idevice_ext.o `test -f 'idevice_ext.c' || echo './'`idevice_ext.c
idevice_ext.c: In function ‘idevice_ext_connection_enable_ssl’:
idevice_ext.c:104:3: error: ‘PEM_read_bio_RSAPrivateKey’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  104 |   PEM_read_bio_RSAPrivateKey(membp, &rootPrivKey, NULL, NULL);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/ssl.h:36,
                 from ../include/ios-webkit-debug-proxy/idevice_ext.h:15,
                 from idevice_ext.c:18:
/usr/include/openssl/pem.h:447:1: note: declared here
  447 | DECLARE_PEM_rw_cb_attr(OSSL_DEPRECATEDIN_3_0, RSAPrivateKey, RSA)
      | ^~~~~~~~~~~~~~~~~~~~~~
idevice_ext.c:106:3: error: ‘SSL_CTX_use_RSAPrivateKey’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  106 |   SSL_CTX_use_RSAPrivateKey(ssl_ctx, rootPrivKey);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/ssl.h:1815:12: note: declared here
 1815 | __owur int SSL_CTX_use_RSAPrivateKey(SSL_CTX *ctx, RSA *rsa);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
idevice_ext.c:107:3: error: ‘RSA_free’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  107 |   RSA_free(rootPrivKey);
      |   ^~~~~~~~
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:751: ios_webkit_debug_proxy-idevice_ext.o] Erro 1
make[2]: Saindo do diretório '/home/felipe/ios-webkit-debug-proxy/src'

make[1]: *** [Makefile:410: all-recursive] Erro 1
make[1]: Saindo do diretório '/home/felipe/ios-webkit-debug-proxy'

make: *** [Makefile:342: all] Erro 2
[felipe@fedora ios-webkit-debug-proxy]$ 

i try command make but dont works

**Comment by artygus** [comment]
hey @zionbr, I'm afraid you might need an older openssl 1.1 to compile it, I'll work on adding SSL 3 support in the meatime

**Comment by artygus** [comment]
should be addressed in https://github.com/google/ios-webkit-debug-proxy/commit/5ba30a2a67f39d25025cadf37c0eafb2e2d2d0a8
