### ISSUE TITLE
Upgrade OpenSSL version

### ISSUE THREAD

**Issue by os-lmo** [google/ios-webkit-debug-proxy#404]
Hi,

I realized that the current version of ios-webkit-debug-proxy is distributing the version 1.1.1 of openssl.
However, as we can see in https://endoflife.date/openssl, the support for that version ends on 11th September 2023.

Saying this. will a new version ios-webkit-debug-proxy be released in coming weeks with a new version of openssl (v3)?

Thanks

**Comment by artygus** [comment]
Hi, don't see it as an issue tbh, being unsupported doesn't mean it'll suddenly stop working 🤔

**Comment by lmvco** [comment]
It's true that being unsupported doesn't mean stop working. Nonetheless, if any issue or security vulnerability is found meanwhile, with unsupported versions, there will be no fix it...
Is the upgrade to Open SSL 3.x hard to implement?

**Comment by artygus** [comment]
Support is already implemented, it's just there were no major updates for the new build. 

> Nonetheless, if any issue or security vulnerability is found meanwhile, with unsupported versions, there will be no fix it...

Fair, I'll craft a new release in a couple of weeks if nothing pops up. thanks for bringing this up!

**Comment by artygus** [comment]
[new release](https://github.com/google/ios-webkit-debug-proxy/releases/tag/v1.9.1) has been built with openssl 3.3.0
