### ISSUE TITLE
Empty page on inspected DevTools

### ISSUE THREAD

**Issue by lezhenkin** [google/ios-webkit-debug-proxy#409]
Hi. I have an empty page when I click the "inspect" link in chrome://inspect/#devices.

iPhone 7. iOS 15.8.1. In PowerShell i see messages "Invalid HTTP header".
When I started with ios_webkit_debug_proxy i see that:

Listing devices on :9221
Connected :9222 to iPhone7lezhenkin (e0f72e548b8b37392f5be7866d7649aab54d3609)

In my chrome://inspect/#devices I have that configs:

-- Discover USB devices Port forwarding: 9222 -> localhost:9221
-- Discover network targets Configure: localhost:9222

In my iPhone setting web inspector is turn on

What am I doing wrong? Help, please

**Comment by artygus** [comment]
Hi there, please see readme section about chrome dev tools https://github.com/google/ios-webkit-debug-proxy?tab=readme-ov-file#using-with-devtools
