### ISSUE TITLE
RFE: Persist console log across pages

### ISSUE THREAD

**Issue by bluesmoon** [google/ios-webkit-debug-proxy#41]
While we currently have the ability to persist network request tracking across pages:
![bottom toolbar network panel](https://f.cloud.github.com/assets/35098/1513789/454169fc-4ae8-11e3-809d-dde123e00cf9.png)

There does not appear to be a way to do the same for the console log:
![bottom toolbar console panel](https://f.cloud.github.com/assets/35098/1513794/53ba935a-4ae8-11e3-846c-45ebd7a22c62.png)

This would be a very useful addition.

**Comment by artygus** [comment]
the issue relates to devtools frontend, not a tool functionality
