### ISSUE TITLE
Unable to get target page in inspect window on MacOS

### ISSUE THREAD

**Issue by EzioLi01** [google/ios-webkit-debug-proxy#413]
Hey experts,

Please check if it's an issue or expected behavior.

Repo steps:
1. Open app in ios simulator
2. Start proxy like `ios_webkit_debug_proxy -c null:9220,:9223-9322 -s unix:/private/tmp/com.apple.launchd.AdE5als0Ax/com.apple.webinspectord_sim.socket`
3. Open `edge or chrome://inspect/#devices`
4. Can get correct target and file in target list, click inspect

Result:
Empty inspect window is displayed

Attach simulator info:
```
[
    {
        "devtoolsFrontendUrl": "/devtools/devtools.html?ws=localhost:9223/devtools/page/1",
        "faviconUrl": "",
        "thumbnailUrl": "/thumb/file:///Users/ezio/Library/Developer/CoreSimulator/Devices/31B90FF9-20F1-42BA-A848-462996D6F53F/data/Containers/Bundle/Application/37EDF797-19E1-4922-A1D9-EB66ECC3D904/helloCordova4.app/www/index.html",
        "title": "Hello World",
        "url": "file:///Users/ezio/Library/Developer/CoreSimulator/Devices/31B90FF9-20F1-42BA-A848-462996D6F53F/data/Containers/Bundle/Application/37EDF797-19E1-4922-A1D9-EB66ECC3D904/helloCordova4.app/www/index.html",
        "webSocketDebuggerUrl": "ws://localhost:9223/devtools/page/1",
        "appId": "PID:4130"
    }
]
```

**Comment by EzioLi01** [comment]
The attached file is in `.app` file, I'm not sure if chrome devtools can attach into ios application content.

**Comment by artygus** [comment]
Hi @EzioLi01, please check out this readme section https://github.com/google/ios-webkit-debug-proxy?tab=readme-ov-file#using-with-devtools. Unfortunately newer versions of Chrome DevTools aren't compatible with Safari dev tools protocol, but there are alternatives.

**Comment by EzioLi01** [comment]
Thanks @artygus for the quickly reply, so it means that this should be the knows limitation as expected on chrome devtools?

**Comment by artygus** [comment]
yes, I'd say it's unworkable with chrome dev tools at this point. since you're on mac already, waht don't you use safari for inspecting pages? 😅

**Comment by EzioLi01** [comment]
> yes, I'd say it's unworkable with chrome dev tools at this point. since you're on mac already, why don't you use safari for inspecting pages? 😅

Yes, I've started using it. Thanks for the information! I'll close this issue.
