### ISSUE TITLE
Chrome cannot connect - everything else looks fine

### ISSUE THREAD

**Issue by brouxhaha** [google/ios-webkit-debug-proxy#44]
I've got all the necessary items installed for this to work. I get no errors anywhere, except when I actually try to go to port 9221. I get a "Google Chrome could not connect to localhost:9221" error. Here's an image of my console, the ios simulator, and my web browser: http://i.imgur.com/QawXsBN.png.

I've tried looking around, but I can't find anything. Can anyone figure out what might be wrong?

**Comment by artygus** [comment]
see https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

> To use Chrome DevTools it's the recommendation to use the RemoteDebug/remotedebug-ios-webkit-adapter project, which has instructions on how to setup Chrome to remote debug iOS devices, much similar to Android debugging.
> 
> The reason is that recent versions of Chrome and Safari there're major discrepancies between Chrome Remote Debugging Protocol and Apple's Remote Web Inspector service, which means that newer versions of Chrome DevTools arne't compatible with Safari.
