### ISSUE TITLE
Segfault while starting up

### ISSUE THREAD

**Issue by pbruining** [google/ios-webkit-debug-proxy#45]
During the startup of the proxy it segfaults. I attached the debug output.
The host system is Ubuntu 13.10. If more information is needed, please mail me.
The idevice is an iPad mini retina with iOS 7.0.4 running.

<pre><code>pieter@Ares:~/Code/ios-webkit-debug-proxy$ idevice_id -l
794815b****
pieter@Ares:~/Code/ios-webkit-debug-proxy$ ios_webkit_debug_proxy -d
ss.add_server_fd(3)
ss.add_fd(4)
ss.add_server_fd(5)
ss.remove_server_fd(5)
ss.recv fd=4 len=932
ss.add_server_fd(5)
Segmentatiefout (geheugendump gemaakt)
pieter@Ares:~/Code/ios-webkit-debug-proxy$ 
</code></pre>

**Comment by artygus** [comment]
the issue is quite old now, if you still have the issue feel free to reopen
