### ISSUE TITLE
can't inpsect pages

### ISSUE THREAD

**Issue by seansay** [google/ios-webkit-debug-proxy#49]
I'm using os x 10.9, after `brew install ios_webkit_debug_proxy`

I can list my devices on port 9221
but can't open inspect page on my ipad

```
iOS Devices:
localhost:9222 - Sean's iPad
```

But port 9222 fail to load `Oops! Google Chrome could not connect to localhost:9222`

**Comment by auchenberg** [comment]
Should probably be closed.
