### ISSUE TITLE
Can't inspect pages on simulator

### ISSUE THREAD

**Issue by datoda** [google/ios-webkit-debug-proxy#50]
Hi,

```
Here's my environment:
```
1. I installed ios-webkit-debug-proxy using brew without problem on my Mac.
2. I have xcode insalled. I can start simulator without any issue.

Here's what I did:
1. Start simulator. Pick iPhone Retina with iOS 6.
2. Make sure that in the simulator, Safari's Advanced setting has Web Inspector "on".
3. Start Safari in the simulator, and navigate to google.com.
3. Start "ios-webkit-debug-proxy -d" (i.e. with debug on) on Mac.
4. Start Chrome. And enter the URL "localhost:9221".
5. I can see the simulator tagged as localhost:9222.
6. Click the link "localhost:9222", and I see "www.google.com" listed as an inspectable page.
7. I click "www.google.com", and got the page "No Data Received".
8 In the console, I see that ios-webkit-debug-proxy's output says "send failed: Socket is not connected".

Am I missing something here? How can I correct this? Thanks.

**Comment by rocco** [comment]
Did you solve this meanwhile? I have the same issue on a real device (iPad).

**Comment by vopjie** [comment]
I have the same issue on a real device (iPhone XR).

**Comment by artygus** [comment]
I recommend using safari on mac. but if you're looking for automation purposes to connect to simulator you would need to obtain webinspectord socket from simulator using `lsof -aUc launchd_sim`, then grab path to unix socket, e.g. something like `/private/tmp/com.apple.launchd.ABC/com.apple.webinspectord_sim.socket` and provide it as argument to the `-s` flag.
