### ISSUE TITLE
Can't use chrome dev tools profiler with ios-webkitdebug-proxy

### ISSUE THREAD

**Issue by earlyster** [google/ios-webkit-debug-proxy#52]
I was not able to get chrome dev tools profiler working when using Ipad device or using simulator. I couldn't find any issue related to profiler working or not working. Just want to make sure that this feature is not supposed to work since the safari debug tools don't have a profiler. 

When I use profiler I see blank screen and see JS error:

Request with id = 23 failed. Method not found(-32601): 'Profiler.getProfile' wasn't found. 

All the profile windows are empty

![image](https://f.cloud.github.com/assets/813090/2275843/8b960e1a-9f2c-11e3-8d9d-62b1f9ab62a2.png)

**Comment by jordwalke** [comment]
What would it take to get this working?

**Comment by kcbanner** [comment]
Any updates on this?

**Comment by artygus** [comment]
@kcbanner @jordwalke I'm currently working on a compatibility layer between chrome and safari dev tools protocols, I think I'll publish the first working version in a month or so

**Comment by jordwalke** [comment]
@artygus Is that a complete reimplementation of the ios-webkit-debug-proxy, or just fixing the issues? I'd really like to hear more about what you're doing.

**Comment by auchenberg** [comment]
@artygus @jordwalke +1 listening in here.

**Comment by artygus** [comment]
@jordwalke nope, iwdp does the only one thing, it proxies dev tools messages from iOS browser. Chrome and Safari have diverged a little bit with the debugger protocol at some point, so technically it is possible to write another proxy that translates things from the old protocol to what Chrome understands now. You can get the idea here https://github.com/google/ios-webkit-debug-proxy/issues/86#issuecomment-91132203

**Comment by jordwalke** [comment]
@artygus Thanks. Well, I assure you that anyone using React Native would be very excited to hear what your findings are. Please keep us posted.

**Comment by artygus** [comment]
@kcbanner @jordwalke @auchenberg hey guys, as I don't have enough free time to finish work on compatibility proxy right now, I decided to to make a little progress on the issue extracting webkit webinspector diectly, maybe you will find it useful https://github.com/artygus/webkit-webinspector

**Comment by artygus** [comment]
Regarding the Profiler tab I'm afraid it's not possible at all, Profiler domain was completely removed with  protocol v9, and only CPU profiling was possible with previous versions

**Comment by auchenberg** [comment]
@artygus Thanks for the update, much appreciated!

**Comment by auchenberg** [comment]
Ping @paulirish

**Comment by artygus** [comment]
see https://github.com/google/ios-webkit-debug-proxy#using-with-devtools

> To use Chrome DevTools it's the recommendation to use the RemoteDebug/remotedebug-ios-webkit-adapter project, which has instructions on how to setup Chrome to remote debug iOS devices, much similar to Android debugging.
> 
> The reason is that recent versions of Chrome and Safari there're major discrepancies between Chrome Remote Debugging Protocol and Apple's Remote Web Inspector service, which means that newer versions of Chrome DevTools arne't compatible with Safari.
