### ISSUE TITLE
Windows Port

### ISSUE THREAD

**Issue by SamHasler** [google/ios-webkit-debug-proxy#53]
The Readme says "Windows support is planned but not implemented yet."

I couldn't find an issue for it so I've created this one to track it.

In the mean-time I'm using https://github.com/artygus/ios-webkit-debug-proxy-win32

**Comment by paulirish** [comment]
Aye, it looks like @artygus's port is the best choice for now. 

In the future this port could be merged in, but it looks like the separate project can track upstream closely if need be.

**Comment by artygus** [comment]
@paulirish my repo needs some extra work, i'd like to merge though

**Comment by SamHasler** [comment]
See also https://github.com/artygus/ios-webkit-debug-proxy-win32/issues/23#issuecomment-275169128

> @auchenberg these commits correspond to 1.7.0 and 1.6.0 versions. Those were built with msys2/mingw32(64).
> 
> It would be more precise to call "win32" project a "visual studio" project, it's based more or less on 1.5.0. and I have no further intention to keep it up to date.
> 
> UPD: I hope to get back to work on mingw branch of original ios-webkit-debug-proxy, so win builds would be always up to date with other platforms, in the next two weeks

Presumably @artygus would be open to any help getting that build working.

**Comment by artygus** [comment]
done #193

**Comment by paulirish** [comment]
This is huge! awesome stuff, @artygus. 
very very nice. :)
