### ISSUE TITLE
Libimobile working, ios-webkit-debug not doing anything - on 7.1 device.

### ISSUE THREAD

**Issue by programmin1** [google/ios-webkit-debug-proxy#54]
I updated my libimobiledevice by compiling it earlier, now I'm able to see and view files from the iPad 7.1, but when I run libimobiledevice, it returns with no error message.

strace ios_webkit_debug_proxy gives:
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=23054, si_uid=1000} ---
+++ killed by SIGPIPE +++

**Comment by artygus** [comment]
there were major updates since then and minimal libimobiledevice was raised to 1.2.0
