### ISSUE TITLE
Can't Edit Styles

### ISSUE THREAD

**Issue by luco** [google/ios-webkit-debug-proxy#57]
Actually I can't edit styles in the default address provided:
http://chrome-devtools-frontend.appspot.com/static/18.0.1025.74/devtools.html

I already tried the -f option using some url's provided here as:
http://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html

But I doesn't seems to work. Any tips?

**Comment by montogeek** [comment]
Use http://chrome-devtools-frontend.appspot.com/static/27.0.1453.93/devtools.html :)

**Comment by stephanec1** [comment]
it do not work for me too

**Comment by anaibol** [comment]
@luco any news about this? Could you finally edit the styles?

Thanks

**Comment by artygus** [comment]
unfortunately it's because diverged Chrome and Safari protocols, an the issue is not going to be fixed. The purpose of the tools is to proxy requests to safari devtools through websocket protocol
