### ISSUE TITLE
Invalid idevice_connection struct? Unable to attach <UDID> inspector

### ISSUE THREAD

**Issue by anshumanchatterji** [google/ios-webkit-debug-proxy#59]
Hi Team,

I am seeing this error as soon as i connect my iPad.

<code>
Invalid idevice_connection struct?: Undefined error: 0
Unable to get connection file descriptor.: Undefined error: 0
ss.remove_server_fd(5)
Unable to attach c70fbb163gd3edee9bf781e0052d24a1111bb56e inspector
</code>

What I did:
<code>
brew install ios_webkit_debug_proxy
brew update
brew doctor
</code>

Then i corrected all the warnings as suggested by brew doctor. And ran this command:

<code>
ios_webkit_debug_proxy -d
</code>

the output was:
<code>
ss.add_server_fd(3)
ss.add_fd(4)
ss.add_server_fd(5)
ss.remove_server_fd(5)
ss.recv fd=4 len=978
ss.add_server_fd(5)
</code>

but as soon as i plugged in my iPad, i got this error:
<code>
Invalid idevice_connection struct?: Undefined error: 0
Unable to get connection file descriptor.: Undefined error: 0
ss.remove_server_fd(5)
Unable to attach c70fbb163gd3edee9bf781e0052d24a1111bb56e inspector
</code>

This is my brew config output
<code>
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 68da542651c8c8d4fa844cd7d32b8265b0231d4a
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit ivybridge
OS X: 10.9.3-x86_64
Xcode: 5.0.2
CLT: 5.1.0.0.1.1396320587
Clang: 5.0 build 500
X11: N/A
System Ruby: 2.0.0-451
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/crestech/.rvm/rubies/ruby-2.1.0/bin/ruby

</code>

**Comment by artygus** [comment]
seems to be fixed after upgrading libimobiledevice to 1.1.6
