### ISSUE TITLE
Pausing javascript execution crashes Safari and the debug proxy.

### ISSUE THREAD

**Issue by AdaRoseEdwards** [google/ios-webkit-debug-proxy#63]
If the javascript execution stops, via the pause button, pause on exceptions or on debugger; safari crashes and the debugger proxy segfaults.

Ubuntu 14.04.

Encountered on both ios 6 and ios 7

**Comment by jacksonrayhamilton** [comment]
I tried `ios_webkit_debug_proxy -f chrome-devtools://devtools/bundled/inspector.html` at fec01df5d0c637e3ac52c3a8c1ad4efa0862f3d1 with Chromium "Version 48.0.2564.82 Built on Ubuntu 14.04, running on LinuxMint 17 (64-bit)," and debugging JS code worked for me.

**Comment by artygus** [comment]
note about devtools has been added to readme https://github.com/google/ios-webkit-debug-proxy/commit/4b940e6dd9629b1662d8fd8dc710f26731af9c6e
