### ISSUE TITLE
Unable to run make install

### ISSUE THREAD

**Issue by usharj** [google/ios-webkit-debug-proxy#64]
brew install ios-webkit-debug-proxy
==> Downloading https://github.com/google/ios-webkit-debug-proxy/archive/1.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/ios-webkit-debug-proxy-1.3.tar.gz
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/ios-webkit-debug-proxy/1.3
==> make install
      _wi_args_to_xml in webinspector.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: **\* [ios_webkit_debug_proxy] Error 1
make: **\* [install-recursive] Error 1

**Comment by artygus** [comment]
should be fixed long ago
