### ISSUE TITLE
plist_copy_node: Assertion `data' failed. When running on ubuntu 14.04

### ISSUE THREAD

**Issue by dwilkie** [google/ios-webkit-debug-proxy#65]
I upgraded my libplist to as described here: https://github.com/google/ios-webkit-debug-proxy/issues/62 but now I get the following error.

```
Listing devices on :9221
ios_webkit_debug_proxy: plist.c:194: plist_copy_node: Assertion `data' failed.
```

**Comment by artygus** [comment]
closing the issue as it's related to dependent libraries
