### ISSUE TITLE
Unable to run on Ubuntu 14.04

### ISSUE THREAD

**Issue by stevenmc** [google/ios-webkit-debug-proxy#66]
ios_webkit_debug_proxyListing devices on :9221
Detected an old copy of libplist?!  For a fix, see:
https://github.com/libimobiledevice/libimobiledevice/issues/68#issuecomment-38994545: Success
Unable to start device_listener

I'm running libplist-dev 1.10.1 amd64 as this appears to be the latest download available.

I've looked through the suggested url, but it doesn't actually suggest a fix in the end.

Thanks.

**Comment by artygus** [comment]
issue seems to be related to now outdated libplist version, if the problem still there feel free to reopen
