### ISSUE TITLE
ios_webkit_debug_proxy -c <udid>:27753 -d gives select_port() failed

### ISSUE THREAD

**Issue by JeffHoover** [google/ios-webkit-debug-proxy#67]
Actually, when I specify any port number, I get 'select_port() failed'

Versions:
MacOS 10.9.4
ios-webkit-debug-proxy 1.3
libimobiledevice 1.1.5 (already downgraded from 1.1.6 as other threads suggest)

**Comment by artygus** [comment]
hi @JeffHoover, it's been a while, but can you confirm it's still happening to you?

**Comment by JeffHoover** [comment]
After 2+ years, I don't recall what I was even doing with it. Sorry.
