### ISSUE TITLE
Can't accesss remote debugging 

### ISSUE THREAD

**Issue by danilomelo** [google/ios-webkit-debug-proxy#70]
I can't load devtools from remote server why it toggle the protocol from http to https when load the page

user$ ios_webkit_debug_proxy -f http://chrome-devtools-frontend.appspot.com/static/33.0.1722.0/devtools.html

log from console page:
[blocked] The page at 'https://chrome-devtools-frontend.appspot.com/static/33.0.1722.0/devtools.html?host=localhost:9222&page=1' was loaded over HTTPS, but ran insecure content from 'ws://localhost:9222/devtools/page/1': this content should also be loaded over HTTPS.
 inspector.js:742
Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS. inspector.js:742
Application Cache NoUpdate event devtools.html:1
Refused to load plugin data from '' because it violates the following Content Security Policy directive: "object-src 'none'".

some tip?

**Comment by auchenberg** [comment]
Have you tried loading the devtools front-end from non HTTPS? The debugging target can be HTTPS without the devtools itself is.
