### ISSUE TITLE
Not working with iOS 8.0 or 7.1.1 from Mac 10.9.2

### ISSUE THREAD

**Issue by appsforartists** [google/ios-webkit-debug-proxy#72]
I just tried installing for the first time using `brew install ios-webkit-debug-proxy`.  It looks like it worked fine, but I can't get either of my test devices (iPhone 5 on iOS 8 or iPad mini /w Retina on iOS 7.1.1) to connect.  Here's a log:

```
ss.add_server_fd(3)
ss.add_fd(4)
ss.add_server_fd(5)
ss.remove_server_fd(5)
ss.recv fd=4 len=980
ss.add_server_fd(5)
Invalid idevice_connection struct?: Undefined error: 0
Unable to get connection file descriptor.: Undefined error: 0
ss.remove_server_fd(5)
Unable to attach 0bc06164408e5960ff4e976293db2b58e5c222cc inspector
```

If I go to `localhost:9221`, I see this:

``` html
<html><head><title>iOS Devices</title></head><body>iOS Devices:<p><ol>
</ol></body></html>
```

Here's the install log:

```
~/P/ios-webkit-debug-proxy (master) $   brew install ios-webkit-debug-proxy
==> Installing dependencies for ios-webkit-debug-proxy: autoconf, automake, libxml2, libplist, libusb, usbmuxd, libtasn1, openssl, libimobiledevice
==> Installing ios-webkit-debug-proxy dependency: autoconf
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/autoconf-2.69.mavericks.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring autoconf-2.69.mavericks.bottle.1.tar.gz
🍺  /usr/local/Cellar/autoconf/2.69: 69 files, 2.0M
==> Installing ios-webkit-debug-proxy dependency: automake
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/automake-1.14.1.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring automake-1.14.1.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/automake/1.14.1: 127 files, 2.5M
==> Installing ios-webkit-debug-proxy dependency: libxml2
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/libxml2-2.9.1.mavericks.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring libxml2-2.9.1.mavericks.bottle.1.tar.gz
==> Caveats
This formula is keg-only, so it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/libxml2/lib
    CPPFLAGS: -I/usr/local/opt/libxml2/include

==> Summary
🍺  /usr/local/Cellar/libxml2/2.9.1: 274 files, 11M
==> Installing ios-webkit-debug-proxy dependency: libplist
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/libplist-1.11.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libplist-1.11.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/libplist/1.11: 26 files, 404K
==> Installing ios-webkit-debug-proxy dependency: libusb
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/libusb-1.0.18.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libusb-1.0.18.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/libusb/1.0.18: 11 files, 332K
==> Installing ios-webkit-debug-proxy dependency: usbmuxd
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/usbmuxd-1.0.9.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring usbmuxd-1.0.9.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/usbmuxd/1.0.9: 9 files, 124K
==> Installing ios-webkit-debug-proxy dependency: libtasn1
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/libtasn1-3.6.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libtasn1-3.6.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/libtasn1/3.6: 53 files, 564K
==> Installing ios-webkit-debug-proxy dependency: openssl
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/openssl-1.0.1h.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring openssl-1.0.1h.mavericks.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, so it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

The OpenSSL provided by OS X is too old for some software.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.1h: 429 files, 14M
==> Installing ios-webkit-debug-proxy dependency: libimobiledevice
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/libimobiledevice-1.1.6.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libimobiledevice-1.1.6.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/libimobiledevice/1.1.6: 58 files, 912K
==> Installing ios-webkit-debug-proxy
==> Downloading https://github.com/google/ios-webkit-debug-proxy/archive/1.3.tar.gz
######################################################################## 100.0%
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/ios-webkit-debug-proxy/1.3
==> make install
🍺  /usr/local/Cellar/ios-webkit-debug-proxy/1.3: 15 files, 160K, built in 13 seconds
```

My corporate laptop is a MacBook Pro /w Retina running 10.9.2.

**Comment by cades** [comment]
Exactly the same problem as @maizaAvaro 
happens on iPhone 6 and iPad

**Comment by confile** [comment]
I think it depends on the version of Chrome it work with version 36 for me.

**Comment by srihariinnamuri** [comment]
Any solution for this issue, I am getting same issue on IPhone 6 (IOS 8.1)

Invalid message _rpc_applicationUpdated: <dict>
	<key>WIRApplicationIdentifierKey</key>
	<string>PID:892</string>
	<key>WIRIsApplicationProxyKey</key>
	<true/>
	<key>WIRApplicationNameKey</key>
	<string></string>
	<key>WIRApplicationBundleIdentifierKey</key>
	<string>com.apple.WebKit.WebContent</string>
	<key>WIRIsApplicationActiveKey</key>
	<integer>0</integer>
	<key>WIRHostApplicationIdentifierKey</key>
	<string>PID:890</string>
</dict>
ss.remove_fd(6)
Disconnected :27753 from

**Comment by elennaro** [comment]
Also have this message Invalid message _rpc_applicationUpdated

**Comment by paymand** [comment]
For *Invalid message _rpc_applicationUpdated* use this:
``./bin/ios-webkit-debug-proxy-launcher.js -c <UDID>:27753 -d``
which takes care of launching *ios_webkit_debug_proxy*. See:
https://github.com/appium/appium/blob/master/bin/ios-webkit-debug-proxy-launcher.js

**Comment by wrightt** [comment]
Hi, sorry I haven't had time to fix this yet!  I'm freeing up time soon and I have a refactor plan to help avoid these bugs; see:
https://github.com/appium/appium/issues/4668#issuecomment-77769033

**Comment by NehaDua** [comment]
Hi All,

I was also facing this webkit crashing issue and trying its work around "./bin/ios-webkit-debug-proxy-launcher.js -c <UDID>:27753 -d" 

first i did    "cd /usr/local/bin" on terminal 
then "ios-webkit-debug-proxy-launcher.js -c ca666e295c7cd5a893e376989f3c4a3b24987534:27753 –d"


it says "command not found "

can someone please help me , do we need to separate install this js file or where I can find this on my mac 

thanks

**Comment by jchuong** [comment]
@NehaDua That is only in the appium directory, not in your system directory.  [appium]/bin/ios-webkit-debug-proxy-launcher.js

**Comment by ASYB** [comment]
@paymand 
Sorry this message is not related to  thread, can you please let me know the configuration to test on Opera Mini on iPhone 5s and iPad Mini, as you mentioned you tested on this browser.

**Comment by paymand** [comment]
@ASYB: The settings were the ones I mentioned in https://github.com/google/ios-webkit-debug-proxy/issues/72#issuecomment-61071651 last time I checked.

**Comment by ASYB** [comment]
what about the capabilities for browser, as we mentioned safari for safari browser. If I am not wrong you were talking about Opera Mini browser ??

**Comment by paymand** [comment]
You do not need any special cap for Opera afaik. It uses UIWebview for non-mini modes that Appium should automatically pick up and expose via ``driver.contexts``.
See https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/hybrid.md for more info.

**Comment by priyatech** [comment]
iOS Web Kit debug Proxy connects with the iOS device and disconnects immediately. Once in 10 times plugging and unplugging and changing the port it connects. Is there any  iOS Web Kit debug Proxy cache on device or mac to clean up? 

Xcode7.2 
OSx10.11
iOS Device 7.1
iPhone 5S

**Comment by artygus** [comment]
hi @appsforartists, did it work for you eventually?

**Comment by appsforartists** [comment]
No idea - I don't even work at that job anymore.  😝

**Comment by artygus** [comment]
haha k, I guess it should be fixed anyway
