### ISSUE TITLE
Device disconnected when leaving Safari

### ISSUE THREAD

**Issue by gapipro** [google/ios-webkit-debug-proxy#73]
For example when you are connected to device and you click on Install Certificate on web page users leaves Safari and Certificate dialog is shown. At that time device gets disconnected form proxy and even after Certificate install is done and user is redirected back to Safari device doesn't show up again until you disconnect and reconnect usb cable. 

Can't there be some detection when device is switching back to Safari?

**Comment by paulirish** [comment]
Closing as iwdp can't try this out right now.
