### ISSUE TITLE
IOS 8 - Issue inpector on Ubuntu 14.04

### ISSUE THREAD

**Issue by danilomelo** [google/ios-webkit-debug-proxy#74]
On ubuntu 14.04 

Could not start com.apple.webinspector!: No such file or directory
ss.remove_server_fd(5)
Unable to attach a607dedbabb464c43ebde5db9cdc225449ed4cfd inspector

The inspector on Iphone is enabled.

**Comment by brainwarped** [comment]
I have the same problem. Pairing, unpairing and validation were successful.

Tested on:

Fedora @ 20
iPad @ 8
iPhone @ 8

Error:

> Could not start com.apple.webinspector!: Success
> Unable to attach xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx inspector

**Comment by haizaar** [comment]
Same issue here exactly. Is there any workaround? Can someone confirm if it works on Ubuntu 14.10 or 15.04?

**Comment by vincentbernat** [comment]
A possible workaround is to recompile libimobiledevice packages to use OpenSSL instead of GnuTLS. I am able to make all work when I do just that.

```
apt-get source libimobiledevice
sed -i d/disable-openssl/ debian/rules
dpkg-buildpackage -us -uc
```

**Comment by programmin1** [comment]
I'm on libimobiledevice 1.2 from here on 14.04 and still getting this error:
https://launchpad.net/~martin-salbaba/+archive/ubuntu/ppa+libimobiledevice

**Comment by artygus** [comment]
sounds like libimobiledevice problem, please report to https://github.com/libimobiledevice/libimobiledevice
