### ISSUE TITLE
In file included from ios_webkit_debug_proxy_main.c:23: ../include/webinspector.h:15:10: fatal error: 'plist/plist.h' file not found

### ISSUE THREAD

**Issue by emilanova** [google/ios-webkit-debug-proxy#76]
Hello,

I am running on my Macbook Pro the following commands:
> git clone https://github.com/google/ios-webkit-debug-proxy.git
> ./autogen.sh
> ./configure
> make
and the result of the "make" command is the following:

ios-webkit-debug-proxy-1.4 my_user$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
gcc -DHAVE_CONFIG_H -I. -I..  -I../include     -g -O2 -Wall -Werror -MT ios_webkit_debug_proxy_main.o -MD -MP -MF .deps/ios_webkit_debug_proxy_main.Tpo -c -o ios_webkit_debug_proxy_main.o ios_webkit_debug_proxy_main.c
In file included from ios_webkit_debug_proxy_main.c:23:
../include/webinspector.h:15:10: fatal error: 'plist/plist.h' file not found
#include <plist/plist.h>
         ^
1 error generated.
make[2]: *** [ios_webkit_debug_proxy_main.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Can you please suggest how to resolve this?

**Comment by emilanova** [comment]
Hi all,

Obviously, this will not work with the commands above which are also official steps in the project README. If you want you can use "brew install ios-webkit-debug-proxy". Depending on the WiFi settings it shall work as expected.

**Comment by lbielski** [comment]
This helped me:  

export C_INCLUDE_PATH=/usr/local/include
export LIBRARY_PATH=/usr/local/lib
