### ISSUE TITLE
Not working with latest Chrome DevTools 38.0.2125.104

### ISSUE THREAD

**Issue by gapipro** [google/ios-webkit-debug-proxy#78]
When I visit chrome-devtools://devtools/bundled/devtools.html?host=localhost:9222&page=1 I get empty DevTools with no content under any panel. 

If I run DevTools on DevTools I can see that there was an error when loading

     Uncaught TypeError: Cannot read property 'frame' of undefined Main.js:4146

Can this be fixed?

**Comment by confile** [comment]
Does not work with OSX Chrome Version 38.0.2125.111

**Comment by kevin1024** [comment]
Yeah, I keep a separate install of Chrome 37 around just so I can use this tool.

**Comment by confile** [comment]
@kevin1024  Could you please post a link to Chrome 37?

**Comment by kevin1024** [comment]
@confile sure, I use Archlinux so I find old packages in the Arch Rollback Machine.  Here's a [direct link to an old chromium package](http://seblu.net/a/arm/2014/09/10/extra/os/x86_64/chromium-37.0.2062.94-1-x86_64.pkg.tar.xz).  I don't know what distro you use but they might have a similar service.

**Comment by confile** [comment]
@kevin1024 I use mac so I need a mac version. Do you have one too?

**Comment by kevin1024** [comment]
@confile Sorry I don't use Mac for this but if you're on Mac you can use the [official IOS Safari Remote Debugger](http://moduscreate.com/enable-remote-web-inspector-in-ios-6/)

**Comment by confile** [comment]
This does not help because I want to develop with the dev tool.

**Comment by richardkeen** [comment]
I worked around this by download Chromium 37 for Mac from here: http://sourceforge.net/projects/osxportableapps/files/Chromium/
