### ISSUE TITLE
JSON interface doesn't return valid JSON Object when page title has quotations in it. Not escaping properly

### ISSUE THREAD

**Issue by SidBala** [google/ios-webkit-debug-proxy#81]
One example is:

The Response Body is:[{
"devtoolsFrontendUrl": "/devtools/devtools.html?host=localhost:1142&page=1",
"faviconUrl": "",
"thumbnailUrl": "/thumb/http://sfbay.craigslist.org/search/ppa?query=air+conditioner+%7C+a%2Fc",
"title": "SF bay area appliances "air conditioner | a/c" - craigslist",
"url": "http://sfbay.craigslist.org/search/ppa?query=air+conditioner+%7C+a%2Fc",
"webSocketDebuggerUrl": "ws://localhost:1142/devtools/page/1"
}]

Notice how the title value has double quotations inside it that are not escaped. This is invalid JSON

**Comment by artygus** [comment]
should be fixed with f040da60759617cbf74ea3da19d22f29b7d5b566
