### ISSUE TITLE
Can't access ./autogen.sh after install

### ISSUE THREAD

**Issue by goldylucks** [google/ios-webkit-debug-proxy#88]
I'm on ubuntu 13.10.
After installing the dependencies, I'm trying to run ./autogen.sh but I get "commmand not found"

**Comment by viniciusrtf** [comment]
I"m on Ubuntu 14.10 and had the same problem.

Here is what I did:

1. sudo apt-get install libtool
2. compile libimobiledevice 1.2.0 from source (http://www.libimobiledevice.org/)
3. export LDFLAGS="$LDFLAGS -lm"
4. compile ios-webkit-debug-proxy from source according to README.md instructions.

**Comment by viniciusrtf** [comment]
Also had to compile a newer usbmuxd from source, and run "sudo ldconfig" before using ios-webkit-debug-proxy. After everything is installed and your iPhone is connected and recognized, you'll probably need to read issue #86 and use an old version of DevTools to be able to inspect anything.

**Comment by jmunsch** [comment]
Possibly related: https://github.com/google/ios-webkit-debug-proxy/issues/94

**Comment by artygus** [comment]
should be fixed with 8a90693a4fbd86f0c320c83954d6790b63381334
