### ISSUE TITLE
Problems building on Linux Ubuntu 12.04

### ISSUE THREAD

**Issue by ottonascarella** [google/ios-webkit-debug-proxy#9]
Hi there,

been having problems with the build on my machine.
firstly, I needed to install libimobiledevice-dev, which is not on your instructions and is needed.

now it's giving me the following error:
/usr/include/libimobiledevice/installation_proxy.h:31:18: fatal error: glib.h: No such file or directory

any help, please?

cheers in advance

**Comment by artygus** [comment]
as far as I understood from comments the problem doesn't exist if you build everything from sources and it's barely ios-webkit-debug-proxy problem, more likely it's the problem with one of the dev versions of packages of required libs (libimobiledevice, libusbmuxd, libplist)
