### ISSUE TITLE
Please update dependency versions for the latest release of ios-webkit-debug-proxy

### ISSUE THREAD

**Issue by oskosk** [google/ios-webkit-debug-proxy#95]

**Comment by uipoet** [comment]
And release a new version that we may once again use via `brew install ios-webkit-debug-proxy`. I thought this project was dead, given latest release date, that it no longer works and no commits until recently.

**Comment by jchuong** [comment]
The new release version of iwdp is now up on Homebrew, please try it out.

**Comment by Swapnillll** [comment]
@jchuong can you please push the fix for ios-webkit disconnecting in latest webkit release? Currently i'm using fork you had mentioned in one issue.

**Comment by jchuong** [comment]
I think you're using my fork?  If so, then those changes should be already merged in this repository already.

**Comment by Swapnillll** [comment]
I don't think so, when i use the brew install i still get disconnected. Only using the fork fixes it.
Not sure if i'm missing anything.  If possible can you let me know which release has that fix?

I'll try to test it again from latest release.

**Comment by artygus** [comment]
@Swapnillll make sure you ran `brew update` before `brew install ios-webkit-debug-proxy`

**Comment by Swapnillll** [comment]
Sure, i'll try that now.

**Comment by artygus** [comment]
@Swapnillll  also you can try `brew upgrade ios-webkit-debug-proxy`

**Comment by Swapnillll** [comment]
wow, i'm confused now. Taking brew update stated its already up to date. ios-webkit i had latest release but still was having issues.

I tried doing a clean install of the webkit and it fixed the issue. Not sure what caused this error. Looks like i have to do this for all of our test macs.

Anways, thanks a lot for the quick response and fix steps @artygus  and  @jchuong.
